// ⚙️ AUTO-GENERATED by scripts/generate-chapter-index.mjs — do not edit by hand
import type { ChapterRecord } from "../../types";

import { chapter as part_0_chapter_1 } from "./part-0/chapter-1";
import { chapter as part_0_chapter_2 } from "./part-0/chapter-2";
import { chapter as part_0_chapter_3 } from "./part-0/chapter-3";
import { chapter as part_0_chapter_4 } from "./part-0/chapter-4";
import { chapter as part_0_chapter_5 } from "./part-0/chapter-5";
import { chapter as part_0_chapter_6 } from "./part-0/chapter-6";
import { chapter as part_0_chapter_7 } from "./part-0/chapter-7";
import { chapter as part_1_chapter_1 } from "./part-1/chapter-1";
import { chapter as part_1_chapter_2 } from "./part-1/chapter-2";
import { chapter as part_1_chapter_3 } from "./part-1/chapter-3";
import { chapter as part_1_chapter_4 } from "./part-1/chapter-4";
import { chapter as part_2_chapter_1 } from "./part-2/chapter-1";
import { chapter as part_2_chapter_2 } from "./part-2/chapter-2";
import { chapter as part_2_chapter_3 } from "./part-2/chapter-3";
import { chapter as part_2_chapter_4 } from "./part-2/chapter-4";
import { chapter as part_2_chapter_5 } from "./part-2/chapter-5";
import { chapter as part_3_chapter_1 } from "./part-3/chapter-1";
import { chapter as part_3_chapter_2 } from "./part-3/chapter-2";
import { chapter as part_4_chapter_1 } from "./part-4/chapter-1";
import { chapter as part_4_chapter_2 } from "./part-4/chapter-2";
import { chapter as part_4_chapter_3 } from "./part-4/chapter-3";
import { chapter as part_5_chapter_1 } from "./part-5/chapter-1";
import { chapter as part_5_chapter_2 } from "./part-5/chapter-2";
import { chapter as part_5_chapter_3 } from "./part-5/chapter-3";
import { chapter as part_5_chapter_4 } from "./part-5/chapter-4";
import { chapter as part_5_chapter_5 } from "./part-5/chapter-5";
import { chapter as part_6_chapter_1 } from "./part-6/chapter-1";
import { chapter as part_6_chapter_2 } from "./part-6/chapter-2";
import { chapter as part_6_chapter_3 } from "./part-6/chapter-3";
import { chapter as part_6_chapter_4 } from "./part-6/chapter-4";
import { chapter as part_6_chapter_5 } from "./part-6/chapter-5";
import { chapter as part_6_chapter_6 } from "./part-6/chapter-6";
import { chapter as part_7_chapter_1 } from "./part-7/chapter-1";
import { chapter as part_7_chapter_2 } from "./part-7/chapter-2";
import { chapter as part_7_chapter_3 } from "./part-7/chapter-3";
import { chapter as part_7_chapter_4 } from "./part-7/chapter-4";
import { chapter as part_7_chapter_5 } from "./part-7/chapter-5";
import { chapter as part_7_chapter_6 } from "./part-7/chapter-6";
import { chapter as part_7_chapter_7 } from "./part-7/chapter-7";
import { chapter as part_8_chapter_1 } from "./part-8/chapter-1";
import { chapter as part_8_chapter_2 } from "./part-8/chapter-2";
import { chapter as part_8_chapter_3 } from "./part-8/chapter-3";
import { chapter as part_8_chapter_4 } from "./part-8/chapter-4";
import { chapter as part_8_chapter_5 } from "./part-8/chapter-5";
import { chapter as part_8_chapter_6 } from "./part-8/chapter-6";
import { chapter as part_9_chapter_1 } from "./part-9/chapter-1";
import { chapter as part_9_chapter_2 } from "./part-9/chapter-2";
import { chapter as part_9_chapter_3 } from "./part-9/chapter-3";
import { chapter as part_9_chapter_4 } from "./part-9/chapter-4";
import { chapter as part_9_chapter_5 } from "./part-9/chapter-5";
import { chapter as part_9_chapter_6 } from "./part-9/chapter-6";
import { chapter as part_9_chapter_7 } from "./part-9/chapter-7";
import { chapter as part_10_chapter_1 } from "./part-10/chapter-1";
import { chapter as part_10_chapter_2 } from "./part-10/chapter-2";
import { chapter as part_10_chapter_3 } from "./part-10/chapter-3";
import { chapter as part_10_chapter_4 } from "./part-10/chapter-4";
import { chapter as part_10_chapter_5 } from "./part-10/chapter-5";
import { chapter as part_11_chapter_1 } from "./part-11/chapter-1";
import { chapter as part_11_chapter_2 } from "./part-11/chapter-2";
import { chapter as part_11_chapter_3 } from "./part-11/chapter-3";
import { chapter as part_12_chapter_1 } from "./part-12/chapter-1";
import { chapter as part_12_chapter_2 } from "./part-12/chapter-2";
import { chapter as part_12_chapter_3 } from "./part-12/chapter-3";
import { chapter as part_13_chapter_1 } from "./part-13/chapter-1";
import { chapter as part_13_chapter_2 } from "./part-13/chapter-2";
import { chapter as part_13_chapter_3 } from "./part-13/chapter-3";
import { chapter as part_13_chapter_4 } from "./part-13/chapter-4";
import { chapter as part_13_chapter_5 } from "./part-13/chapter-5";
import { chapter as part_13_chapter_6 } from "./part-13/chapter-6";

export const chapterPaths: Record<string, string> = {
  "sql-0-1-background-how-an-app-is-built-ui-api-database-w": "part-0/chapter-1.ts",
  "sql-0-2-what-sql-is-why-it-comes-in-dialects-mysql-postg": "part-0/chapter-2.ts",
  "sql-0-3-what-testers-use-sql-for": "part-0/chapter-3.ts",
  "sql-0-4-read-only-vs-write-access-environments-dev-qa-st": "part-0/chapter-4.ts",
  "sql-0-5-db-users-roles-permissions": "part-0/chapter-5.ts",
  "sql-0-6-sample-database-how-to-follow-along": "part-0/chapter-6.ts",
  "sql-0-7-what-this-manual-does-not-cover-scope-where-to-g": "part-0/chapter-7.ts",
  "sql-1-1-databases-tables-rows-columns-schemas": "part-1/chapter-1.ts",
  "sql-1-2-data-types": "part-1/chapter-2.ts",
  "sql-1-3-select-from-where-basics": "part-1/chapter-3.ts",
  "sql-1-4-comparison-logical-operators": "part-1/chapter-4.ts",
  "sql-2-1-where-clause-deep-dive": "part-2/chapter-1.ts",
  "sql-2-2-order-by-limit-top-distinct": "part-2/chapter-2.ts",
  "sql-2-3-null-handling": "part-2/chapter-3.ts",
  "sql-2-4-functions-expressions-case-coalesce-nullif-strin": "part-2/chapter-4.ts",
  "sql-2-5-text-matching-gotchas": "part-2/chapter-5.ts",
  "sql-3-1-count-sum-avg-min-max": "part-3/chapter-1.ts",
  "sql-3-2-group-by-and-having": "part-3/chapter-2.ts",
  "sql-4-1-inner-left-right-full-joins": "part-4/chapter-1.ts",
  "sql-4-2-self-joins": "part-4/chapter-2.ts",
  "sql-4-3-practical-qa-scenario-validating-foreign-key-rel": "part-4/chapter-3.ts",
  "sql-5-1-subqueries-in-where-select-from": "part-5/chapter-1.ts",
  "sql-5-2-common-table-expressions": "part-5/chapter-2.ts",
  "sql-5-3-when-to-use-a-subquery-vs-a-join": "part-5/chapter-3.ts",
  "sql-5-4-set-operators-union-union-all-intersect-except": "part-5/chapter-4.ts",
  "sql-5-5-window-functions-row-number-rank-lag-lead-sum-ov": "part-5/chapter-5.ts",
  "sql-6-1-verifying-data-migration-etl-correctness": "part-6/chapter-1.ts",
  "sql-6-2-comparing-expected-vs-actual-data-sets": "part-6/chapter-2.ts",
  "sql-6-3-finding-duplicates-orphaned-records-mismatched-c": "part-6/chapter-3.ts",
  "sql-6-4-testing-schema-migration-scripts": "part-6/chapter-4.ts",
  "sql-6-5-schema-drift-checks-across-environments": "part-6/chapter-5.ts",
  "sql-6-6-before-after-snapshot-regression-validation": "part-6/chapter-6.ts",
  "sql-7-1-insert-update-delete": "part-7/chapter-1.ts",
  "sql-7-2-safely-seeding-cleaning-test-data": "part-7/chapter-2.ts",
  "sql-7-3-transactions-commit-rollback": "part-7/chapter-3.ts",
  "sql-7-4-ddl-awareness-create-alter-drop-truncate-vs-dele": "part-7/chapter-4.ts",
  "sql-7-5-bulk-test-data-generation": "part-7/chapter-5.ts",
  "sql-7-6-masking-anonymizing-pii": "part-7/chapter-6.ts",
  "sql-7-7-acid-isolation-levels-concurrency": "part-7/chapter-7.ts",
  "sql-8-1-primary-keys-foreign-keys-unique-constraints-ind": "part-8/chapter-1.ts",
  "sql-8-2-why-schema-knowledge-helps-you-write-better-test": "part-8/chapter-2.ts",
  "sql-8-3-views-triggers-stored-procedures": "part-8/chapter-3.ts",
  "sql-8-4-common-schema-patterns-soft-deletes-audit-column": "part-8/chapter-4.ts",
  "sql-8-5-query-performance-basics-explain-slow-queries-wh": "part-8/chapter-5.ts",
  "sql-8-6-exploring-an-unfamiliar-database": "part-8/chapter-6.ts",
  "sql-9-1-verifying-api-responses-against-db-state": "part-9/chapter-1.ts",
  "sql-9-2-using-sql-alongside-postman-pytest-cypress": "part-9/chapter-2.ts",
  "sql-9-3-cross-checking-business-logic": "part-9/chapter-3.ts",
  "sql-9-4-sql-with-playwright-ci-pipelines": "part-9/chapter-4.ts",
  "sql-9-5-pagination-sorting-filter-validation": "part-9/chapter-5.ts",
  "sql-9-6-dashboard-report-validation": "part-9/chapter-6.ts",
  "sql-9-7-sql-injection-basics-for-testers": "part-9/chapter-7.ts",
  "sql-10-1-finding-bugs-via-data-anomalies": "part-10/chapter-1.ts",
  "sql-10-2-building-reusable-sanity-check-queries": "part-10/chapter-2.ts",
  "sql-10-3-query-templates-for-attendance-payroll-appointme": "part-10/chapter-3.ts",
  "sql-10-4-leave-module-templates": "part-10/chapter-4.ts",
  "sql-10-5-approval-workflow-status-transition-checks": "part-10/chapter-5.ts",
  "sql-11-1-running-queries-via-db-clients": "part-11/chapter-1.ts",
  "sql-11-2-read-replicas-safe-environments": "part-11/chapter-2.ts",
  "sql-11-3-exporting-query-results-for-bug-reports": "part-11/chapter-3.ts",
  "sql-12-1-sample-hrms-practice-database-schema-seed-data": "part-12/chapter-1.ts",
  "sql-12-2-exercises-per-part-with-answers": "part-12/chapter-2.ts",
  "sql-12-3-mini-project-a-full-sanity-check-suite-for-one-m": "part-12/chapter-3.ts",
  "sql-13-1-cheat-sheet-of-common-queries": "part-13/chapter-1.ts",
  "sql-13-2-sql-syntax-differences-mysql-vs-postgresql-vs-sq": "part-13/chapter-2.ts",
  "sql-13-3-glossary-of-terms": "part-13/chapter-3.ts",
  "sql-13-4-common-sql-errors-how-to-fix-them": "part-13/chapter-4.ts",
  "sql-13-5-sample-database-schema-reference-er-overview": "part-13/chapter-5.ts",
  "sql-13-6-sql-interview-questions-for-qa-roles": "part-13/chapter-6.ts",
};

export const chapters: ChapterRecord[] = [
  part_0_chapter_1,
  part_0_chapter_2,
  part_0_chapter_3,
  part_0_chapter_4,
  part_0_chapter_5,
  part_0_chapter_6,
  part_0_chapter_7,
  part_1_chapter_1,
  part_1_chapter_2,
  part_1_chapter_3,
  part_1_chapter_4,
  part_2_chapter_1,
  part_2_chapter_2,
  part_2_chapter_3,
  part_2_chapter_4,
  part_2_chapter_5,
  part_3_chapter_1,
  part_3_chapter_2,
  part_4_chapter_1,
  part_4_chapter_2,
  part_4_chapter_3,
  part_5_chapter_1,
  part_5_chapter_2,
  part_5_chapter_3,
  part_5_chapter_4,
  part_5_chapter_5,
  part_6_chapter_1,
  part_6_chapter_2,
  part_6_chapter_3,
  part_6_chapter_4,
  part_6_chapter_5,
  part_6_chapter_6,
  part_7_chapter_1,
  part_7_chapter_2,
  part_7_chapter_3,
  part_7_chapter_4,
  part_7_chapter_5,
  part_7_chapter_6,
  part_7_chapter_7,
  part_8_chapter_1,
  part_8_chapter_2,
  part_8_chapter_3,
  part_8_chapter_4,
  part_8_chapter_5,
  part_8_chapter_6,
  part_9_chapter_1,
  part_9_chapter_2,
  part_9_chapter_3,
  part_9_chapter_4,
  part_9_chapter_5,
  part_9_chapter_6,
  part_9_chapter_7,
  part_10_chapter_1,
  part_10_chapter_2,
  part_10_chapter_3,
  part_10_chapter_4,
  part_10_chapter_5,
  part_11_chapter_1,
  part_11_chapter_2,
  part_11_chapter_3,
  part_12_chapter_1,
  part_12_chapter_2,
  part_12_chapter_3,
  part_13_chapter_1,
  part_13_chapter_2,
  part_13_chapter_3,
  part_13_chapter_4,
  part_13_chapter_5,
  part_13_chapter_6
];
