/** Pathwise catalog — Gutenberg, Standard Ebooks, Open Library, authors' free editions. */

export type LibraryBook = {
  id: string
  title: string
  author: string
  shelf: string
  shelves?: string[]
  blurb: string
  url: string
  source: string
  year?: string
}

export type LibraryShelf = {
  id: string
  label: string
  blurb: string
}

export const shelves: LibraryShelf[] = [
  { id: 'all', label: 'All shelves', blurb: 'Everything in the library.' },
  { id: 'study-guides', label: 'Study Guides', blurb: 'Cheat sheets, exam prep & interview blueprints.' },
  { id: 'tech-fiction', label: 'Tech & Sci-Fi Fiction', blurb: 'DevOps novels, cyber-thrillers & speculative fiction.' },
  { id: 'engineering-classics', label: 'Engineering Classics', blurb: 'System design, clean code, microservices & SRE.' },
  { id: 'tech', label: 'Tech & Learning', blurb: 'Free programming books and interactive tutorials.' },
  { id: 'career-leadership', label: 'Leadership & Career', blurb: 'Engineering management, staff developer paths & productivity.' },
  { id: 'fiction', label: 'Fiction', blurb: 'Stories worth finishing.' },
  { id: 'nonfiction', label: 'Nonfiction', blurb: 'Essays, history, ideas.' },
  { id: 'resources', label: 'Resources & Hubs', blurb: 'Catalogs, reference, documentation.' },
  { id: 'classics', label: 'Classics', blurb: 'Public-domain canon.' },
  { id: 'science', label: 'Science & Method', blurb: 'Nature, mind, and physics.' },
]

export const libraryBooks: LibraryBook[] = [
  // —— Romance (public domain) ——
  {
    id: 'pride-prejudice',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    shelf: 'romance',
    shelves: ['romance', 'fiction', 'classics'],
    blurb: 'Elizabeth Bennet, Mr. Darcy, and the long art of revising first impressions.',
    url: 'https://www.gutenberg.org/ebooks/1342',
    source: 'Project Gutenberg',
    year: '1813',
  },
  {
    id: 'sense-sensibility',
    title: 'Sense and Sensibility',
    author: 'Jane Austen',
    shelf: 'romance',
    shelves: ['romance', 'fiction', 'classics'],
    blurb: 'Two sisters, two temperaments, one inheritance problem.',
    url: 'https://www.gutenberg.org/ebooks/161',
    source: 'Project Gutenberg',
    year: '1811',
  },
  {
    id: 'emma',
    title: 'Emma',
    author: 'Jane Austen',
    shelf: 'romance',
    shelves: ['romance', 'fiction', 'classics'],
    blurb: 'Matchmaking gone stylishly wrong — then right.',
    url: 'https://www.gutenberg.org/ebooks/158',
    source: 'Project Gutenberg',
    year: '1815',
  },
  {
    id: 'persuasion',
    title: 'Persuasion',
    author: 'Jane Austen',
    shelf: 'romance',
    shelves: ['romance', 'fiction', 'classics'],
    blurb: 'Second chances, navy captains, and quieter longing.',
    url: 'https://www.gutenberg.org/ebooks/105',
    source: 'Project Gutenberg',
    year: '1817',
  },
  {
    id: 'jane-eyre',
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    shelf: 'romance',
    shelves: ['romance', 'fiction', 'classics'],
    blurb: 'Governess, mystery, moral steel — gothic romance done right.',
    url: 'https://www.gutenberg.org/ebooks/1260',
    source: 'Project Gutenberg',
    year: '1847',
  },
  {
    id: 'wuthering-heights',
    title: 'Wuthering Heights',
    author: 'Emily Brontë',
    shelf: 'romance',
    shelves: ['romance', 'fiction', 'classics'],
    blurb: 'Moors, obsession, and a love story that refuses to be tidy.',
    url: 'https://www.gutenberg.org/ebooks/768',
    source: 'Project Gutenberg',
    year: '1847',
  },
  {
    id: 'northanger-abbey',
    title: 'Northanger Abbey',
    author: 'Jane Austen',
    shelf: 'romance',
    shelves: ['romance', 'fiction', 'classics'],
    blurb: 'Gothic novels, Bath balls, and a heroine who reads too much.',
    url: 'https://www.gutenberg.org/ebooks/121',
    source: 'Project Gutenberg',
    year: '1817',
  },
  {
    id: 'scarlet-pimpernel',
    title: 'The Scarlet Pimpernel',
    author: 'Baroness Orczy',
    shelf: 'romance',
    shelves: ['romance', 'fiction'],
    blurb: 'Revolutionary intrigue with a dash of daring romance.',
    url: 'https://www.gutenberg.org/ebooks/60',
    source: 'Project Gutenberg',
    year: '1905',
  },

  // —— Fiction / classics ——
  {
    id: 'frankenstein',
    title: 'Frankenstein',
    author: 'Mary Shelley',
    shelf: 'fiction',
    shelves: ['fiction', 'classics', 'science'],
    blurb: 'Creation, responsibility, and the original lab-gone-wrong story.',
    url: 'https://www.gutenberg.org/ebooks/84',
    source: 'Project Gutenberg',
    year: '1818',
  },
  {
    id: 'dracula',
    title: 'Dracula',
    author: 'Bram Stoker',
    shelf: 'fiction',
    shelves: ['fiction', 'classics'],
    blurb: 'Letters, journals, and a Count who never sleeps.',
    url: 'https://www.gutenberg.org/ebooks/345',
    source: 'Project Gutenberg',
    year: '1897',
  },
  {
    id: 'alice',
    title: "Alice's Adventures in Wonderland",
    author: 'Lewis Carroll',
    shelf: 'fiction',
    shelves: ['fiction', 'classics'],
    blurb: 'Down the rabbit hole — logic puzzles dressed as nonsense.',
    url: 'https://www.gutenberg.org/ebooks/11',
    source: 'Project Gutenberg',
    year: '1865',
  },
  {
    id: 'sherlock',
    title: 'The Adventures of Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    shelf: 'fiction',
    shelves: ['fiction', 'classics'],
    blurb: 'Twelve cases. One consulting detective. Still sharp.',
    url: 'https://www.gutenberg.org/ebooks/1661',
    source: 'Project Gutenberg',
    year: '1892',
  },
  {
    id: 'dorian-gray',
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    shelf: 'fiction',
    shelves: ['fiction', 'classics'],
    blurb: 'Beauty, vanity, and a portrait that keeps the receipts.',
    url: 'https://www.gutenberg.org/ebooks/174',
    source: 'Project Gutenberg',
    year: '1890',
  },
  {
    id: 'metamorphosis',
    title: 'The Metamorphosis',
    author: 'Franz Kafka',
    shelf: 'fiction',
    shelves: ['fiction', 'classics'],
    blurb: 'Wake up as a bug. Keep going to work. Kafka.',
    url: 'https://www.gutenberg.org/ebooks/5200',
    source: 'Project Gutenberg',
    year: '1915',
  },
  {
    id: 'tale-two-cities',
    title: 'A Tale of Two Cities',
    author: 'Charles Dickens',
    shelf: 'classics',
    shelves: ['classics', 'fiction'],
    blurb: 'Best of times, worst of times — revolution and sacrifice.',
    url: 'https://www.gutenberg.org/ebooks/98',
    source: 'Project Gutenberg',
    year: '1859',
  },
  {
    id: 'great-expectations',
    title: 'Great Expectations',
    author: 'Charles Dickens',
    shelf: 'classics',
    shelves: ['classics', 'fiction'],
    blurb: 'Pip, estates, and the long cost of wanting more.',
    url: 'https://www.gutenberg.org/ebooks/1400',
    source: 'Project Gutenberg',
    year: '1861',
  },
  {
    id: 'anne-green-gables',
    title: 'Anne of Green Gables',
    author: 'L. M. Montgomery',
    shelf: 'fiction',
    shelves: ['fiction', 'romance'],
    blurb: 'Orphan with opinions, Prince Edward Island, and found family.',
    url: 'https://www.gutenberg.org/ebooks/45',
    source: 'Project Gutenberg',
    year: '1908',
  },
  {
    id: 'wizard-oz',
    title: 'The Wonderful Wizard of Oz',
    author: 'L. Frank Baum',
    shelf: 'fiction',
    shelves: ['fiction', 'classics'],
    blurb: 'Yellow brick road, friends found along the way.',
    url: 'https://www.gutenberg.org/ebooks/55',
    source: 'Project Gutenberg',
    year: '1900',
  },

  // —— Nonfiction / science ——
  {
    id: 'walden',
    title: 'Walden',
    author: 'Henry David Thoreau',
    shelf: 'nonfiction',
    shelves: ['nonfiction', 'classics'],
    blurb: 'A cabin, a pond, and deliberate living.',
    url: 'https://www.gutenberg.org/ebooks/205',
    source: 'Project Gutenberg',
    year: '1854',
  },
  {
    id: 'prophet',
    title: 'The Prophet',
    author: 'Kahlil Gibran',
    shelf: 'nonfiction',
    shelves: ['nonfiction', 'classics'],
    blurb: 'Short poetic essays on work, love, and leaving.',
    url: 'https://www.gutenberg.org/ebooks/58585',
    source: 'Project Gutenberg',
    year: '1923',
  },
  {
    id: 'origin-species',
    title: 'On the Origin of Species',
    author: 'Charles Darwin',
    shelf: 'science',
    shelves: ['science', 'nonfiction', 'classics'],
    blurb: 'Natural selection explained for a curious century.',
    url: 'https://www.gutenberg.org/ebooks/1228',
    source: 'Project Gutenberg',
    year: '1859',
  },
  {
    id: 'relativity',
    title: 'Relativity: The Special and General Theory',
    author: 'Albert Einstein',
    shelf: 'science',
    shelves: ['science', 'nonfiction'],
    blurb: 'Einstein writing for non-specialists — still a workout.',
    url: 'https://www.gutenberg.org/ebooks/5001',
    source: 'Project Gutenberg',
    year: '1916',
  },
  {
    id: 'prince',
    title: 'The Prince',
    author: 'Niccolò Machiavelli',
    shelf: 'nonfiction',
    shelves: ['nonfiction', 'classics'],
    blurb: 'Power, perception, and political realism — read critically.',
    url: 'https://www.gutenberg.org/ebooks/1232',
    source: 'Project Gutenberg',
    year: '1532',
  },
  {
    id: 'siddhartha',
    title: 'Siddhartha',
    author: 'Hermann Hesse',
    shelf: 'fiction',
    shelves: ['fiction', 'classics', 'nonfiction'],
    blurb: 'A seeker’s path beside a river — short and lasting.',
    url: 'https://www.gutenberg.org/ebooks/2500',
    source: 'Project Gutenberg',
    year: '1922',
  },

  // —— Tech & learning (author/publisher free editions) ——
  {
    id: 'automate-boring',
    title: 'Automate the Boring Stuff with Python',
    author: 'Al Sweigart',
    shelf: 'tech',
    shelves: ['tech', 'resources'],
    blurb: 'Practical Python for real chores — free online edition.',
    url: 'https://automatetheboringstuff.com/',
    source: 'Author free edition',
    year: '2019',
  },
  {
    id: 'eloquent-js',
    title: 'Eloquent JavaScript',
    author: 'Marijn Haverbeke',
    shelf: 'tech',
    shelves: ['tech', 'resources'],
    blurb: 'Modern JS from values to the browser — free book.',
    url: 'https://eloquentjavascript.net/',
    source: 'Author free edition',
    year: '2024',
  },
  {
    id: 'pro-git',
    title: 'Pro Git',
    author: 'Scott Chacon & Ben Straub',
    shelf: 'tech',
    shelves: ['tech', 'resources'],
    blurb: 'The Git book — branching, remotes, internals.',
    url: 'https://git-scm.com/book/en/v2',
    source: 'git-scm.com',
    year: '2014',
  },
  {
    id: 'think-python',
    title: 'Think Python',
    author: 'Allen B. Downey',
    shelf: 'tech',
    shelves: ['tech', 'resources'],
    blurb: 'Python as a way to think — free from Green Tea Press.',
    url: 'https://greenteapress.com/wp/think-python-2e/',
    source: 'Green Tea Press',
    year: '2015',
  },
  {
    id: 'linux-cli',
    title: 'The Linux Command Line',
    author: 'William Shotts',
    shelf: 'tech',
    shelves: ['tech', 'resources'],
    blurb: 'Shell fluency without the gatekeeping.',
    url: 'https://linuxcommand.org/tlcl.php',
    source: 'Author free edition',
    year: '2019',
  },
  {
    id: 'ydkjs',
    title: "You Don't Know JS Yet",
    author: 'Kyle Simpson',
    shelf: 'tech',
    shelves: ['tech'],
    blurb: 'Deep JS mental models — free on GitHub.',
    url: 'https://github.com/getify/You-Dont-Know-JS',
    source: 'GitHub',
    year: '2022',
  },
  {
    id: 'playwright-docs',
    title: 'Playwright Documentation',
    author: 'Microsoft',
    shelf: 'tech',
    shelves: ['tech', 'resources'],
    blurb: 'Official Playwright docs — pair with Pathwise manuals.',
    url: 'https://playwright.dev/docs/intro',
    source: 'playwright.dev',
  },
  {
    id: 'python-tutorial',
    title: 'The Python Tutorial',
    author: 'Python Software Foundation',
    shelf: 'tech',
    shelves: ['tech', 'resources'],
    blurb: 'Official tour of the language — always current.',
    url: 'https://docs.python.org/3/tutorial/',
    source: 'docs.python.org',
  },

  // —— Resources / hubs ——
  {
    id: 'gutenberg-catalog',
    title: 'Project Gutenberg Catalog',
    author: 'Project Gutenberg',
    shelf: 'resources',
    shelves: ['resources'],
    blurb: '70,000+ free public-domain ebooks. Start here to wander.',
    url: 'https://www.gutenberg.org/',
    source: 'Project Gutenberg',
  },
  {
    id: 'standard-ebooks',
    title: 'Standard Ebooks',
    author: 'Standard Ebooks',
    shelf: 'resources',
    shelves: ['resources', 'classics'],
    blurb: 'Carefully typeset public-domain classics — beautiful free EPUBs.',
    url: 'https://standardebooks.org/ebooks',
    source: 'Standard Ebooks',
  },
  {
    id: 'open-library',
    title: 'Open Library',
    author: 'Internet Archive',
    shelf: 'resources',
    shelves: ['resources'],
    blurb: 'Borrow scans and find editions — Internet Archive’s library.',
    url: 'https://openlibrary.org/',
    source: 'Open Library',
  },
  {
    id: 'internet-archive-texts',
    title: 'Internet Archive Texts',
    author: 'Internet Archive',
    shelf: 'resources',
    shelves: ['resources'],
    blurb: 'Millions of digitized books and periodicals.',
    url: 'https://archive.org/details/texts',
    source: 'Internet Archive',
  },
  {
    id: 'librivox',
    title: 'LibriVox',
    author: 'LibriVox volunteers',
    shelf: 'resources',
    shelves: ['resources'],
    blurb: 'Free public-domain audiobooks read by volunteers.',
    url: 'https://librivox.org/',
    source: 'LibriVox',
  },
  {
    id: 'mdn',
    title: 'MDN Web Docs',
    author: 'Mozilla',
    shelf: 'resources',
    shelves: ['resources', 'tech'],
    blurb: 'HTML, CSS, JS reference — the working developer’s shelf.',
    url: 'https://developer.mozilla.org/en-US/docs/Web',
    source: 'MDN',
  },

  // —— Study Guides & Interview Blueprints ——
  {
    id: 'system-design-primer',
    title: 'System Design Primer & Blueprint',
    author: 'Donne Martin',
    shelf: 'study-guides',
    shelves: ['study-guides', 'engineering-classics', 'tech'],
    blurb: 'Comprehensive open guide to designing large-scale systems, microservices, caches, and databases.',
    url: 'https://github.com/donnemartin/system-design-primer',
    source: 'GitHub Open Guide',
    year: '2024',
  },
  {
    id: 'playwright-cheatsheet',
    title: 'Playwright & E2E Testing Study Guide',
    author: 'Microsoft & Pathwise',
    shelf: 'study-guides',
    shelves: ['study-guides', 'tech'],
    blurb: 'Complete locator strategy cheat sheet, assertion patterns, and CI pipeline setup guide.',
    url: 'https://playwright.dev/docs/intro',
    source: 'playwright.dev',
    year: '2025',
  },
  {
    id: 'aws-cloud-practitioner',
    title: 'AWS Architecture & Cloud Practitioner Guide',
    author: 'Amazon Web Services',
    shelf: 'study-guides',
    shelves: ['study-guides', 'tech'],
    blurb: 'Official cloud architecture frameworks, IAM policies, VPC subnetting, and serverless blueprints.',
    url: 'https://aws.amazon.com/architecture/',
    source: 'AWS Documentation',
    year: '2024',
  },
  {
    id: 'docker-k8s-blueprint',
    title: 'Docker & Kubernetes Operator Study Guide',
    author: 'Cloud Native Computing Foundation',
    shelf: 'study-guides',
    shelves: ['study-guides', 'tech', 'engineering-classics'],
    blurb: 'Container isolation, Dockerfile multi-stage builds, Pod scheduling, and Ingress routing cheat sheet.',
    url: 'https://kubernetes.io/docs/concepts/',
    source: 'CNCF Documentation',
    year: '2024',
  },
  {
    id: 'distributed-systems-raft',
    title: 'Raft Consensus & Distributed Systems Visual Guide',
    author: 'Diego Ongaro & John Ousterhout',
    shelf: 'study-guides',
    shelves: ['study-guides', 'science', 'tech'],
    blurb: 'Understand leader election, log replication, and Byzantine fault tolerance intuitively.',
    url: 'https://raft.github.io/',
    source: 'Raft GitHub',
    year: '2023',
  },
  {
    id: 'sql-indexing-guide',
    title: 'Use The Index, Luke! SQL Tuning Study Guide',
    author: 'Markus Winand',
    shelf: 'study-guides',
    shelves: ['study-guides', 'tech'],
    blurb: 'Essential guide to B-tree indexes, execution plans, join algorithms, and slow query optimization.',
    url: 'https://use-the-index-luke.com/',
    source: 'Author Free Edition',
    year: '2023',
  },
  {
    id: 'interactive-python-ds',
    title: 'Problem Solving with Algorithms & Data Structures',
    author: 'Brad Miller & David Ranum',
    shelf: 'study-guides',
    shelves: ['study-guides', 'tech', 'science'],
    blurb: 'Interactive study guide covering stacks, trees, graphs, sorting, and Big-O complexity analysis.',
    url: 'https://runestone.academy/ns/books/published/pythonds3/index.html',
    source: 'Runestone Academy',
    year: '2022',
  },
  {
    id: 'react-server-components-guide',
    title: 'React Server Components & Next.js 15 Guide',
    author: 'Vercel Engineering',
    shelf: 'study-guides',
    shelves: ['study-guides', 'tech'],
    blurb: 'Deep dive into streaming SSR, Server Actions, hydration boundaries, and caching layers.',
    url: 'https://nextjs.org/docs',
    source: 'Vercel Docs',
    year: '2025',
  },

  // —— Tech Fiction & Systems Novels (DevOps / Cyber Thrillers / Sci-Fi) ——
  {
    id: 'phoenix-project',
    title: 'The Phoenix Project',
    author: 'Gene Kim, Kevin Behr & George Spafford',
    shelf: 'tech-fiction',
    shelves: ['tech-fiction', 'fiction', 'engineering-classics'],
    blurb: 'A legendary novel about IT, DevOps, WIP limits, and helping an enterprise manufacturing company survive.',
    url: 'https://itrevolution.com/product/the-phoenix-project/',
    source: 'IT Revolution Press',
    year: '2013',
  },
  {
    id: 'unicorn-project',
    title: 'The Unicorn Project',
    author: 'Gene Kim',
    shelf: 'tech-fiction',
    shelves: ['tech-fiction', 'fiction', 'engineering-classics'],
    blurb: 'A gripping software novel on the Five Ideals: Locality, Simplicity, Focus, Flow, and Psychological Safety.',
    url: 'https://itrevolution.com/product/the-unicorn-project/',
    source: 'IT Revolution Press',
    year: '2019',
  },
  {
    id: 'the-goal',
    title: 'The Goal: A Process of Ongoing Improvement',
    author: 'Eliyahu M. Goldratt',
    shelf: 'tech-fiction',
    shelves: ['tech-fiction', 'fiction', 'career-leadership'],
    blurb: 'The classic business novel introducing the Theory of Constraints that inspired modern DevOps thinking.',
    url: 'https://openlibrary.org/books/OL24213506M/The_Goal',
    source: 'Open Library',
    year: '1984',
  },
  {
    id: 'neuromancer',
    title: 'Neuromancer',
    author: 'William Gibson',
    shelf: 'tech-fiction',
    shelves: ['tech-fiction', 'fiction', 'classics'],
    blurb: 'The seminal cyberpunk novel that coined "cyberspace" — Case, Molly Millions, and Artificial Intelligences.',
    url: 'https://openlibrary.org/works/OL871261W/Neuromancer',
    source: 'Open Library',
    year: '1984',
  },
  {
    id: 'snow-crash',
    title: 'Snow Crash',
    author: 'Neal Stephenson',
    shelf: 'tech-fiction',
    shelves: ['tech-fiction', 'fiction'],
    blurb: 'The Metaverse, pizza delivery in a high-speed car, and linguistic computer viruses.',
    url: 'https://openlibrary.org/works/OL1804791W/Snow_Crash',
    source: 'Open Library',
    year: '1992',
  },
  {
    id: 'cryptonomicon',
    title: 'Cryptonomicon',
    author: 'Neal Stephenson',
    shelf: 'tech-fiction',
    shelves: ['tech-fiction', 'fiction'],
    blurb: 'WWII codebreakers meet 1990s cypherpunks building an underground data haven.',
    url: 'https://openlibrary.org/works/OL1804787W/Cryptonomicon',
    source: 'Open Library',
    year: '1999',
  },
  {
    id: 'daemon',
    title: 'Daemon',
    author: 'Daniel Suarez',
    shelf: 'tech-fiction',
    shelves: ['tech-fiction', 'fiction'],
    blurb: 'A game designer dies and leaves behind a autonomous computer program that starts restructuring society.',
    url: 'https://openlibrary.org/works/OL8305080W/Daemon',
    source: 'Open Library',
    year: '2006',
  },
  {
    id: 'exhalation',
    title: 'Exhalation: Stories',
    author: 'Ted Chiang',
    shelf: 'tech-fiction',
    shelves: ['tech-fiction', 'fiction', 'science'],
    blurb: 'Profound philosophical sci-fi stories on time travel, AI software pets, and entropy.',
    url: 'https://openlibrary.org/works/OL19808381W/Exhalation',
    source: 'Open Library',
    year: '2019',
  },

  // —— Engineering & Systems Architecture Classics ——
  {
    id: 'ddia',
    title: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    shelf: 'engineering-classics',
    shelves: ['engineering-classics', 'tech', 'resources'],
    blurb: 'The definitive guide to reliability, scalability, transactions, replication, and consensus in distributed systems.',
    url: 'https://dataintensive.net/',
    source: 'Author Site / O’Reilly',
    year: '2017',
  },
  {
    id: 'pragmatic-programmer',
    title: 'The Pragmatic Programmer',
    author: 'Andrew Hunt & David Thomas',
    shelf: 'engineering-classics',
    shelves: ['engineering-classics', 'tech', 'career-leadership'],
    blurb: 'Timeless advice from orthogonality to tracer bullets and taking pride in your craft.',
    url: 'https://pragprog.com/titles/tpp20/the-pragmatic-programmer-20th-anniversary-edition/',
    source: 'Pragmatic Bookshelf',
    year: '2019',
  },
  {
    id: 'clean-code',
    title: 'Clean Code: A Handbook of Agile Craftsmanship',
    author: 'Robert C. Martin',
    shelf: 'engineering-classics',
    shelves: ['engineering-classics', 'tech'],
    blurb: 'Meaningful names, small single-responsibility functions, clean formatting, and error handling.',
    url: 'https://openlibrary.org/works/OL15842823W/Clean_Code',
    source: 'Open Library',
    year: '2008',
  },
  {
    id: 'google-sre-book',
    title: 'Site Reliability Engineering (Google SRE Book)',
    author: 'Betsy Beyer, Chris Jones, Jennifer Petoff & Niall Richard Murphy',
    shelf: 'engineering-classics',
    shelves: ['engineering-classics', 'tech', 'resources'],
    blurb: 'How Google operates production systems — SLOs, error budgets, blameless postmortems, and automation.',
    url: 'https://sre.google/sre-book/table-of-contents/',
    source: 'Google Free Online Book',
    year: '2016',
  },
  {
    id: 'refactoring',
    title: 'Refactoring: Improving the Design of Existing Code',
    author: 'Martin Fowler',
    shelf: 'engineering-classics',
    shelves: ['engineering-classics', 'tech'],
    blurb: 'Catalog of code smells and step-by-step transformations to make software clean and resilient.',
    url: 'https://martinfowler.com/books/refactoring.html',
    source: 'MartinFowler.com',
    year: '2018',
  },
  {
    id: 'building-microservices',
    title: 'Building Microservices',
    author: 'Sam Newman',
    shelf: 'engineering-classics',
    shelves: ['engineering-classics', 'tech'],
    blurb: 'Modeling microservices, API gateways, database decomposition patterns, and service mesh architecture.',
    url: 'https://samnewman.io/books/building_microservices_2nd_edition/',
    source: 'SamNewman.io',
    year: '2021',
  },
  {
    id: 'accelerate',
    title: 'Accelerate: Lean Software and DevOps',
    author: 'Nicole Forsgren, Jez Humble & Gene Kim',
    shelf: 'engineering-classics',
    shelves: ['engineering-classics', 'career-leadership', 'tech'],
    blurb: 'Rigorous empirical research measuring DORA metrics: Deployment Frequency, Lead Time, MTTR, and Change Failure Rate.',
    url: 'https://itrevolution.com/product/accelerate/',
    source: 'IT Revolution',
    year: '2018',
  },
  {
    id: 'staff-engineer',
    title: 'Staff Engineer: Leadership Beyond Management',
    author: 'Will Larson',
    shelf: 'career-leadership',
    shelves: ['career-leadership', 'engineering-classics', 'tech'],
    blurb: 'Navigating the Staff, Principal, and Distinguished Engineer tracks while setting technical direction.',
    url: 'https://staffeng.com/book',
    source: 'StaffEng.com',
    year: '2021',
  },
  {
    id: 'domain-driven-design',
    title: 'Domain-Driven Design',
    author: 'Eric Evans',
    shelf: 'engineering-classics',
    shelves: ['engineering-classics', 'tech'],
    blurb: 'Tackling complexity in software by matching code structure to Ubiquitous Domain Models and Bounded Contexts.',
    url: 'https://openlibrary.org/works/OL3305459W/Domain-driven_design',
    source: 'Open Library',
    year: '2003',
  },

  // —— Sci-Fi & Classic Literature ——
  {
    id: 'time-machine',
    title: 'The Time Machine',
    author: 'H. G. Wells',
    shelf: 'fiction',
    shelves: ['fiction', 'classics', 'science'],
    blurb: 'The Time Traveller journeys to 802,701 AD to encounter the Eloi and Morlocks.',
    url: 'https://www.gutenberg.org/ebooks/35',
    source: 'Project Gutenberg',
    year: '1895',
  },
  {
    id: 'war-of-worlds',
    title: 'The War of the Worlds',
    author: 'H. G. Wells',
    shelf: 'fiction',
    shelves: ['fiction', 'classics', 'science'],
    blurb: 'Martian tripods land in Victorian England equipped with Heat-Rays and Black Smoke.',
    url: 'https://www.gutenberg.org/ebooks/36',
    source: 'Project Gutenberg',
    year: '1898',
  },
  {
    id: 'twenty-thousand-leagues',
    title: 'Twenty Thousand Leagues Under the Sea',
    author: 'Jules Verne',
    shelf: 'fiction',
    shelves: ['fiction', 'classics', 'science'],
    blurb: 'Captain Nemo commands the futuristic submarine Nautilus through deep ocean abysses.',
    url: 'https://www.gutenberg.org/ebooks/164',
    source: 'Project Gutenberg',
    year: '1870',
  },
  {
    id: 'world-eighty-days',
    title: 'Around the World in Eighty Days',
    author: 'Jules Verne',
    shelf: 'fiction',
    shelves: ['fiction', 'classics'],
    blurb: 'Phileas Fogg and Passepartout embark on a timed voyage across steamers and railways.',
    url: 'https://www.gutenberg.org/ebooks/103',
    source: 'Project Gutenberg',
    year: '1872',
  },
]

export function bookShelves(book: LibraryBook) {
  return book.shelves || [book.shelf]
}

export function booksOnShelf(shelfId: string) {
  if (!shelfId || shelfId === 'all') return libraryBooks
  return libraryBooks.filter((b) => bookShelves(b).includes(shelfId))
}

export function searchBooks(query: string, shelfId = 'all') {
  const q = query.trim().toLowerCase()
  return booksOnShelf(shelfId).filter((b) => {
    if (!q) return true
    return (
      b.title.toLowerCase().includes(q) ||
      b.author.toLowerCase().includes(q) ||
      b.blurb.toLowerCase().includes(q) ||
      b.source.toLowerCase().includes(q)
    )
  })
}

export function gutenbergCoverUrl(book: LibraryBook) {
  const m = book.url.match(/gutenberg\.org\/ebooks\/(\d+)/)
  return m ? `https://www.gutenberg.org/cache/epub/${m[1]}/pg${m[1]}.cover.medium.jpg` : null
}
