import type { TestingChapterData } from "@/app/manuals/_ui/TestingTypesInteractiveManual";

/** Parts 19–22 — Chapters 73–88 (final) */
export const TESTING_TYPES_PARTS_19_22: TestingChapterData[] = [
  {
    no: "73",
    title: "Continuous Testing (CI/CD)",
    category: "Automation Strategy",
    desc: "Continuous testing is the practice of wiring automated tests directly into the CI/CD pipeline so they run automatically on every commit, pull request, or deployment — not a distinct kind of test in itself, but a delivery strategy that determines when and how automatically every other test type in this manual actually gets executed.",
    why: "A great automated test suite that only ever gets run manually, occasionally, before a release, provides almost none of its real value — bugs sit undetected for days or weeks before anyone notices, and by the time someone does, the change that caused them is buried under dozens of other commits, making it far harder to isolate. Continuous testing closes that gap by making test execution an automatic, unavoidable part of the delivery process itself, so feedback arrives within minutes of the change that caused a problem, while it's still fresh and easy to trace.",
    when: "From the very start of a project, growing in scope as the test suite grows — unit and fast integration tests wired in first since they need to run on every single commit, with slower suites (full regression, performance, soak tests) scheduled less frequently (nightly, or before release) so the fast feedback loop on every commit stays fast.",
    advantages: [
      "Shrinks the gap between a bug being introduced and being caught from days/weeks down to minutes",
      "Makes running tests a mandatory, automatic part of delivery rather than something that depends on someone remembering to do it",
      "Gives every pull request an objective, consistent quality gate before it can be merged",
      "Both tools have generous free tiers well within reach of a small-to-mid-sized team",
    ],
    limitations: [
      "A slow, poorly-organized pipeline can itself become a bottleneck the team starts trying to work around rather than benefit from",
      "Only as good as the underlying test suite — continuous testing amplifies a strong suite, but doesn't create test coverage that doesn't already exist",
      "Jenkins in particular carries real setup and ongoing maintenance overhead compared to a hosted option",
      "Flaky tests in a CI pipeline are especially costly, since they erode trust in the pipeline and get ignored/re-run rather than fixed",
    ],
    practical: {
      app: "HRMS Payroll Calculation Regression",
      scenario:
        "The Bizlevate team wires its regression suite into GitHub Actions to run on every pull request touching the Payroll module.",
      fail: "A developer changes the tax-bracket rounding logic; the change is only caught two weeks later during manual pre-release testing, by which point six other commits have touched the same file, making it much harder to isolate exactly which change caused the regression.",
      failLabel: "Fail (before)",
      pass: "With the regression suite wired into GitHub Actions, the same rounding bug is caught within four minutes of the pull request being opened, blocking the merge with a clear failing-test link directly in the PR, while the change is still fresh in the developer's mind.",
      passLabel: "Pass (after fix)",
    },
    tools: [
      {
        name: "GitHub Actions",
        sub: "Hosted CI in the repo",
        url: "https://github.com/features/actions",
        desc: "A CI/CD platform built directly into GitHub — workflows are defined as YAML files stored in the repository itself, triggered automatically by events like a push or pull request, with no separate server to host or maintain.",
        adv: [
          "No separate server to host or maintain",
          "Runs on every push and pull request from a file in the repo",
          "Failed checks can block merge when branch protection is on",
          "Generous free tier for small-to-mid-sized teams",
        ],
        lim: [
          "A slow workflow becomes a bottleneck the team starts to work around",
          "Only as good as the tests it runs",
          "Flaky tests erode trust and get ignored",
          "Hosted minutes can run out on very large matrices",
        ],
        steps: [
          {
            t: "Step 1 — Add a workflow file",
            p: "Create .github/workflows/test.yml that installs dependencies and runs the suite.",
            c: `name: Test\non: [push, pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 22\n      - run: npm ci && npm test`,
          },
          { t: "Step 2 — Trigger on every relevant change", p: "on: [push, pull_request] so it is not optional." },
          { t: "Step 3 — Fail the check on a red suite", p: "With branch protection, a failed run blocks the merge." },
          { t: "Step 4 — Use a build matrix when needed", p: "Same suite across Node versions, browsers, or OS in parallel." },
          { t: "Step 5 — Read failures in the Actions tab", p: "Which test failed and why, in the GitHub UI on the PR." },
        ],
      },
      {
        name: "Jenkins",
        sub: "Self-hosted pipeline",
        url: "https://jenkins.io",
        desc: "A free, self-hosted automation server with a long track record — more setup and maintenance overhead than a hosted service like GitHub Actions, but highly flexible and well suited to complex, multi-stage, or on-premises pipelines.",
        adv: [
          "Highly flexible for complex or on-premises pipelines",
          "Pipeline as code via a Jenkinsfile in the repo",
          "Build history shows pass/fail trends, not just the latest run",
          "Free and self-hosted — no per-minute hosted cost",
        ],
        lim: [
          "Real setup and ongoing maintenance overhead vs a hosted option",
          "A slow, poorly-organized pipeline becomes a bottleneck",
          "Does not create coverage the suite does not already have",
          "Flaky stages get re-run instead of fixed",
        ],
        steps: [
          { t: "Step 1 — Install Jenkins", p: "Dedicated server or container, then a new Pipeline job." },
          {
            t: "Step 2 — Check in a Jenkinsfile",
            p: "Stages for build, test, deploy live in the repository.",
            c: `pipeline {\n  agent any\n  stages {\n    stage('Test') {\n      steps { sh 'npm ci && npm test' }\n    }\n  }\n}`,
          },
          { t: "Step 3 — Webhook on every commit", p: "Jenkins triggers automatically when the repo is pushed." },
          { t: "Step 4 — Fail the build and notify", p: "Email or Slack when the test stage fails." },
          { t: "Step 5 — Watch trends on the dashboard", p: "Pass/fail history over time, not only the latest run." },
        ],
      },
    ],
  },
  {
    no: "74",
    title: "Interoperability Testing",
    category: "Non-Functional",
    desc: "Interoperability testing verifies that an application correctly exchanges data and functions correctly when integrated with other independent systems it doesn't control — third-party tools, partner systems, external APIs — checking the real integration, not a mocked or assumed version of it.",
    why: "Integration tests inside your own codebase (Chapter 2) typically test your own modules against each other, or against mocks standing in for external systems — useful, but they can't catch a real mismatch between what your system assumes an external partner does and what that partner actually does in practice. Interoperability testing is what specifically closes that gap, by testing against the real (or realistically sandboxed) external system itself, where genuine format mismatches, timing issues, and undocumented behavior actually live.",
    when: "Whenever the application exchanges data with any external system it doesn't fully control — a banking export format, a government tax-filing API, a third-party SSO provider — tested against a real or sandboxed instance of that system specifically, not just a mock standing in for it.",
    advantages: [
      "Confirms real-world integrations actually work, rather than only working against your own internal assumptions of them",
      "Catches format/contract mismatches with a partner system before a real client or user is affected by them",
      "Specifically tests failure-mode behavior (partner system down/slow/erroring), which is exactly when integration bugs cause the most visible damage",
      "Turning the check into a saved Postman collection makes it repeatable instead of a one-off manual verification",
    ],
    limitations: [
      "Requires access to a real or realistic sandbox of the external system, which isn't always available or fully representative of production behavior",
      "External systems can change behavior outside your control, silently breaking a previously-passing interoperability check",
      "Doesn't cover UI-level integration issues (e.g. an embedded third-party widget rendering incorrectly) — that's closer to compatibility or GUI testing",
      "Testing failure-mode behavior realistically (a partner truly going down) can be hard to simulate faithfully against a live external system",
    ],
    practical: {
      app: "HRMS Bank File Export",
      scenario: "Bizlevate's payroll export is tested against a client's real external banking system's file-import sandbox.",
      fail: "The payroll export produces a file that passes every internal validation check, but the bank's import sandbox rejects it — the bank expects a fixed-width field for the routing number, while Bizlevate exports it as a variable-width, comma-delimited field, a mismatch invisible from internal testing alone.",
      pass: "The export format is corrected to match the bank's fixed-width specification exactly, re-verified by re-submitting the corrected file to the same banking sandbox and confirming a clean import.",
      passLabel: "Pass (after fix)",
    },
    tools: [
      {
        name: "Postman",
        sub: "Repeatable real-partner exchange",
        url: "https://postman.com",
        seeChapter: 2,
        desc: "Rather than testing an external integration purely by hand each time, Postman lets the exact request/response exchange with the external system be scripted once and re-run identically on demand — turning an ad-hoc manual check into a repeatable, shareable test.",
        adv: [
          "Confirms the real partner, not a mock of it",
          "Catches format/contract mismatches before a client is hit",
          "Failure-mode checks (slow, error, unreachable) are explicit",
          "A saved collection is repeatable after either side changes",
        ],
        lim: [
          "Needs a real or realistic sandbox of the partner",
          "Partners can change behavior outside your control",
          "Does not cover embedded-widget UI issues",
          "True partner-down is hard to simulate on a live system",
        ],
        steps: [
          { t: "Step 1 — List every external system", p: "And what each integration point is supposed to do." },
          { t: "Step 2 — Hit the real or sandboxed partner", p: "A Postman request (or collection) against the actual exchange." },
          { t: "Step 3 — Well-formed and edge-case data", p: "Verify the partner's actual response matches what your app assumes." },
          { t: "Step 4 — Slow, error, and unreachable", p: "How your app behaves when the partner is not fine." },
          { t: "Step 5 — Both directions", p: "Data received, interpreted, and displayed correctly on each side." },
          { t: "Step 6 — Save as a named collection", p: "Re-run after any change to either system." },
        ],
      },
    ],
  },
  {
    no: "75",
    title: "Conformance Testing",
    category: "Non-Functional",
    desc: "Conformance testing verifies that an application's output — typically HTML/CSS markup, but potentially any defined protocol or specification — actually conforms to a formal external standard, checked directly against that standard's own official validator rather than against internal expectations of what \"correct\" looks like.",
    why: "Code can render correctly in the one or two browsers a team happens to test in while still silently violating the underlying standard those browsers are simply being lenient about — technical debt that surfaces later as unpredictable rendering in a browser or tool that isn't as forgiving, as an accessibility failure, or simply as markup that's harder to maintain than it needs to be. Conformance testing catches that gap directly and early, against an authoritative, objective standard rather than \"did it look fine in Chrome.\"",
    when: "Periodically across development, and specifically after any significant markup/template change — cheap and fast enough to run routinely rather than saved only for a final pre-release check.",
    advantages: [
      "Checks against an objective, authoritative external standard rather than \"does it look right in my browser\"",
      "Free, instant, and requires no setup — just a URL or pasted markup",
      "Improves compatibility with standards-compliant tools and assistive technology beyond just mainstream browsers",
      "Catches structural markup issues that often correlate with, and contribute to, accessibility problems",
    ],
    limitations: [
      "A page can be fully standards-conformant and still be a poor user experience — conformance and quality/usability are related but distinct",
      "Doesn't test JavaScript-driven dynamic content well if the validator only sees the initial server-rendered markup",
      "Some flagged warnings are genuinely minor and not worth the effort to chase down immediately",
      "Doesn't cover protocols or specifications outside HTML/CSS — a different, dedicated validator is needed for other kinds of conformance (e.g. specific API/data-format standards)",
    ],
    practical: {
      app: "HRMS Public Careers Page",
      scenario: "Bizlevate's public-facing careers/landing page is submitted to the W3C validator after a template redesign.",
      fail: "The validator flags several unclosed <div> tags and a form input missing an associated <label> — markup that happened to render acceptably in the team's usual browser, but represents both a real accessibility gap and a fragile structure likely to break unpredictably elsewhere.",
      pass: "The unclosed tags are fixed and proper <label> elements are added to every form input; re-validating the same page returns zero errors, and the associated labels additionally improve the page's accessibility score.",
      passLabel: "Pass (after fix)",
    },
    tools: [
      {
        name: "W3C Markup Validation Service",
        sub: "Official HTML/CSS validator",
        url: "https://validator.w3.org",
        desc: "The official, authoritative validator for HTML and CSS, maintained by the World Wide Web Consortium (W3C) itself — checks submitted markup directly against the formal HTML/CSS specification and returns a precise, line-numbered list of every violation found.",
        adv: [
          "Authoritative external standard, not \"looks fine in Chrome\"",
          "Free, instant, no setup — URL or pasted markup",
          "Helps assistive tech and strict browsers",
          "Structural issues often correlate with accessibility gaps",
        ],
        lim: [
          "Conformant is not the same as usable",
          "JS-driven DOM may not be what the validator sees",
          "Some warnings are not worth chasing immediately",
          "HTML/CSS only — other specs need their own validator",
        ],
        steps: [
          { t: "Step 1 — Submit the page", p: "URL or paste raw markup into the validator." },
          { t: "Step 2 — Read errors and warnings", p: "Line-numbered list against the formal spec." },
          { t: "Step 3 — Prioritize real impact", p: "Unclosed tags and invalid nesting over purely cosmetic warnings." },
          { t: "Step 4 — Fix the template, not one instance", p: "So the fix applies everywhere that markup is used." },
          { t: "Step 5 — Re-submit the same page", p: "Confirm issues are gone and nothing new appeared." },
          { t: "Step 6 — Make it routine", p: "After any significant template/markup change, not only pre-release." },
        ],
      },
    ],
  },
  {
    no: "76",
    title: "Globalization Testing",
    category: "Non-Functional",
    desc: "Globalization testing verifies that an application's underlying design and codebase are actually built to support being adapted to multiple languages and regions in the first place — checking the foundation itself (no hard-coded strings, flexible layout, proper character encoding) — distinct from localization testing (Chapter 23), which checks a specific already-translated locale.",
    why: "An application can be fully, correctly translated into a new language and still fail badly in practice if the underlying codebase was never actually built to support that — a hard-coded date format, a UI layout that assumes short English words and breaks when a translated label runs twice as long, text rendered with an encoding that can't display certain characters at all. Globalization testing catches these foundational gaps before real translation work begins, so localization efforts aren't undermined by problems baked into the code itself.",
    when: "Early, ideally during initial design and development — retrofitting genuine globalization support into a codebase that was never built with it is significantly more expensive than building it in from the start, and this check is what verifies that foundation is actually in place before any specific locale gets built on top of it.",
    advantages: [
      "Catches foundational internationalization gaps before they're compounded by actual translation and localization work built on top of them",
      "Automated string-scanning finds hard-coded text far more reliably and completely than manual code review alone",
      "Much cheaper to fix at this stage than to retrofit after the codebase has grown around the assumption of a single hard-coded language",
      "Directly de-risks future expansion into new markets, which frequently arrives later as a business requirement with a tight timeline",
    ],
    limitations: [
      "Automated scanning for hard-coded strings can still produce false positives/negatives depending on how the codebase is structured",
      "Testing with an artificially lengthened placeholder locale approximates, but doesn't perfectly predict, how every real target language will actually behave",
      "Doesn't verify translation quality or cultural appropriateness at all — that's the separate concern of localization testing (Chapter 23)",
      "Requires genuine buy-in to fix flagged issues structurally, rather than working around them locally each time they cause a visible problem",
    ],
    practical: {
      app: "HRMS Sales Pipeline Module",
      scenario: "Bizlevate's Sales Pipeline module is scanned with i18n-ally ahead of a planned expansion into new regional markets.",
      fail: "The scan reveals several UI labels are hard-coded directly into component files rather than pulled from a translation resource, and manually testing with lengthened placeholder text shows the \"Deal Stage\" column header overlapping adjacent columns once text length roughly doubles.",
      pass: "The hard-coded labels are moved into proper translation resource files and the column layout is adjusted to accommodate longer text gracefully; re-running both the i18n-ally scan and the lengthened-placeholder layout check confirms the module is now genuinely ready for translation into a new locale.",
      passLabel: "Pass (after fix)",
    },
    tools: [
      {
        name: "i18n-ally",
        sub: "Hard-coded string scan",
        url: "https://github.com/lokalise/i18n-ally",
        seeChapter: 23,
        desc: "A free, open-source VS Code extension that automatically scans a codebase for hard-coded, non-internationalized strings and highlights them directly in the editor, rather than relying purely on a human reviewer to spot every instance by eye.",
        adv: [
          "Finds hard-coded UI text more completely than review by eye",
          "Cheaper to fix before translation work starts",
          "De-risks later market expansion under a tight timeline",
          "Pairs with a lengthened-placeholder layout check",
        ],
        lim: [
          "False positives/negatives depending on project structure",
          "Doubled strings only approximate real target languages",
          "Does not judge translation quality (Chapter 23)",
          "Needs buy-in to fix structurally, not locally each time",
        ],
        steps: [
          { t: "Step 1 — Install and point at the repo", p: "i18n-ally in VS Code against the project codebase." },
          { t: "Step 2 — Scan for hard-coded UI text", p: "Strings that are not pulled from a translation resource." },
          { t: "Step 3 — Move genuine UI copy into resources", p: "Review each flag; keep non-UI strings that should stay in code." },
          { t: "Step 4 — Lengthened placeholder locale", p: "Double string length and confirm layouts do not break." },
          { t: "Step 5 — Unicode end to end", p: "Input, stored data, and rendered output — not just display text." },
          { t: "Step 6 — Locale-aware numbers and dates", p: "Formatting functions, not one region's hard-coded format." },
        ],
      },
    ],
  },
  {
    no: "77",
    title: "Baseline Testing",
    category: "Test Strategy",
    desc: "Baseline testing is the practice of running a defined, stable set of tests against a known-good build to capture a reference point — a \"baseline\" — for performance, behavior, or output, which every future run can then be measured against to detect drift or regression.",
    why: "Without a captured baseline, \"is this slower than before?\" or \"did this behavior change?\" is a question nobody can actually answer with confidence — only a vague impression. A baseline turns that impression into a concrete, documented number or output that any future comparison can be measured against objectively, which is what makes regressions in performance or behavior detectable at all, rather than something that quietly accumulates unnoticed release after release.",
    when: "Immediately after reaching any known-stable milestone (a release, a major refactor, a new environment going live) — captured deliberately and documented, then revisited specifically after any change that could plausibly affect what was baselined.",
    advantages: [
      "Turns \"does this feel slower?\" into an objective, documented comparison against a real number",
      "Cheap to set up once and reusable across many future comparisons, not a one-time cost",
      "Makes gradual, release-over-release performance creep visible, which is easy to miss when only ever comparing the current build to the last one",
      "Gives a concrete, defensible reference point to cite when discussing performance with stakeholders",
    ],
    limitations: [
      "Only as meaningful as how faithfully the comparison conditions match the original baseline conditions",
      "A baseline captured on an already-subtly-degraded build simply preserves that degradation as the new \"normal\"",
      "Doesn't identify why a regression happened, only that one did — still requires follow-up investigation",
      "Needs periodic re-baselining as the application legitimately evolves, or the comparison stops being useful",
    ],
    practical: {
      app: "HRMS Fiscal Year Setup Page",
      scenario: "Bizlevate captures a JMeter baseline of the fiscal-year-setup page's load time before starting a planned query optimization effort.",
      fail: "After the optimization work, the team has a vague sense the page \"feels about the same, maybe faster\" but no way to confirm or quantify it — and no way to tell if a later, unrelated change quietly makes it slower again.",
      failLabel: "Fail (without baseline)",
      pass: "The pre-optimization baseline shows a 2.1s average load time; the post-optimization re-run shows 0.9s under identical conditions, giving a concrete, documented confirmation that the optimization worked — and a fixed reference point to catch any future regression against.",
      passLabel: "Pass (with baseline)",
    },
    tools: [
      {
        name: "Apache JMeter",
        sub: "Baseline-capture configuration",
        url: "https://jmeter.apache.org",
        seeChapter: 14,
        desc: "The same load-testing tool already used for Load, Stress, and Soak testing, used here specifically to capture and preserve a single reference performance run under clearly documented, repeatable conditions — the technique is about what you do with the result (save it as a fixed reference) as much as the tool itself.",
        adv: [
          "Turns \"feels slower\" into a documented number",
          "Set up once, reused on every later comparison",
          "Makes release-over-release creep visible",
          "A defensible reference for stakeholder conversations",
        ],
        lim: [
          "Only meaningful if conditions match the original run",
          "A degraded baseline becomes the new normal",
          "Shows that drift happened, not why",
          "Must be re-baselined as the product legitimately evolves",
        ],
        steps: [
          { t: "Step 1 — Pick a known-stable build", p: "Fixed load, data volume, and environment to baseline against." },
          { t: "Step 2 — Run and save the full results", p: "Response times, throughput, error rate as the named reference." },
          { t: "Step 3 — Document the conditions", p: "Build version, environment, data volume, date — or it is not reproducible." },
          { t: "Step 4 — Re-run identically after a change", p: "Same plan, same conditions, whenever performance could move." },
          { t: "Step 5 — Compare, ignore noise", p: "Flag meaningful degradation, not every tiny fluctuation." },
          { t: "Step 6 — Re-baseline on purpose", p: "A known-good later build so the reference does not go stale." },
        ],
      },
    ],
  },
  {
    no: "78",
    title: "Comparative Testing",
    category: "Other",
    desc: "Comparative testing runs the same defined set of scenarios against two products side by side — most often a competitor's product, or an earlier version of your own — scoring and comparing the results consistently, to surface concrete, evidence-based gaps or advantages rather than general impressions.",
    why: "Product and roadmap decisions are often made on the basis of \"I think our competitor's onboarding flow is smoother\" — a genuine instinct, but not something a team can act on with confidence or defend to stakeholders. Comparative testing turns that instinct into a structured, repeatable comparison with specific, documented findings, which is what actually makes the difference actionable rather than just a vague, contestable impression.",
    when: "When evaluating a competitor ahead of a roadmap decision, or when validating that a new version of your own product genuinely matches or improves on the one it's replacing — run as a structured, scenario-based comparison, not an informal, unstructured look-around.",
    advantages: [
      "Converts a vague competitive impression into specific, evidence-based, defensible findings",
      "A consistent scenario list and scoring makes the comparison fair and reproducible, not dependent on who happened to look at it",
      "Directly informs prioritization and roadmap decisions with concrete gaps, not just gut feeling",
      "Reusable framework — the same scenario list can be re-run against a later version of either product to track whether a gap has closed",
    ],
    limitations: [
      "Only as fair as how carefully the comparison conditions (data, account state, environment) are matched between the two products",
      "A competitor's product can change at any time, so findings can go stale and need periodic re-verification",
      "Doesn't explain why a competitor made a particular design choice, only that a measurable difference exists",
      "Scoring inherently involves some subjectivity even with defined criteria, especially for qualitative aspects like \"clarity\"",
    ],
    practical: {
      app: "HRMS Onboarding Flow vs. Competitor",
      scenario: "Bizlevate runs the same \"hire a new employee\" scenario against its own Onboarding module and a competitor's equivalent feature.",
      fail: "The comparison shows Bizlevate's flow requires 9 screens and re-enters the employee's name twice, while the competitor's equivalent flow completes the same task in 5 screens with no repeated fields — a specific, reproducible, and actionable gap rather than a vague sense that \"theirs feels smoother.\"",
      failLabel: "Finding",
      pass: "The findings are used to justify a scoped redesign of the Onboarding flow, with the same 9-vs-5-screen scenario re-run after the redesign to confirm the gap has actually closed.",
      passLabel: "Follow-up",
    },
    tools: [
      {
        name: "Spreadsheet + LambdaTest",
        sub: "Scored scenarios, matched captures",
        url: "https://lambdatest.com",
        seeChapter: 37,
        desc: "A shared spreadsheet keeps the scenario list, scoring, and findings structured and consistent across both products being compared, while LambdaTest's free tier lets both products be captured side by side under equivalent conditions (same browser/device) so screenshots are genuinely comparable rather than confounded by different testing setups.",
        adv: [
          "Evidence-based findings instead of a contestable impression",
          "Same scenario list and scoring for a fair comparison",
          "Concrete gaps feed roadmap decisions",
          "The same list can be re-run later to see if a gap closed",
        ],
        lim: [
          "Unfair if data, account state, or environment differ",
          "Competitor products change — findings go stale",
          "Shows that a difference exists, not why they chose it",
          "Qualitative scores still have some subjectivity",
        ],
        steps: [
          { t: "Step 1 — Fix the scenario list", p: "Same tasks, same order, same input data where possible." },
          { t: "Step 2 — Capture both under matched conditions", p: "LambdaTest: same browser/device so screenshots are comparable." },
          { t: "Step 3 — Score in the shared sheet", p: "Predefined criteria, not ad-hoc impressions." },
          { t: "Step 4 — Write specific differences", p: "\"4 steps vs our 7\" — not \"theirs feels easier.\"" },
          { t: "Step 5 — Flag unfair conditions", p: "Different data volumes or account states so findings are not misread." },
          { t: "Step 6 — Summarize to reproducible scenarios", p: "Each gap or advantage ties back to a specific run." },
        ],
      },
    ],
  },
  {
    no: "79",
    title: "Domain Testing",
    category: "Design Technique",
    desc: "Domain testing is a systematic test-design technique that defines the full valid \"domain\" — the complete valid range, type, or set of allowed values — for a given input, and then deliberately tests values from inside, at the edge of, and outside that domain, combining the core ideas behind boundary value analysis (Chapter 51) and equivalence partitioning (Chapter 52) into a single, consistent approach applied field by field.",
    why: "Testing input fields without a systematic technique tends to produce test cases clustered around whatever values happen to come to mind first, leaving real gaps in coverage that only surface later, in production, when a real user enters something nobody thought to try. Domain testing forces that thinking to be explicit and complete for every field — what's the actual valid domain, and have I genuinely tested inside it, at its edges, and outside it — rather than relying on whatever test cases feel intuitive in the moment.",
    when: "During test-case design for any form or input field with a clearly definable valid range or set — applied consistently across every field on a screen, not just the ones that seem obviously risky, since gaps often hide in the fields nobody thought to scrutinize.",
    advantages: [
      "Produces systematic, complete input coverage rather than test cases clustered around intuitive guesses",
      "Combines the strengths of boundary value analysis and equivalence partitioning into one consistent, repeatable technique",
      "Documenting test cases in TestLink makes the domain coverage reusable and auditable across releases, not redesigned from scratch each time",
      "Easy to explain and apply consistently across an entire form, even by testers less familiar with the specific feature",
    ],
    limitations: [
      "Defining the \"true\" valid domain correctly requires accurate, up-to-date knowledge of the actual business rule — an incorrect domain assumption produces confidently wrong test cases",
      "Can still miss defects arising from combinations of fields, since domain testing is typically applied one field at a time",
      "Maintaining documented test cases in a separate tool (TestLink) adds process overhead compared to purely ad-hoc testing",
      "Doesn't cover non-input-related defects (UI rendering, workflow logic) — it's specifically a technique for input validation coverage",
    ],
    practical: {
      app: "HRMS Salary Input Field",
      scenario: "Bizlevate defines the salary input field's domain as any positive number up to a configured organizational maximum, and documents domain test cases in TestLink accordingly.",
      fail: "Testing only \"inside\" values (e.g. a typical mid-range salary) never exercises the field's actual maximum; a real client later enters a salary exactly at their organization's configured cap and the system silently truncates it without any error, a bug the narrower ad-hoc test cases never had a chance to catch.",
      pass: "With domain testing applied — a value inside the range, one exactly at the maximum, and one above it — the truncation bug is caught immediately at the boundary case, fixed to show a clear validation message instead, and re-verified using the same documented TestLink case set.",
      passLabel: "Pass (after fix)",
    },
    tools: [
      {
        name: "TestLink",
        sub: "Documented inside / edge / outside cases",
        url: "https://testlink.org",
        seeChapter: 51,
        desc: "A free, open-source test-case management tool that lets a domain-testing test-case set (inside/edge/outside values, per field) be documented once and reused consistently across every field and every future release, rather than redesigned from memory each time.",
        adv: [
          "Systematic coverage instead of intuitive clusters",
          "BVA and equivalence partitioning in one field-by-field pass",
          "Cases are reusable and auditable across releases",
          "Easy to apply consistently across a whole form",
        ],
        lim: [
          "A wrong domain assumption produces confidently wrong cases",
          "Field-by-field misses combination defects",
          "A separate TMS adds process overhead",
          "Does not cover UI or workflow defects",
        ],
        steps: [
          { t: "Step 1 — Name the valid domain", p: "Exact range, type, or set of values considered valid for the field." },
          { t: "Step 2 — Document inside, edge, and outside", p: "One TestLink case for each, per field." },
          { t: "Step 3 — Execute and record actual vs expected", p: "Every documented case." },
          { t: "Step 4 — Every field on the form", p: "Not only the ones that intuitively seem risky." },
          { t: "Step 5 — Reuse on later releases", p: "Confirm domain handling has not regressed." },
          { t: "Step 6 — Update when the rule changes", p: "The documented domain and its cases must match the business rule." },
        ],
      },
    ],
  },
  {
    no: "80",
    title: "Error Handling / Error Guessing Testing",
    category: "Other",
    desc: "Error guessing is an experience-driven testing technique where a tester deliberately targets the areas and actions most likely to reveal defects — based on tester intuition and pattern recognition from past bugs — rather than following a fully scripted test case, specifically probing how the application handles errors once they occur (clear messaging, no data corruption, no exposed internals).",
    why: "Scripted test cases are designed around what's supposed to happen; real users routinely do the things nobody scripted for — double-clicking submit, hitting the browser back button mid-form, leaving a session open until it times out, then continuing anyway. Error guessing is what deliberately anticipates and tests exactly those \"usual suspect\" actions before a real user stumbles into them, drawing on the pattern-recognition experienced testers build up over time about where problems tend to actually hide.",
    when: "As a deliberate supplement layered on top of scripted functional testing, especially for any feature involving state transitions, multi-step forms, or external system boundaries — applied by testers who bring genuine prior experience of where these kinds of bugs tend to live.",
    advantages: [
      "Targets exactly the \"usual suspect\" actions real users actually perform, which scripted test cases frequently don't anticipate",
      "Leverages accumulated tester experience efficiently, often finding high-value bugs with relatively little time invested",
      "Confirms error handling specifically — not just \"did the happy path work,\" but \"did the failure path fail gracefully\"",
      "Pairing with an OWASP ZAP scan catches a class of error-handling issue (verbose/leaky error responses) manual guessing alone might overlook",
    ],
    limitations: [
      "Inherently less systematic and reproducible than a scripted technique — coverage depends heavily on the specific tester's experience and instincts",
      "Findings can be harder to formally track/report against, since there's no predefined test-case list to check off",
      "Different testers will guess differently, so error-guessing coverage can vary significantly by who's doing the testing",
      "Doesn't replace systematic negative testing (Chapter 49) or boundary value analysis (Chapter 51) — it's a complementary, intuition-driven layer on top of them",
    ],
    practical: {
      app: "HRMS Leave Request Submission",
      scenario: "A tester deliberately double-clicks the Submit button on Bizlevate's leave-request form, simulating a real, common user action never explicitly scripted.",
      fail: "The double-click creates two identical leave-request records instead of one, silently doubling the days deducted from the employee's balance — a data-integrity bug invisible to any test case that only ever clicks Submit exactly once.",
      pass: "The submit action is made idempotent (a second rapid click while the first request is still processing is ignored), re-verified by repeating the same double-click action and confirming only a single leave-request record is created.",
      passLabel: "Pass (after fix)",
    },
    tools: [
      {
        name: "OWASP ZAP + guessing checklist",
        sub: "Usual suspects + leaky errors",
        url: "https://zaproxy.org",
        seeChapter: 40,
        desc: "Manual error guessing covers application-level and workflow-level error handling (double submits, back-button state, session timeouts), while running OWASP ZAP alongside it automatically probes for a specific, well-known class of error-handling failures — unhandled exceptions, verbose error messages that leak internal details — that a human guessing session might not think to specifically try.",
        adv: [
          "Hits the actions real users do that scripts skip",
          "High-value bugs for relatively little time",
          "Checks that failure paths fail gracefully",
          "ZAP catches verbose/leaky errors guessing may miss",
        ],
        lim: [
          "Coverage depends on the tester's instincts",
          "Harder to track without a predefined case list",
          "Different testers guess differently",
          "Complements, does not replace, Chapters 49 and 51",
        ],
        steps: [
          { t: "Step 1 — Usual-suspect checklist", p: "Double-submit, back mid-flow, refresh mid-submit, timeout then continue." },
          { t: "Step 2 — Perform each action", p: "Against the target feature; observe the result." },
          { t: "Step 3 — Messages must be clear, never leaky", p: "No stack traces, raw database errors, or internal file paths." },
          { t: "Step 4 — State stays consistent", p: "No duplicate records, no partial data left behind." },
          { t: "Step 5 — ZAP in parallel", p: "Review verbose error responses or unhandled exceptions." },
          { t: "Step 6 — Log exact repro steps", p: "Guessing findings are otherwise not documented anywhere." },
        ],
      },
    ],
  },
  {
    no: "81",
    title: "Statement/Branch/Path Coverage Testing",
    category: "White Box Subtype",
    desc: "Coverage testing measures, in concrete percentages, how much of the underlying source code a test suite actually exercises when it runs — statement coverage (has this line executed at all?), branch coverage (has each side of every if/else executed?), and path coverage (have all the distinct combinations of branches through a function executed?) — each a progressively stricter measure of the same underlying question.",
    why: "A test suite can pass every single test and still leave large parts of the actual code never executed at all — an entire error-handling branch, an else clause nobody wrote a test for, a rare combination of conditions nobody thought to construct. Coverage testing makes that gap visible and measurable instead of a matter of guesswork, turning \"I think we test this pretty well\" into a specific, actionable number and a specific list of exactly which lines and branches are untested.",
    when: "Continuously, as a standard part of the test suite's own reporting — reviewed especially closely for business-critical logic (calculations, approval workflows, financial code), where an untested branch represents genuine, concrete risk rather than an abstract metric.",
    advantages: [
      "Converts a vague sense of \"we probably test this reasonably well\" into a specific, objective, line-level number",
      "Directly identifies exactly which lines/branches need a new test, rather than leaving the tester to guess",
      "Both tools are free, well-established, and integrate directly into standard JS/Python test workflows",
      "Branch coverage specifically catches the common and risky gap of an entirely untested else/error-handling path",
    ],
    limitations: [
      "A high coverage percentage confirms code was executed, not that it was correctly verified — a test can execute a line without meaningfully asserting on its result",
      "Chasing 100% coverage as a goal in itself can produce low-value tests written purely to hit an uncovered line, not to verify real behavior",
      "Path coverage in particular can grow combinatorially explosive for functions with many conditions, making full path coverage impractical for complex logic",
      "Coverage tooling measures code that ran, not code that's missing entirely — it can't reveal a scenario nobody wrote any code path for",
    ],
    practical: {
      app: "HRMS Leave Approval Logic",
      scenario: "Coverage.py reveals the leave-approval function's else branch — handling a manager who has since left the company — has zero coverage.",
      fail: "The existing test suite passes at 100% green, but the never-executed branch contains a bug: when the assigned approving manager has been deactivated, the function throws an unhandled exception instead of routing to a fallback approver — invisible until a real employee's leave request genuinely hits that exact scenario in production.",
      pass: "A test case is added specifically exercising the deactivated-manager branch, the fallback-approver logic is corrected, and the coverage report confirms the previously-red branch is now green and correctly verified.",
      passLabel: "Pass (after fix)",
    },
    tools: [
      {
        name: "Istanbul (nyc)",
        sub: "JavaScript coverage",
        url: "https://istanbul.js.org",
        seeChapter: 26,
        desc: "A free, open-source JavaScript code-coverage tool — typically run via its nyc command-line wrapper, or built directly into a test runner like Jest — that instruments code during a test run and produces a detailed report of exactly which statements, branches, and lines were and weren't executed.",
        adv: [
          "Line-level number instead of a vague sense of coverage",
          "Shows exactly which branches still need a test",
          "Free and built into Jest via --coverage",
          "Branch coverage catches untested else/error paths",
        ],
        lim: [
          "Executed is not the same as correctly asserted",
          "Chasing 100% produces low-value tests",
          "Full path coverage explodes combinatorially",
          "Cannot reveal a scenario nobody wrote a path for",
        ],
        steps: [
          {
            t: "Step 1 — Run the suite through Istanbul",
            p: "nyc <test command> or jest --coverage.",
            c: `npx jest --coverage`,
          },
          { t: "Step 2 — Open the HTML report", p: "Clearest, most navigable view of what ran." },
          { t: "Step 3 — Hunt red, not just the percentage", p: "Uncovered lines and branches." },
          { t: "Step 4 — Write a test for each uncovered branch", p: "The else clause, the error-handling block — that exact path." },
          { t: "Step 5 — Re-run to confirm green", p: "Previously-red lines should now be covered." },
          { t: "Step 6 — Track the percentage as a trend", p: "Not a single point-in-time snapshot." },
        ],
      },
      {
        name: "Coverage.py",
        sub: "Python coverage",
        url: "https://coverage.readthedocs.io",
        seeChapter: 26,
        desc: "The equivalent free, well-established coverage tool for Python — instruments code during a pytest (or other test runner) execution and produces both a terminal summary and a detailed, navigable HTML report of exactly what was and wasn't exercised.",
        adv: [
          "Terminal summary plus navigable HTML",
          "Prioritize business-critical uncovered branches first",
          "--branch measures more than statement coverage",
          "Free and standard in Python test workflows",
        ],
        lim: [
          "Executed is not verified",
          "100% as a goal produces noise tests",
          "Full path coverage is often impractical",
          "Missing code paths stay invisible",
        ],
        steps: [
          {
            t: "Step 1 — Instrument the run",
            p: "coverage run -m pytest",
            c: `coverage run -m pytest\ncoverage report\ncoverage html --branch`,
          },
          { t: "Step 2 — Terminal or HTML", p: "coverage report for a summary; coverage html for a browsable view." },
          { t: "Step 3 — Module by module, red lines first", p: "Especially in calculations and financial code." },
          { t: "Step 4 — Prefer --branch", p: "Statement coverage alone can hide an untested else." },
          { t: "Step 5 — Add tests, re-check the report", p: "Confirm the gap actually closed." },
        ],
      },
    ],
  },
  {
    no: "82",
    title: "Operational Acceptance Testing (OAT)",
    category: "By Level (UAT Subtype)",
    desc: "Operational Acceptance Testing is a specialized subtype of acceptance testing (Chapter 4) focused not on whether business features work, but on whether the operations team can actually run, monitor, back up, restore, and maintain the system in production — the readiness check performed from the operations side of go-live, rather than the business/user side.",
    why: "A system can pass full business-feature UAT with flying colors and still be genuinely unready for production if nobody has verified that backups actually restore correctly, that monitoring alerts actually fire when something breaks, or that a routine deploy can be performed without an outage. OAT exists specifically to close that gap — verifying the unglamorous, easy-to-overlook operational plumbing that determines whether a technically-working system can actually be safely and sustainably run in the real world.",
    when: "As a required gate immediately before go-live, and again after any significant infrastructure or deployment-process change — run by, or in close collaboration with, the actual operations team who will be responsible for supporting the system afterward.",
    advantages: [
      "Confirms the system can actually be operated and supported, not just that its business features work",
      "Catches operational gaps (a backup that silently doesn't work, an alert that's misconfigured) while the stakes are still low, before a real incident",
      "Deliberately triggering failures to test alerting is a meaningfully stronger check than passively assuming a dashboard means monitoring works",
      "Directly reduces the risk of a production incident being made worse by operational unreadiness on top of the original problem",
    ],
    limitations: [
      "Requires genuine collaboration with the operations team, who may have limited availability during a busy pre-launch period",
      "Some operational scenarios (a full regional outage, a genuine hardware failure) are hard to simulate faithfully in a lower environment",
      "A runbook that works when followed by its author may still fail when followed by someone else seeing it for the first time — worth deliberately testing with a different person",
      "Doesn't cover business-feature correctness at all — it specifically complements, and doesn't replace, standard UAT (Chapter 4)",
    ],
    practical: {
      app: "HRMS Production Backup & Restore",
      scenario: "Ahead of a Bizlevate client go-live, the operations team performs a full documented backup-and-restore drill against a staging copy of the production environment.",
      fail: "The documented backup procedure runs successfully every night without error, but attempting an actual restore reveals the backup files have been silently incomplete for weeks — a critical gap that would only have been discovered during a real data-loss incident, when it would have been far too late.",
      pass: "The backup process is corrected and re-verified with a full end-to-end restore drill, confirming the recovered data is genuinely complete and correct, and the operations team now has direct, first-hand confidence in the restore procedure rather than an untested assumption.",
      passLabel: "Pass (after fix)",
    },
    tools: [
      {
        name: "UptimeRobot",
        sub: "Prove the alert actually fires",
        url: "https://uptimerobot.com",
        seeChapter: 42,
        desc: "Manually reviewing a monitoring dashboard confirms it exists; UptimeRobot lets the team actually verify that an alert fires correctly by deliberately triggering a monitored condition and confirming the notification genuinely arrives — a meaningfully stronger check than assuming a configured alert works.",
        adv: [
          "Operability, not just business-feature UAT",
          "Finds silent backup and alert gaps before an incident",
          "Triggering failure is stronger than assuming a dashboard works",
          "Reduces the chance an incident is made worse by unreadiness",
        ],
        lim: [
          "Needs real ops collaboration under launch pressure",
          "Regional/hardware failures are hard to simulate faithfully",
          "A runbook must work for someone who did not write it",
          "Does not replace Chapter 4 UAT",
        ],
        steps: [
          { t: "Step 1 — Document the runbook", p: "Backup, restore, monitoring/alerting, routine maintenance and deploy." },
          { t: "Step 2 — Configure monitors as for real ops", p: "UptimeRobot against the key production endpoints." },
          { t: "Step 3 — Trigger a failure on purpose", p: "Stop the service in staging; confirm the notification actually arrives." },
          { t: "Step 4 — Create a real backup", p: "Walk the documented procedure; confirm a backup file exists." },
          { t: "Step 5 — Restore from that backup", p: "Data is genuinely and correctly restored, not just that a file exists." },
          { t: "Step 6 — Fresh eyes on the runbook", p: "Ops performs a deploy or config change using only the documented steps." },
        ],
      },
    ],
  },
  {
    no: "83",
    title: "Cloud Testing",
    category: "Non-Functional",
    desc: "Cloud testing verifies an application's performance, scalability, and functional correctness specifically in a cloud-hosted environment — checking behaviors unique to the cloud itself, like auto-scaling under load, resilience across multiple regions or availability zones, and recovery from cloud-specific failure events, rather than testing generic application logic that happens to run on cloud infrastructure.",
    why: "Cloud infrastructure's core promise — elastic scaling, redundancy across zones — only actually delivers real value if the application is genuinely built and verified to take advantage of it; an application that silently assumes a single fixed server will behave badly the moment it's auto-scaled across multiple instances (inconsistent session state, race conditions between instances) or a zone genuinely fails. Cloud testing is what specifically verifies the application handles these cloud-native realities correctly, rather than merely running on cloud infrastructure without actually being cloud-resilient.",
    when: "After migrating to, or building specifically for, cloud infrastructure — tested deliberately under conditions that exercise auto-scaling and multi-zone behavior, which won't be naturally exercised by standard functional or single-instance load testing.",
    advantages: [
      "Verifies the application actually benefits from, and correctly handles, the elasticity cloud infrastructure is specifically built to provide",
      "Free tier is genuinely capable of generating load sufficient to trigger real auto-scaling behavior, unlike many local-only load tools",
      "Specifically tests cloud-native failure modes (instance restart, zone outage) that a standard single-server load test would never naturally exercise",
      "Multi-region test locations reveal genuine consistency issues across zones that a single-location test would miss entirely",
    ],
    limitations: [
      "Generating load sufficient to trigger real auto-scaling can incur real cloud infrastructure costs on the environment under test, separate from BlazeMeter's own pricing",
      "Free tier load/duration limits may fall short of what's needed to fully exercise scaling behavior for a large-scale application",
      "Cloud-provider-specific auto-scaling configuration and behavior varies significantly, so findings don't always transfer cleanly between different cloud platforms",
      "Deliberately simulating a genuine zone-level failure isn't always possible or safe to do against a real production environment",
    ],
    practical: {
      app: "HRMS Roles & Permissions Under Auto-Scaling",
      scenario: "Bizlevate's Roles & Permissions module is load-tested with BlazeMeter at a level sufficient to trigger the environment's auto-scaling from one instance to three.",
      fail: "Once traffic is distributed across the newly-scaled instances, some requests intermittently return stale permission data — the module was caching permissions in each instance's local memory rather than a shared cache, so different instances briefly disagree with each other during the scaling transition.",
      pass: "Permission data is moved to a shared, centralized cache accessible by every instance; re-running the same auto-scaling load test confirms permission data now stays consistent across all instances throughout the scaling event.",
      passLabel: "Pass (after fix)",
    },
    tools: [
      {
        name: "BlazeMeter",
        sub: "Cloud-scale load, multi-region",
        url: "https://blazemeter.com",
        seeChapter: 14,
        desc: "A free-tier-available, JMeter-compatible load-testing platform built specifically for cloud-scale testing — able to generate load sufficient to actually trigger real auto-scaling behavior and to distribute test traffic across multiple geographic locations, closer to how real global cloud traffic actually arrives.",
        adv: [
          "Exercises elasticity, not just single-instance capacity",
          "Free tier can trigger real auto-scaling",
          "Cloud-native failures a local load test never hits",
          "Multi-region locations find cross-zone inconsistency",
        ],
        lim: [
          "The environment under test can incur real cloud cost",
          "Free-tier limits may be too small for large-scale apps",
          "Findings do not always transfer across cloud vendors",
          "True zone failure is not always safe to simulate in prod",
        ],
        steps: [
          { t: "Step 1 — Target the cloud-hosted environment", p: "BlazeMeter builder or an imported JMeter plan." },
          { t: "Step 2 — Ramp past the auto-scale threshold", p: "Not just a single instance's comfortable capacity." },
          { t: "Step 3 — Watch the scaling event itself", p: "Session or data inconsistency as new instances join." },
          { t: "Step 4 — Multi-region if the app spans zones", p: "Compare consistency of results across test locations." },
          { t: "Step 5 — Simulate instance/zone failure where safe", p: "App continues via remaining healthy capacity." },
          { t: "Step 6 — Read the scaling transition, not only steady state", p: "Response time and error rate during the change." },
        ],
      },
    ],
  },
  {
    no: "84",
    title: "Diff / Golden Master Testing",
    category: "Automation Technique",
    desc: "Golden master testing (also called characterization testing) captures a known-good, trusted output — the \"golden master\" — for a given set of inputs, then automatically diffs all future output against that saved reference, flagging any difference for review, without requiring the tester to actually understand or hand-write individual assertions about why that output is correct.",
    why: "Legacy code with little or no existing test coverage is often too risky to refactor confidently, precisely because nobody fully understands every rule buried inside it well enough to write correct assertions from scratch — but a golden master doesn't require that understanding at all; it only requires that the current output be trusted as correct, which can then act as a safety net protecting against any unintended change during refactoring, even without fully understanding every rule that produced it.",
    when: "Specifically before refactoring legacy or poorly-understood code that lacks adequate existing test coverage — as a protective safety net during the refactor itself, not as a long-term substitute for genuine, understood test coverage once the refactor is complete.",
    advantages: [
      "Protects legacy code during a refactor without requiring the refactoring team to first fully reverse-engineer every business rule inside it",
      "Very low setup cost — no need to write assertions from scratch, only to capture and trust the existing output",
      "The plain-text diff tools required are free and already present on virtually every development machine",
      "Provides genuine, concrete confidence during a refactor that would otherwise be an unverified leap of faith",
    ],
    limitations: [
      "Only as trustworthy as the assumption that the original captured output was actually correct — a golden master captured from already-buggy output simply preserves that bug",
      "A flagged diff shows that something changed, not why, or whether the change is actually correct — still requires human judgment every time",
      "Doesn't explain or document the underlying business rules at all — it's a safety net for refactoring, not a substitute for genuinely understanding and testing the logic",
      "Large or highly complex outputs can produce diffs that are tedious and error-prone for a human to meaningfully review in full",
    ],
    practical: {
      app: "HRMS Legacy Tax Calculation Engine",
      scenario: "Before refactoring Bizlevate's old, sparsely-documented tax-calculation engine, the team captures its current output as a golden master across a representative range of salary inputs.",
      fail: "After the refactor, running the same inputs and diffing against the golden master reveals the new code produces a different result for salaries exactly at a tax-bracket boundary — an accidental regression in boundary-handling logic introduced during the refactor, which nobody on the team fully understood well enough to have written a targeted assertion for in advance.",
      failLabel: "Fail (caught)",
      pass: "The boundary-handling bug is corrected in the refactored code; re-running the same representative inputs and diffing against the golden master shows zero differences, confirming the refactor preserved the exact original behavior.",
      passLabel: "Pass (after fix)",
    },
    tools: [
      {
        name: "script diff",
        sub: "diff / git diff",
        url: null,
        desc: "The command-line comparison tools already present on virtually every development machine — free, universal, and sufficient for text-based output without needing any specialized tooling. For a small number of outputs, comparing current output against the saved reference by eye remains a valid, zero-setup starting point.",
        adv: [
          "No reverse-engineering every buried rule first",
          "Capture trusted output — no assertions from scratch",
          "diff and git diff are already on the machine",
          "Concrete confidence during an otherwise unverified refactor",
        ],
        lim: [
          "A buggy original becomes a preserved bug",
          "A diff shows that, not why or whether it is correct",
          "Not a substitute for understanding the logic",
          "Large outputs are hard for a human to review in full",
        ],
        steps: [
          { t: "Step 1 — Save trusted output", p: "Representative inputs → reference golden master file." },
          {
            t: "Step 2 — After a change, save new output",
            p: "Same inputs, separate file.",
            c: `diff old_output.txt new_output.txt`,
          },
          { t: "Step 3 — Diff line by line", p: "diff or git diff if both files are tracked." },
          { t: "Step 4 — Classify each difference", p: "Intentional consequence, or accidental regression?" },
          { t: "Step 5 — If intentional, update the master", p: "New output becomes the reference going forward." },
          { t: "Step 6 — If unintentional, fix the code", p: "Do not patch the reference file to hide a refactor bug." },
        ],
      },
    ],
  },
  {
    no: "85",
    title: "Content Testing",
    category: "Other",
    desc: "Content testing reviews the actual text, labels, and messaging displayed throughout an application — accuracy, clarity, tone, and above all consistency of terminology — checking the words themselves as a distinct concern from whether the underlying feature functionally works correctly.",
    why: "A feature can be functionally flawless and still confuse or frustrate users through its content alone — an unclear label, a typo that undermines trust, or the same underlying concept called two different things in two different places (\"Leave Balance\" on one screen, \"Leave Credit\" on another), leaving a user genuinely unsure whether they're looking at the same thing or something different. Content testing is what deliberately catches these issues, which functional and even usability testing can easily pass right over if the reviewer is focused on behavior rather than the words themselves.",
    when: "Across every screen as part of standard review, and specifically whenever new copy is introduced or an existing screen is reworked — checked against a consistent internal terminology/style reference, not left to each screen's author to phrase independently.",
    advantages: [
      "Catches typos, unclear labels, and confusing wording that hurt usability and undermine user trust",
      "Ensures the same concept is referred to consistently everywhere in the product, reducing user confusion",
      "Automated linting with Vale finds terminology drift across many screens far more completely than manual review alone can",
      "Cheap, high-visibility improvement — content fixes are typically low-risk and low-effort relative to their impact on perceived quality",
    ],
    limitations: [
      "Vale checks consistency and defined style rules, not genuine clarity or correctness — a human review is still needed for that",
      "Requires an actively maintained style/terminology guide to be useful; a stale or incomplete guide limits what it can catch",
      "Doesn't cover translated content in other locales — that's the separate concern of localization testing (Chapter 23)",
      "Reviewing dynamic/templated text for every real-data edge case (pluralization, unusual name lengths) can be easy to under-scope",
    ],
    practical: {
      app: "HRMS Leave Terminology Inconsistency",
      scenario: "Vale, configured with Bizlevate's internal terminology guide, is run against the application's content files.",
      fail: "The scan flags \"Leave Credit\" appearing on the employee dashboard while every other screen consistently uses \"Leave Balance\" for the identical concept — a small inconsistency, but one that had already generated confused support tickets from employees genuinely unsure if the two labels meant different things.",
      pass: "The dashboard label is corrected to \"Leave Balance\" to match the rest of the application; re-running Vale against the updated content confirms no remaining terminology inconsistencies for this term.",
      passLabel: "Pass (after fix)",
    },
    tools: [
      {
        name: "Vale",
        sub: "Prose linter + custom style",
        url: "https://vale.sh",
        desc: "A free, open-source prose linter that can be configured with a custom style guide (approved terminology, banned phrases, tone rules) and then automatically scan written content against it — catching terminology drift across many screens far more reliably and completely than manual review alone.",
        adv: [
          "Catches typos and confusing labels functional tests skip",
          "Same concept, same term, everywhere",
          "Finds drift across dozens of screens",
          "Low-risk, high-visibility fixes",
        ],
        lim: [
          "Consistency is not the same as clarity",
          "A stale style guide limits what it can catch",
          "Does not cover translated locales (Chapter 23)",
          "Dynamic/templated edge cases are easy to under-scope",
        ],
        steps: [
          { t: "Step 1 — Write the terminology guide", p: "Approved term per concept — always \"Leave Balance,\" never \"Leave Credit.\"" },
          { t: "Step 2 — Configure Vale as a custom style", p: "So it can check content automatically against approved terms." },
          { t: "Step 3 — Scan copy files", p: "Or exported screen text — flag inconsistent and banned phrases." },
          { t: "Step 4 — Human review for clarity", p: "Vale checks consistency; a person checks whether wording is actually clear." },
          { t: "Step 5 — Dynamic/templated text with real data", p: "Pluralization that breaks for exactly one item, unusual name lengths." },
          { t: "Step 6 — Re-run when copy changes", p: "Same review process as the functional change itself." },
        ],
      },
    ],
  },
  {
    no: "86",
    title: "Cookie / Session Testing",
    category: "Non-Functional",
    desc: "Cookie and session testing verifies that an application creates, stores, expires, and secures cookies and session data correctly — checking session-related security flags, timeout behavior, and consistency across tabs/devices for the same logged-in user, an area with both functional and genuine security implications.",
    why: "Session handling sits directly at the intersection of usability and security — a session that expires too aggressively frustrates legitimate users, one that never expires or is missing basic security flags creates a genuine attack surface, and inconsistent behavior across multiple open tabs or devices for the same user can produce confusing, hard-to-reproduce bugs. Cookie/session testing is what deliberately verifies this specific, easy-to-overlook layer is both usable and secure, rather than left as an unverified assumption sitting underneath every other feature in the application.",
    when: "Whenever authentication or session-handling logic is built or changed — checked specifically, since session bugs are often invisible during normal single-tab, single-session functional testing and only surface under multi-tab or extended-duration conditions.",
    advantages: [
      "Confirms session tokens are handled with appropriate security flags, directly reducing a real attack surface",
      "Free and built directly into the browser — no extra tooling or setup required",
      "Catches session-timeout and multi-tab consistency bugs that standard single-session functional testing naturally misses",
      "Manually tampering with the cookie is a cheap, immediate way to verify graceful handling of an invalid/expired session",
    ],
    limitations: [
      "DevTools inspection is inherently manual, tab-by-tab — not easily automated at scale without additional scripting",
      "Verifying long-timeout behavior (e.g. an 8-hour session expiry) realistically can require genuinely waiting, or manually manipulating the system clock/cookie",
      "Doesn't cover server-side session storage/validation logic directly — only what's observable from the client side",
      "Security flag correctness (Secure, HttpOnly) is necessary but not sufficient on its own for full session security; it's one check among several",
    ],
    practical: {
      app: "HRMS Admin Session Timeout",
      scenario: "An admin's Bizlevate session is inspected in Chrome DevTools after logging in, and the configured 30-minute idle timeout is tested directly.",
      fail: "The session cookie is missing the Secure flag entirely, meaning it could theoretically be transmitted over an unencrypted connection, and manually waiting past the configured 30-minute timeout shows the admin dashboard remains fully interactive with no re-authentication prompt at all — the timeout is configured but never actually enforced.",
      pass: "The Secure flag is added to the session cookie and the timeout is correctly wired to force re-authentication after 30 minutes of inactivity; re-testing both in DevTools confirms the flag is present and the timeout is now genuinely enforced.",
      passLabel: "Pass (after fix)",
    },
    tools: [
      {
        name: "Chrome DevTools",
        sub: "Application → Cookies",
        url: "https://developer.chrome.com/docs/devtools",
        seeChapter: 18,
        desc: "Built directly into Chrome at no cost — the Application panel gives direct visibility into every cookie the application sets, including its security-relevant flags, letting session behavior be inspected and verified with no additional tooling required.",
        adv: [
          "Security flags on the session token, for free",
          "No extra tooling — already in the browser",
          "Catches timeout and multi-tab bugs single-tab tests miss",
          "Tampering with the cookie checks invalid-session handling",
        ],
        lim: [
          "Manual, tab-by-tab — not easy at scale",
          "Long timeouts may need clock/cookie manipulation",
          "Client-side only — not server session storage",
          "Secure/HttpOnly is necessary, not sufficient",
        ],
        steps: [
          { t: "Step 1 — Application panel → Cookies", p: "For the target site, after login." },
          { t: "Step 2 — Inspect security flags", p: "Secure and HttpOnly set as expected for a session token." },
          { t: "Step 3 — Check expiry vs intended timeout", p: "Cookie expiry matches the designed session duration." },
          { t: "Step 4 — Second tab, same user", p: "Session consistent — or the intended \"log out everywhere\" behavior." },
          { t: "Step 5 — Wait or simulate timeout", p: "Logout or re-auth prompt; not a silent failure." },
          { t: "Step 6 — Delete or edit the cookie", p: "Invalid session handled gracefully, not an unexpected error." },
        ],
      },
    ],
  },
  {
    no: "87",
    title: "Object-Oriented Testing",
    category: "White Box Subtype",
    desc: "Object-oriented testing focuses specifically on the constructs unique to object-oriented design — class methods, inheritance hierarchies, polymorphism, and object state across its lifecycle — verifying these OO-specific behaviors directly, in a way that generic functional testing, which typically only exercises a class through its outward-facing behavior, can easily miss.",
    why: "Generic functional or unit testing can pass while a subtle OO-specific defect lurks underneath — a subclass that overrides a method in a way that silently breaks the parent class's expected contract, an object whose internal state becomes inconsistent partway through its lifecycle in a way no single method call reveals in isolation. Object-oriented testing is what deliberately targets these OO-specific risk areas directly, rather than relying on generic tests that happen to exercise a class without specifically probing its inheritance and state-management behavior.",
    when: "For codebases built around meaningful class hierarchies and shared base classes — particularly wherever a subclass overrides base-class behavior, since that's specifically where the risk of silently breaking the base class's intended contract concentrates.",
    advantages: [
      "Catches OO-specific defects — broken inheritance contracts, incorrect polymorphic dispatch — that generic functional testing routinely misses",
      "Improves confidence specifically in shared, reusable base classes, where a defect can silently propagate to every subclass built on top of them",
      "Complements standard unit testing by adding an OO-specific lens rather than duplicating the same generic checks",
      "Structured code review catches design-level OO risk patterns before they even manifest as a runtime bug",
    ],
    limitations: [
      "Requires genuine familiarity with object-oriented design principles to review or test effectively — not a technique every tester is equally equipped for",
      "Manual-only testing here means it's not automatically re-verified on every future change without separately maintained test cases",
      "Deep inheritance hierarchies can make it genuinely difficult to reason about every possible interaction and override combination",
      "Doesn't cover procedural or non-OO parts of a codebase at all — it's specifically scoped to OO-structured code",
    ],
    practical: {
      app: "HRMS Payroll Rule Subclass",
      scenario: "A custom OvertimePayrollRule subclass overriding the base PayrollRule class's calculation method is reviewed and tested in Bizlevate.",
      fail: "The overridden method in the subclass silently skips the base class's mandatory minimum-wage floor check — a check every other payroll rule subclass correctly inherits and applies — meaning overtime pay could theoretically be calculated below the legal minimum for a specific edge-case scenario, a defect invisible to any test that only exercised the base class or the more commonly-used subclasses.",
      pass: "The overridden method is corrected to call the base class's minimum-wage check before applying its own overtime-specific logic, re-verified by testing the subclass directly with an input specifically chosen to trigger the minimum-wage floor.",
      passLabel: "Pass (after fix)",
    },
    tools: [
      {
        name: "Manual / code review",
        sub: "OO contract and lifecycle",
        url: null,
        seeChapter: 1,
        desc: "Directly exercising a class's public methods and state transitions with varied inputs — the same fundamental technique as unit testing but specifically directed at OO-specific concerns — plus a structured review of class design focused on inheritance contracts, deep hierarchies, and how object state is mutated.",
        adv: [
          "Finds broken inheritance contracts generic tests miss",
          "Protects shared base classes that every subclass inherits",
          "Adds an OO lens on top of unit tests",
          "Review catches design risk before it is a runtime bug",
        ],
        lim: [
          "Needs real OO design familiarity",
          "Not re-run automatically unless cases are kept",
          "Deep hierarchies are hard to reason about fully",
          "Does not cover non-OO code",
        ],
        steps: [
          { t: "Step 1 — Public methods and lifecycle states", p: "Creation, mutation, destruction/cleanup for each class." },
          { t: "Step 2 — Test overrides against the parent contract", p: "Subclass methods still honor what the base class promises." },
          { t: "Step 3 — Sequence state transitions", p: "Not only isolated method calls — defects that appear across a lifecycle." },
          { t: "Step 4 — Polymorphic dispatch", p: "Call through a base-class reference whose actual type is the subclass." },
          { t: "Step 5 — Review deep chains and complexity", p: "Known risk signals for OO-specific defects." },
          { t: "Step 6 — State only via well-defined methods", p: "Not mutated from multiple uncoordinated places; overrides specialize, they do not change meaning." },
        ],
      },
    ],
  },
  {
    no: "88",
    title: "Progressive Web App (PWA) Testing",
    category: "Mobile/Web Subtype",
    desc: "PWA testing verifies the specific capabilities that distinguish a Progressive Web App from an ordinary website — offline functionality via a service worker, installability to a device's home screen, and overall responsiveness and reliability — checking that the app genuinely delivers on the native-app-like experience a PWA is specifically built to promise.",
    why: "A web application can be technically configured as a PWA (the right manifest file, a registered service worker) while still failing to actually deliver the experience that configuration promises — an \"offline\" mode that shows a blank error screen the moment connectivity drops, an install prompt that never appears or leads to a broken shortcut. PWA testing is what specifically verifies the promised capabilities genuinely work in practice, since a PWA that merely looks configured correctly but doesn't function as one offers no real advantage over an ordinary website.",
    when: "After implementing or updating PWA-specific functionality (service worker caching logic, the web app manifest, offline handling) — tested deliberately under real offline and install conditions, not merely inferred from the presence of the correct configuration files.",
    advantages: [
      "Directly verifies the app delivers the native-app-like experience a PWA is specifically supposed to provide, not just that it's technically configured as one",
      "Free, built directly into Chrome, and requires no additional setup or tooling",
      "Gives a specific, scored, actionable checklist rather than a vague pass/fail impression",
      "Manually testing offline mode and the install flow catches gaps a passing Lighthouse score alone can miss, since the audit checks configuration more than lived experience",
    ],
    limitations: [
      "A high Lighthouse score confirms the PWA criteria are technically met, but doesn't guarantee the offline experience is actually well-designed or usable, only that it exists",
      "Manually testing the install flow requires a real mobile device (or realistic emulation) for a fully trustworthy result",
      "Service worker caching logic can be genuinely tricky to get right, and Lighthouse won't catch every subtle caching bug (stale content served incorrectly, for instance)",
      "Offline testing only covers the specific offline scenario tested — a partially degraded connection can behave differently from a fully offline one",
    ],
    practical: {
      app: "HRMS Mobile Attendance Check-In (Offline)",
      scenario: "Bizlevate's mobile web app is tested with the network set to Offline in Chrome DevTools while attempting to view the employee's schedule.",
      fail: "With the network disabled, the schedule screen shows a generic browser \"no internet connection\" error page instead of the app's own interface — the service worker was registered and passed Lighthouse's automated audit, but its caching logic didn't actually include the schedule data needed to render anything meaningful offline.",
      pass: "The service worker is updated to cache the employee's most recently loaded schedule data specifically for offline access; re-testing with the network disabled now shows the last-synced schedule with a clear \"offline — showing last synced data\" indicator, instead of a broken error page.",
      passLabel: "Pass (after fix)",
    },
    tools: [
      {
        name: "Lighthouse",
        sub: "PWA audit in Chrome DevTools",
        url: "https://developer.chrome.com/docs/lighthouse",
        seeChapter: 41,
        desc: "A free, automated auditing tool built directly into Chrome DevTools — runs a structured audit specifically against recognized PWA criteria (manifest correctness, service worker presence, offline behavior, installability) and returns a scored checklist of exactly what's met and what's missing.",
        adv: [
          "Verifies the promised PWA experience, not just config files",
          "Free, built into Chrome, no extra setup",
          "Scored, actionable checklist",
          "Manual offline and install checks catch gaps the score misses",
        ],
        lim: [
          "A high score is not a well-designed offline UX",
          "Install flow needs a real device (or solid emulation)",
          "Subtle stale-cache bugs slip past Lighthouse",
          "Fully offline ≠ a flaky partial connection",
        ],
        steps: [
          { t: "Step 1 — Lighthouse tab, PWA category", p: "Run the audit in Chrome DevTools." },
          { t: "Step 2 — Work the scored checklist", p: "Address every flagged criterion the app fails." },
          { t: "Step 3 — Network → Offline", p: "App still functions or degrades gracefully — not a blank error page." },
          { t: "Step 4 — Add to Home Screen on a real device", p: "Prompt appears, installs, and launches from the icon." },
          { t: "Step 5 — Mobile network conditions", p: "PWAs are often used on variable connectivity, not only fast desktop." },
          { t: "Step 6 — Re-audit after SW or manifest changes", p: "Confirm the PWA score has not regressed." },
        ],
      },
    ],
  },
];
