// ⚙️ AUTO-GENERATED by scripts/generate-chapter-index.mjs — do not edit by hand
import type { ChapterRecord } from "../../types";

import { chapter as part_1_chapter_1 } from "./part-1/chapter-1";
import { chapter as part_1_chapter_2 } from "./part-1/chapter-2";
import { chapter as part_1_chapter_3 } from "./part-1/chapter-3";
import { chapter as part_1_chapter_4 } from "./part-1/chapter-4";
import { chapter as part_2_chapter_1 } from "./part-2/chapter-1";
import { chapter as part_2_chapter_2 } from "./part-2/chapter-2";
import { chapter as part_2_chapter_3 } from "./part-2/chapter-3";
import { chapter as part_2_chapter_4 } from "./part-2/chapter-4";
import { chapter as part_3_chapter_1 } from "./part-3/chapter-1";
import { chapter as part_3_chapter_2 } from "./part-3/chapter-2";
import { chapter as part_3_chapter_3 } from "./part-3/chapter-3";
import { chapter as part_3_chapter_4 } from "./part-3/chapter-4";
import { chapter as part_4_chapter_1 } from "./part-4/chapter-1";
import { chapter as part_4_chapter_2 } from "./part-4/chapter-2";
import { chapter as part_4_chapter_3 } from "./part-4/chapter-3";
import { chapter as part_4_chapter_4 } from "./part-4/chapter-4";
import { chapter as part_5_chapter_1 } from "./part-5/chapter-1";
import { chapter as part_5_chapter_2 } from "./part-5/chapter-2";
import { chapter as part_5_chapter_3 } from "./part-5/chapter-3";
import { chapter as part_5_chapter_4 } from "./part-5/chapter-4";
import { chapter as part_6_chapter_1 } from "./part-6/chapter-1";
import { chapter as part_6_chapter_2 } from "./part-6/chapter-2";
import { chapter as part_6_chapter_3 } from "./part-6/chapter-3";
import { chapter as part_6_chapter_4 } from "./part-6/chapter-4";
import { chapter as part_7_chapter_1 } from "./part-7/chapter-1";
import { chapter as part_7_chapter_2 } from "./part-7/chapter-2";
import { chapter as part_7_chapter_3 } from "./part-7/chapter-3";
import { chapter as part_7_chapter_4 } from "./part-7/chapter-4";
import { chapter as part_8_chapter_1 } from "./part-8/chapter-1";
import { chapter as part_8_chapter_2 } from "./part-8/chapter-2";
import { chapter as part_8_chapter_3 } from "./part-8/chapter-3";
import { chapter as part_8_chapter_4 } from "./part-8/chapter-4";
import { chapter as part_9_chapter_1 } from "./part-9/chapter-1";
import { chapter as part_9_chapter_2 } from "./part-9/chapter-2";
import { chapter as part_9_chapter_3 } from "./part-9/chapter-3";
import { chapter as part_9_chapter_4 } from "./part-9/chapter-4";
import { chapter as part_10_chapter_1 } from "./part-10/chapter-1";
import { chapter as part_10_chapter_2 } from "./part-10/chapter-2";
import { chapter as part_10_chapter_3 } from "./part-10/chapter-3";
import { chapter as part_10_chapter_4 } from "./part-10/chapter-4";
import { chapter as part_11_chapter_1 } from "./part-11/chapter-1";
import { chapter as part_11_chapter_2 } from "./part-11/chapter-2";
import { chapter as part_11_chapter_3 } from "./part-11/chapter-3";
import { chapter as part_11_chapter_4 } from "./part-11/chapter-4";
import { chapter as part_12_chapter_1 } from "./part-12/chapter-1";
import { chapter as part_12_chapter_2 } from "./part-12/chapter-2";
import { chapter as part_12_chapter_3 } from "./part-12/chapter-3";
import { chapter as part_12_chapter_4 } from "./part-12/chapter-4";
import { chapter as part_13_chapter_1 } from "./part-13/chapter-1";
import { chapter as part_13_chapter_2 } from "./part-13/chapter-2";
import { chapter as part_13_chapter_3 } from "./part-13/chapter-3";
import { chapter as part_13_chapter_4 } from "./part-13/chapter-4";
import { chapter as part_14_chapter_1 } from "./part-14/chapter-1";
import { chapter as part_14_chapter_2 } from "./part-14/chapter-2";
import { chapter as part_14_chapter_3 } from "./part-14/chapter-3";
import { chapter as part_14_chapter_4 } from "./part-14/chapter-4";
import { chapter as part_15_chapter_1 } from "./part-15/chapter-1";
import { chapter as part_15_chapter_2 } from "./part-15/chapter-2";
import { chapter as part_15_chapter_3 } from "./part-15/chapter-3";
import { chapter as part_15_chapter_4 } from "./part-15/chapter-4";
import { chapter as part_16_chapter_1 } from "./part-16/chapter-1";
import { chapter as part_16_chapter_2 } from "./part-16/chapter-2";
import { chapter as part_16_chapter_3 } from "./part-16/chapter-3";
import { chapter as part_16_chapter_4 } from "./part-16/chapter-4";
import { chapter as part_17_chapter_1 } from "./part-17/chapter-1";
import { chapter as part_17_chapter_2 } from "./part-17/chapter-2";
import { chapter as part_17_chapter_3 } from "./part-17/chapter-3";
import { chapter as part_17_chapter_4 } from "./part-17/chapter-4";
import { chapter as part_18_chapter_1 } from "./part-18/chapter-1";
import { chapter as part_18_chapter_2 } from "./part-18/chapter-2";
import { chapter as part_18_chapter_3 } from "./part-18/chapter-3";
import { chapter as part_18_chapter_4 } from "./part-18/chapter-4";
import { chapter as part_19_chapter_1 } from "./part-19/chapter-1";
import { chapter as part_19_chapter_2 } from "./part-19/chapter-2";
import { chapter as part_19_chapter_3 } from "./part-19/chapter-3";
import { chapter as part_19_chapter_4 } from "./part-19/chapter-4";
import { chapter as part_20_chapter_1 } from "./part-20/chapter-1";
import { chapter as part_20_chapter_2 } from "./part-20/chapter-2";
import { chapter as part_20_chapter_3 } from "./part-20/chapter-3";
import { chapter as part_20_chapter_4 } from "./part-20/chapter-4";
import { chapter as part_21_chapter_1 } from "./part-21/chapter-1";
import { chapter as part_21_chapter_2 } from "./part-21/chapter-2";
import { chapter as part_21_chapter_3 } from "./part-21/chapter-3";
import { chapter as part_21_chapter_4 } from "./part-21/chapter-4";
import { chapter as part_22_chapter_1 } from "./part-22/chapter-1";
import { chapter as part_22_chapter_2 } from "./part-22/chapter-2";
import { chapter as part_22_chapter_3 } from "./part-22/chapter-3";
import { chapter as part_22_chapter_4 } from "./part-22/chapter-4";
import { chapter as part_23_chapter_1 } from "./part-23/chapter-1";
import { chapter as part_23_chapter_2 } from "./part-23/chapter-2";
import { chapter as part_23_chapter_3 } from "./part-23/chapter-3";
import { chapter as part_23_chapter_4 } from "./part-23/chapter-4";

export const chapterPaths: Record<string, string> = {
  "tt-unit-testing": "part-1/chapter-1.ts",
  "tt-integration-testing": "part-1/chapter-2.ts",
  "tt-system-testing": "part-1/chapter-3.ts",
  "tt-acceptance-testing": "part-1/chapter-4.ts",
  "tt-manual-testing": "part-2/chapter-1.ts",
  "tt-automated-testing": "part-2/chapter-2.ts",
  "tt-functional-testing": "part-2/chapter-3.ts",
  "tt-smoke-testing": "part-2/chapter-4.ts",
  "tt-sanity-testing": "part-3/chapter-1.ts",
  "tt-regression-testing": "part-3/chapter-2.ts",
  "tt-interface-testing": "part-3/chapter-3.ts",
  "tt-usability-testing": "part-3/chapter-4.ts",
  "tt-performance-testing": "part-4/chapter-1.ts",
  "tt-load-testing": "part-4/chapter-2.ts",
  "tt-stress-testing": "part-4/chapter-3.ts",
  "tt-scalability-testing": "part-4/chapter-4.ts",
  "tt-volume-testing": "part-5/chapter-1.ts",
  "tt-security-testing": "part-5/chapter-2.ts",
  "tt-compatibility-testing": "part-5/chapter-3.ts",
  "tt-reliability-testing": "part-5/chapter-4.ts",
  "tt-accessibility-testing": "part-6/chapter-1.ts",
  "tt-exploratory-testing": "part-6/chapter-2.ts",
  "tt-localization-testing": "part-6/chapter-3.ts",
  "tt-recovery-testing": "part-6/chapter-4.ts",
  "tt-black-box-testing": "part-7/chapter-1.ts",
  "tt-white-box-testing": "part-7/chapter-2.ts",
  "tt-gray-box-testing": "part-7/chapter-3.ts",
  "tt-adhoc-testing": "part-7/chapter-4.ts",
  "tt-alpha-testing": "part-8/chapter-1.ts",
  "tt-beta-testing": "part-8/chapter-2.ts",
  "tt-retesting": "part-8/chapter-3.ts",
  "tt-mutation-testing": "part-8/chapter-4.ts",
  "tt-ab-testing": "part-9/chapter-1.ts",
  "tt-api-testing": "part-9/chapter-2.ts",
  "tt-database-testing": "part-9/chapter-3.ts",
  "tt-end-to-end-testing": "part-9/chapter-4.ts",
  "tt-cross-browser-testing": "part-10/chapter-1.ts",
  "tt-mobile-testing": "part-10/chapter-2.ts",
  "tt-installation-testing": "part-10/chapter-3.ts",
  "tt-penetration-testing": "part-10/chapter-4.ts",
  "tt-seo-site-health-testing": "part-11/chapter-1.ts",
  "tt-uptime-availability-testing": "part-11/chapter-2.ts",
  "tt-fuzz-testing": "part-11/chapter-3.ts",
  "tt-vulnerability-scanning": "part-11/chapter-4.ts",
  "tt-static-testing": "part-12/chapter-1.ts",
  "tt-dynamic-testing": "part-12/chapter-2.ts",
  "tt-gui-testing": "part-12/chapter-3.ts",
  "tt-visual-regression-testing": "part-12/chapter-4.ts",
  "tt-negative-testing": "part-13/chapter-1.ts",
  "tt-positive-testing": "part-13/chapter-2.ts",
  "tt-boundary-value-analysis": "part-13/chapter-3.ts",
  "tt-equivalence-partitioning": "part-13/chapter-4.ts",
  "tt-monkey-testing": "part-14/chapter-1.ts",
  "tt-chaos-testing": "part-14/chapter-2.ts",
  "tt-contract-testing": "part-14/chapter-3.ts",
  "tt-concurrency-testing": "part-14/chapter-4.ts",
  "tt-configuration-testing": "part-15/chapter-1.ts",
  "tt-data-migration-testing": "part-15/chapter-2.ts",
  "tt-disaster-recovery-testing": "part-15/chapter-3.ts",
  "tt-documentation-testing": "part-15/chapter-4.ts",
  "tt-compliance-testing": "part-16/chapter-1.ts",
  "tt-pilot-testing": "part-16/chapter-2.ts",
  "tt-parallel-testing": "part-16/chapter-3.ts",
  "tt-bigbang-vs-incremental-testing": "part-16/chapter-4.ts",
  "tt-data-driven-testing": "part-17/chapter-1.ts",
  "tt-keyword-driven-testing": "part-17/chapter-2.ts",
  "tt-model-based-testing": "part-17/chapter-3.ts",
  "tt-risk-based-testing": "part-17/chapter-4.ts",
  "tt-backend-testing": "part-18/chapter-1.ts",
  "tt-network-testing": "part-18/chapter-2.ts",
  "tt-snapshot-testing": "part-18/chapter-3.ts",
  "tt-soak-endurance-testing": "part-18/chapter-4.ts",
  "tt-continuous-testing-cicd": "part-19/chapter-1.ts",
  "tt-interoperability-testing": "part-19/chapter-2.ts",
  "tt-conformance-testing": "part-19/chapter-3.ts",
  "tt-globalization-testing": "part-19/chapter-4.ts",
  "tt-baseline-testing": "part-20/chapter-1.ts",
  "tt-comparative-testing": "part-20/chapter-2.ts",
  "tt-domain-testing": "part-20/chapter-3.ts",
  "tt-error-guessing-testing": "part-20/chapter-4.ts",
  "tt-coverage-testing": "part-21/chapter-1.ts",
  "tt-operational-acceptance-testing": "part-21/chapter-2.ts",
  "tt-cloud-testing": "part-21/chapter-3.ts",
  "tt-golden-master-testing": "part-21/chapter-4.ts",
  "tt-content-testing": "part-22/chapter-1.ts",
  "tt-cookie-session-testing": "part-22/chapter-2.ts",
  "tt-object-oriented-testing": "part-22/chapter-3.ts",
  "tt-pwa-testing": "part-22/chapter-4.ts",
  "tt-incremental-integration-testing": "part-23/chapter-1.ts",
  "tt-spike-testing": "part-23/chapter-2.ts",
  "tt-session-based-testing": "part-23/chapter-3.ts",
  "tt-voice-conversational-ui-testing": "part-23/chapter-4.ts",
};

export const chapters: ChapterRecord[] = [
  part_1_chapter_1,
  part_1_chapter_2,
  part_1_chapter_3,
  part_1_chapter_4,
  part_2_chapter_1,
  part_2_chapter_2,
  part_2_chapter_3,
  part_2_chapter_4,
  part_3_chapter_1,
  part_3_chapter_2,
  part_3_chapter_3,
  part_3_chapter_4,
  part_4_chapter_1,
  part_4_chapter_2,
  part_4_chapter_3,
  part_4_chapter_4,
  part_5_chapter_1,
  part_5_chapter_2,
  part_5_chapter_3,
  part_5_chapter_4,
  part_6_chapter_1,
  part_6_chapter_2,
  part_6_chapter_3,
  part_6_chapter_4,
  part_7_chapter_1,
  part_7_chapter_2,
  part_7_chapter_3,
  part_7_chapter_4,
  part_8_chapter_1,
  part_8_chapter_2,
  part_8_chapter_3,
  part_8_chapter_4,
  part_9_chapter_1,
  part_9_chapter_2,
  part_9_chapter_3,
  part_9_chapter_4,
  part_10_chapter_1,
  part_10_chapter_2,
  part_10_chapter_3,
  part_10_chapter_4,
  part_11_chapter_1,
  part_11_chapter_2,
  part_11_chapter_3,
  part_11_chapter_4,
  part_12_chapter_1,
  part_12_chapter_2,
  part_12_chapter_3,
  part_12_chapter_4,
  part_13_chapter_1,
  part_13_chapter_2,
  part_13_chapter_3,
  part_13_chapter_4,
  part_14_chapter_1,
  part_14_chapter_2,
  part_14_chapter_3,
  part_14_chapter_4,
  part_15_chapter_1,
  part_15_chapter_2,
  part_15_chapter_3,
  part_15_chapter_4,
  part_16_chapter_1,
  part_16_chapter_2,
  part_16_chapter_3,
  part_16_chapter_4,
  part_17_chapter_1,
  part_17_chapter_2,
  part_17_chapter_3,
  part_17_chapter_4,
  part_18_chapter_1,
  part_18_chapter_2,
  part_18_chapter_3,
  part_18_chapter_4,
  part_19_chapter_1,
  part_19_chapter_2,
  part_19_chapter_3,
  part_19_chapter_4,
  part_20_chapter_1,
  part_20_chapter_2,
  part_20_chapter_3,
  part_20_chapter_4,
  part_21_chapter_1,
  part_21_chapter_2,
  part_21_chapter_3,
  part_21_chapter_4,
  part_22_chapter_1,
  part_22_chapter_2,
  part_22_chapter_3,
  part_22_chapter_4,
  part_23_chapter_1,
  part_23_chapter_2,
  part_23_chapter_3,
  part_23_chapter_4
];
