import type { ChapterRecord } from "../../../types";

/** 31. Shadow DOM & Complex Components */
export const chapter = {
  id: "pw-31-shadow",
  title: "31. Shadow DOM & Complex Components",
  minutes: 40,
  level: "advanced",
  phase: "Part 4 · Advanced Techniques",
  partName: "Part 4 · Advanced Techniques",
  overviewText: "Playwright pierces open shadow DOM automatically — standard get_by_role/get_by_text locators work without special syntax. Closed shadow roots are inaccessible by design. Complex components (date pickers, rich text) may need keyboard.type() instead of fill().",
  why: "Design systems increasingly use web components. Playwright's automatic piercing means the same locator strategy works inside shadow roots.",
  when: "Use role/text locators first inside custom components. Chain page.locator('tag').get_by_role() when needed. Escalate closed shadow roots to dev team for ARIA hooks.",
  practical: { app: "HRMS — Design system date picker", scenario: "Custom hrms-date-picker uses open shadow DOM; get_by_label still works via accessibility tree.", pass: "page.get_by_role('button', name='Save').click() inside component.", fail: "page.locator('#shadow-internal-btn') — cannot cross shadow boundary." },
  tools: [],
  contentMarkdown: "## 31. Shadow DOM & Complex Components\n\nPlaywright pierces shadow DOM automatically — no special syntax required for open shadow roots.\n```python\npage.locator(\"my-custom-element\").get_by_role(\"button\", name=\"Submit\").click()\n```\n\n\nShadow DOM is a browser feature letting web components encapsulate their internal markup/styling, common in design systems (many component libraries render their internals inside a shadow root to prevent CSS leakage). Unlike older tools, which often needed special handling to \"pierce\" into shadow roots, Playwright's standard locators transparently search inside open shadow roots as if they were regular DOM — you generally don't need to do anything different at all, which is a deliberate design choice tied back to Part 0's note about Playwright being built with modern component-based UI in mind from day one.\nClosed shadow roots are a genuine limitation, not a Playwright gap.\nA small but important caveat: this transparent piercing only works for open shadow roots (mode: 'open'), which is the overwhelming majority of real-world usage. Closed shadow roots (mode: 'closed') are deliberately inaccessible from outside JavaScript by browser design — this isn't a Playwright limitation to work around, it's the same restriction any browser automation tool faces, since closed shadow roots are specifically designed to prevent exactly this kind of external access. If you hit this, the practical options are asking the dev team to switch the component to open mode (if there's no strong reason for it to be closed) or falling back to visual/screenshot-based assertions for that specific component.\nComplex custom components (date pickers, rich text editors, custom dropdowns) often need interaction patterns beyond simple locators.\n```python\n# Example: a custom date picker requiring multiple clicks\npage.get_by_role(\"button\", name=\"Select date\").click()\npage.get_by_role(\"gridcell\", name=\"15\").click()\n\n# Example: a rich text editor (contenteditable div)\npage.locator(\"[contenteditable='true']\").click()\n```\n\npage.keyboard.type(\"This is my message\")\n\nMany modern \"complex\" components aren't native HTML elements at all — a date picker is usually a styled popup with clickable day cells, and a rich text editor is often a contenteditable div rather than a <textarea>. This means the locator/action strategies from Chapter 13/14 still apply directly (role-based locators for calendar cells, page.keyboard.type() for typing into a contenteditable region), but you often need to think in terms of \"what does this actually render as in the DOM\" rather than assuming a form-input-style interaction like .fill() will work. Worth deliberately inspecting a component's real markup (dev tools, or Playwright's own Inspector from Chapter 35) before assuming which interaction pattern applies.",
  customSummary: "## 31. Shadow DOM & Complex Components\n\nPlaywright automatically pierces open shadow roots — standard locators work with no special syntax.\nClosed shadow roots are inaccessible by browser design, not a Playwright gap — options are asking devs to open the mode, or falling back to visual assertions.\nComplex custom components (date pickers, contenteditable rich text editors) often aren't native inputs — inspect actual markup and use role-based locators / page.keyboard.type() rather than assuming .fill() works.",
  exercises: [],
  resourceLinks: [],
  steps: [],
  learn: [],
} as ChapterRecord;
