import type { ChapterRecord } from "../../../types";

/** 32. Parallel Execution & Sharding */
export const chapter = {
  id: "pw-32-parallel",
  title: "32. Parallel Execution & Sharding",
  minutes: 40,
  level: "advanced",
  phase: "Part 4 · Advanced Techniques",
  partName: "Part 4 · Advanced Techniques",
  overviewText: "pytest-xdist (-n auto or -n 4) runs tests across worker processes. Parallelization exposes hidden shared-state bugs. Sharding splits suites across CI machines for very large suites. Diminishing returns past optimal worker count.",
  why: "Sequential 400-test suites take hours. Parallel workers cut wall-clock time dramatically when tests are properly isolated.",
  when: "Enable when sequential time exceeds 15 minutes. Start with pytest -n auto. Ensure unique test data per worker. Shard via CI matrix when single-machine parallelism is insufficient.",
  practical: { app: "HRMS — Full regression suite", scenario: "380 tests at 25s each — 2.6 hours sequential; pytest -n 4 finishes in ~42 minutes.", pass: "pytest -n auto with Faker unique data and API teardown per test.", fail: "pytest -n 8 on 2-core machine thrashes; shared /tmp file corrupts parallel runs." },
  tools: [],
  contentMarkdown: "## 32. Parallel Execution & Sharding\n\npytest-xdist distributes tests across multiple worker processes to cut total suite runtime.\npip install pytest-xdist\n```python\npytest -n 4          # run with 4 parallel workers\npytest -n auto       # automatically use one worker per CPU core\n```\n\n\n-n <number> (integer, required) sets how many worker processes run tests simultaneously; -n auto detects available CPU cores and picks a matching number of workers automatically. Since each page fixture creates its own isolated BrowserContext (Part 1, Chapter 3), tests generally parallelize safely without extra work — the isolation that makes tests independent of each other for correctness is the same property that makes them safe to run concurrently.\nParallelization exposes shared-state bugs that were previously hidden by sequential execution.\nA test suite that \"worked fine\" running one test at a time can start failing intermittently once parallelized, if any tests share mutable state they weren't supposed to — a shared test-database record two tests both modify, a hardcoded port both try to bind, or (subtly) a session-scoped fixture that mutates something instead of just reading it. This is a common source of confusion the first time a team turns on parallel execution: failures that look like new bugs are often pre-existing test-isolation problems that sequential execution simply never surfaced.\nSharding splits a suite across multiple separate machines, not just multiple processes on one machine.\n```python\npytest --shard 1/4    # run shard 1 of 4 total shards (conceptual example; exact flag depends on plugin/CI setup)\n```\n\n\nWhile pytest-xdist's -n flag parallelizes across CPU cores on a single machine, sharding goes a step further — splitting the full test suite into N separate chunks that run on N entirely separate CI runners/machines simultaneously, further cutting wall-clock time for very large suites where even fully parallelizing on one machine still takes too long. This becomes relevant in Part 5's CI/CD chapter, where CI platforms typically provide native sharding/matrix-build support (e.g., GitHub Actions matrix strategy) that Playwright/pytest suites plug into.\nParallelization has diminishing returns and real costs worth weighing.\nMore workers isn't free — each worker needs its own browser instance (memory/CPU cost), and beyond a certain point, workers start contending for the same machine's limited resources, actually slowing things down rather than speeding them up. For a suite of a few dozen tests, sequential or lightly parallel execution might already be fast enough that the added complexity of tuning worker counts and debugging occasional flaky parallel-only failures isn't worth it yet — this becomes worthwhile once a suite grows large enough that runtime itself is a real bottleneck in the CI feedback loop.",
  customSummary: "## 32. Parallel Execution & Sharding\n\npytest-xdist's -n <count> (or -n auto) runs tests across multiple worker processes; per-test context isolation makes this generally safe.\nParallelization exposes pre-existing shared-state/test-isolation bugs that sequential runs hid.\nSharding splits the suite across multiple separate CI machines (beyond one machine's parallel workers) for very large suites — set up via CI platform features (Part 5).\nMore workers isn't free — diminishing returns and resource contention past a point; not worth the complexity for small suites.",
  exercises: [],
  resourceLinks: [],
  steps: [],
  learn: [],
} as ChapterRecord;
