import type { ChapterRecord } from "../../../types";

/** 1. Where Playwright is Used */
export const chapter = {
  id: "pw-1-where",
  title: "1. Where Playwright is Used",
  minutes: 30,
  level: "beginner",
  phase: "Part 0 · Background & Context",
  partName: "Part 0 · Background & Context",
  overviewText: "Playwright fits E2E user-journey tests, regression suites, API setup via APIRequestContext, visual regression, web scraping, and cross-browser CI — clustering in frontend-heavy and dedicated QA automation teams.",
  why: "Knowing where Playwright gets used — and where it doesn't — prevents recommending it for load testing or native mobile.",
  when: "Read when scoping a test strategy or answering when would you pick Playwright over Cypress in an interview.",
  practical: { app: "HRM system", scenario: "Team wants API seeding before UI tests without switching tools.", pass: "Propose APIRequestContext in the same pytest project for setup calls.", fail: "Suggest a separate Postman collection with manual cookie copying." },
  advantages: ["E2E specs mirror real user journeys with auto-waiting","APIRequestContext shares pytest project — no context switching","Built-in to_have_screenshot() — no third-party visual plugin","Cross-browser via single CLI flag or pytest parameter","Web scraping reuses same Browser → Context → Page model","Strong fit for dedicated QA teams with Python polyglot stacks"],
  limitations: ["API testing less flexible than dedicated httpx/REST Assured suites","Visual regression needs baseline maintenance discipline","Web scraping use case is out of manual scope","Mobile emulation is web-only — not native app testing","Industry adoption still growing versus Selenium in legacy enterprises","Cross-browser CI requires three engine installs via playwright install"],
  tools: [],
  contentMarkdown: "## 1. Where Playwright is Used\n\nWeb UI test automation (functional, regression, E2E). This is the primary use case and the one this manual focuses on almost entirely — functional testing (does a specific feature work as intended), regression testing (do previously-working features still work after a change), and end-to-end testing (simulating a full real user journey across multiple pages/features, not just one isolated piece). API testing. Playwright isn't just a browser tool — it ships APIRequestContext, letting you send raw HTTP requests (GET/POST/PUT/DELETE) without a browser at all. One tool covers both your UI layer and your backend API layer, instead of maintaining Playwright for UI and a separate tool (Postman/requests) for APIs. It also enables a practical hybrid pattern: using API calls to quickly set up test state (create a user, seed data) and only using the slower UI layer to test the actual feature under test. Visual regression testing. Beyond \"does the button work\" — this asks \"does the page still look right?\" Playwright can screenshot a page and pixel-diff it against a saved baseline, catching things functional tests miss entirely, like a CSS change making text invisible or a layout shift pushing a button off-screen. Web scraping / data extraction. Because Playwright fully renders JavaScript-heavy pages (unlike simple HTTP-request scrapers), it's also popular for scraping sites that load content dynamically. A side use case, not this manual's focus — but worth knowing it exists, since it sometimes comes up in interviews or side projects. Cross-browser compatibility testing. Running the identical suite against Chromium, Firefox, and WebKit to catch browser-specific bugs before real users do. This is what the multi-browser API makes possible in practice — you write the test once and just re-target the browser engine. Industries: e-commerce, SaaS, banking, healthcare. E-commerce checkout/payment flows are directly tied to revenue, so a broken \"Buy Now\" button costs money by the minute. SaaS ships UI changes constantly, often daily, so manual regression alone can't keep pace. Banking has heavy compliance/audit requirements that make documented, repeatable, automated test evidence often mandatory. Healthcare carries similar compliance pressure, plus accessibility requirements that are often legally required rather than nice-to-have. Worth adding EdTech (frequent releases, wide device variety among students) and travel/booking platforms (complex multi-step flows like date pickers, filters, and payment) as well. Relevance to your Bizlevate work: an HRM system is closer to SaaS/internal tooling — useful framing for pitching automation value internally, since it means fewer manual regression passes on Payroll/Attendance/Leave every release cycle.",
  customSummary: "## 1. Where Playwright is Used\n\n### Primary use: Web UI automation — functional, regression, E2E testing\n### API testing via APIRequestContext — same tool for UI + backend; also used to seed test data fast\n### Visual regression testing — pixel-diffing against baselines to catch layout/CSS bugs\n### Web scraping — secondary use case, handles JS-rendered pages well\n### Cross-browser testing — one suite run against Chromium/Firefox/WebKit\n- Heavy industries: e-commerce, SaaS, banking, healthcare (+ EdTech, travel/booking) — driven by revenue risk, release velocity, or compliance.\n- Bizlevate angle: HRM ≈ SaaS/internal tool → automation reduces manual regression load on Payroll/Attendance/Leave per release.",
  exercises: [],
  resourceLinks: [],
  steps: [],
  learn: [],
} as ChapterRecord;
