import { ch } from '../helpers.js'

/** Career paths — resume, portfolio, job hunt. */
export const careerManuals = [
  {
    id: 'resume-linkedin',
    title: 'Resume & LinkedIn',
    tagline: 'Make humans and ATS understand your craft in under 30 seconds.',
    category: 'career',
    accent: '#0B3D2E',
    cover: 'covers/interview-cover.png',
    duration: '1–2 weeks',
    levelSpan: 'Beginner → Pro',
    who: 'Anyone applying to QA, automation, or adjacent product roles.',
    outcomes: [
      'Rewrite bullets as impact, not chore lists',
      'Align resume + LinkedIn to one clear story',
      'Tailor for a role without rewriting your life',
    ],
    chapters: [
      ch({
        id: 'cv-story',
        kind: 'guide',
        phase: 'Start',
        level: 'beginner',
        title: 'Pick your spine story',
        minutes: 25,
        overview: 'Recruiters skim. One sentence should say who you are and what you want next.',
        learn: ['Positioning line', 'Audience', 'Truth over fluff'],
        steps: [
          {
            title: 'Write the spine',
            body: '“I help X do Y by Z.” Example: “QA automation engineer who makes Playwright suites trustworthy for product teams.”',
            doThis: 'Write three spines. Pick one. Put it at the top of your draft.',
          },
        ],
        checklist: ['Spine sentence chosen', 'Target role named'],
      }),
      ch({
        id: 'cv-bullets',
        phase: 'A · Resume',
        level: 'beginner',
        title: 'Bullets that prove skill',
        minutes: 35,
        overview: 'Action + scope + result. Numbers when honest. Drop “responsible for.”',
        learn: ['Impact formula', 'Metrics honesty', 'Keyword fit'],
        steps: [
          {
            title: 'Rewrite five bullets',
            body: 'Turn duties into outcomes. Prefer “cut flake rate 40%” over “worked on automation.”',
            doThis: 'Rewrite five bullets. Read them aloud — cut the mush.',
            tip: 'If you can’t measure, describe decision quality or risk removed.',
          },
        ],
        checklist: ['Five bullets rewritten', 'No “responsible for” left'],
      }),
      ch({
        id: 'cv-tailor',
        phase: 'A · Resume',
        level: 'intermediate',
        title: 'Tailor without lying',
        minutes: 30,
        overview: 'Mirror the job’s language for real skills you have. Reorder; don’t invent.',
        learn: ['JD mapping', 'ATS basics', 'One-page vs two'],
        steps: [
          {
            title: 'Map one JD',
            body: 'Highlight required skills. Mark have / partial / no. Adjust order and examples.',
            doThis: 'Produce a tailored one-pager for a real posting.',
          },
        ],
        checklist: ['JD map done', 'Tailored PDF exported'],
      }),
      ch({
        id: 'cv-li',
        phase: 'B · LinkedIn',
        level: 'intermediate',
        title: 'LinkedIn that matches',
        minutes: 30,
        overview: 'Headline, about, featured links. Consistency beats daily posting cosplay.',
        learn: ['Headline formula', 'About structure', 'Featured proof'],
        steps: [
          {
            title: 'Align the trio',
            body: 'Headline ≈ spine. About expands it. Featured shows GitHub / portfolio / writing.',
            doThis: 'Update headline + about + one featured link today.',
          },
        ],
        checklist: ['Headline updated', 'About rewritten', 'One featured proof live'],
      }),
      ch({
        id: 'cv-cp',
        kind: 'checkpoint',
        phase: 'B · LinkedIn',
        level: 'intermediate',
        title: 'Checkpoint: peer review',
        minutes: 40,
        durationLabel: 'Gate',
        overview: 'Get a cold reader: can they say your target role and strongest proof in 20 seconds?',
        learn: ['Feedback intake'],
        steps: [
          {
            title: '20-second test',
            body: 'Hand resume + LinkedIn to someone. No context. Capture what they say.',
            doThis: 'Fix the top mismatch they found.',
          },
        ],
        checklist: ['Peer did 20-second test', 'One fix shipped'],
        practice: { title: 'Cold read', brief: 'Complete the checkpoint with someone outside your team.' },
      }),
    ],
    resources: {
      docs: [
        { name: 'Harvard resume guide (structure)', url: 'https://careerservices.fas.harvard.edu/resources/create-a-strong-resume/' },
      ],
      tools: ['Google Docs / Word', 'PDF export', 'LinkedIn'],
      books: ['What Color Is Your Parachute? (selective)'],
      practice: [],
      videos: [],
    },
  },
  {
    id: 'portfolio',
    title: 'Portfolio That Hires',
    tagline: 'Public proof beats claims — repos, writeups, and demos employers can trust.',
    category: 'career',
    accent: '#145C4A',
    cover: 'covers/git-cover.png',
    duration: '2–4 weeks',
    levelSpan: 'Beginner → Pro',
    who: 'Automation and QA folks who need a GitHub story, not a graveyard of half-repos.',
    outcomes: [
      'Ship one portfolio repo with README that sells the craft',
      'Show architecture, tests, and CI in plain language',
      'Record a short demo employers will actually watch',
    ],
    chapters: [
      ch({
        id: 'pf-pick',
        kind: 'guide',
        phase: 'Start',
        level: 'beginner',
        title: 'One flagship, not twelve toys',
        minutes: 20,
        overview: 'Depth beats clutter. One excellent Playwright/framework repo outperforms ten tutorials.',
        learn: ['Flagship criteria', 'What to leave out'],
        steps: [
          {
            title: 'Choose the flagship',
            body: 'Must: runnable, documented, shows judgment. Nice: CI badge, traces, API+UI.',
            doThis: 'Name the repo. Archive or hide the noise.',
          },
        ],
        checklist: ['Flagship named', 'Noise repos cleaned or archived'],
      }),
      ch({
        id: 'pf-readme',
        phase: 'A · Build proof',
        level: 'beginner',
        title: 'README as sales page',
        minutes: 35,
        overview: 'Problem, approach, how to run, architecture sketch, sample report. Assume zero Slack access.',
        learn: ['README structure', 'Screenshots / GIFs', 'Honest scope'],
        steps: [
          {
            title: 'Write the README',
            body: 'Top: what it is + why. Then quickstart. Then design choices. Then limitations.',
            doThis: 'Ship a README someone else can run in 15 minutes.',
            tip: 'A diagram beats three paragraphs of folder poetry.',
          },
        ],
        checklist: ['Quickstart works cold', 'Architecture section present'],
      }),
      ch({
        id: 'pf-ci',
        phase: 'A · Build proof',
        level: 'intermediate',
        title: 'CI & evidence',
        minutes: 35,
        overview: 'Green badge, artifacts, and a failure you can explain. That’s interview fuel.',
        learn: ['GitHub Actions basics', 'Artifacts', 'Flake honesty'],
        steps: [
          {
            title: 'Wire a pipeline',
            body: 'On PR: install, test, upload report/trace on failure.',
            doThis: 'Get a green run. Link it from README.',
          },
        ],
        checklist: ['CI green on main', 'Failure artifact linked or described'],
      }),
      ch({
        id: 'pf-demo',
        phase: 'B · Show it',
        level: 'intermediate',
        title: 'Two-minute demo',
        minutes: 30,
        overview: 'Talk over a recording: problem → structure → one test → CI. No apology tour.',
        learn: ['Demo script', 'Pacing', 'What to skip'],
        steps: [
          {
            title: 'Record once',
            body: 'Script 5 beats. Record. Watch at 1.5×. Cut filler.',
            doThis: 'Upload unlisted YouTube or Loom. Link from README.',
          },
        ],
        checklist: ['Demo under 3 minutes', 'Link on README'],
      }),
      ch({
        id: 'pf-cp',
        kind: 'checkpoint',
        phase: 'B · Show it',
        level: 'advanced',
        title: 'Checkpoint: hiring manager view',
        minutes: 45,
        durationLabel: 'Gate',
        overview: 'A stranger opens your repo. Can they run it and understand your design in 20 minutes?',
        learn: ['Friction logging'],
        steps: [
          {
            title: 'Cold run',
            body: 'Peer follows README only. You may not help live.',
            doThis: 'Fix every friction note they logged.',
          },
        ],
        checklist: ['Cold run completed', 'Friction fixes merged'],
        practice: { title: 'Stranger test', brief: 'Complete checkpoint with someone who hasn’t seen the repo.' },
      }),
    ],
    resources: {
      docs: [
        { name: 'GitHub Docs — Actions', url: 'https://docs.github.com/en/actions' },
        { name: 'Awesome README tips', url: 'https://github.com/matiassingers/awesome-readme' },
      ],
      tools: ['GitHub', 'Loom', 'Excalidraw'],
      books: [],
      practice: [],
      videos: [],
    },
  },
  {
    id: 'job-hunt',
    title: 'Job Hunt System',
    tagline: 'A calm pipeline for applications, outreach, and interviews — not panic scrolling.',
    category: 'career',
    accent: '#1A4A3A',
    cover: 'covers/problem-solving-cover.png',
    duration: 'Ongoing system',
    levelSpan: 'Beginner → Pro',
    who: 'People actively interviewing for QA / automation / hybrid roles.',
    outcomes: [
      'Run a weekly hunt cadence with a tracker',
      'Write outreach that isn’t cringe',
      'Debrief interviews into better next rounds',
    ],
    chapters: [
      ch({
        id: 'jh-system',
        kind: 'guide',
        phase: 'Start',
        level: 'beginner',
        title: 'Pipeline over vibes',
        minutes: 25,
        overview: 'Treat the hunt like a product: stages, WIP limits, weekly review. Emotion is data; panic isn’t a plan.',
        learn: ['Stages', 'WIP limits', 'Energy budgeting'],
        steps: [
          {
            title: 'Build the board',
            body: 'Columns: Research → Applied → Talking → Interview → Offer / Closed.',
            doThis: 'Create a sheet or Notion board. Cap Applied WIP at 8.',
          },
        ],
        checklist: ['Board exists', 'WIP limit set'],
      }),
      ch({
        id: 'jh-apply',
        phase: 'A · Motion',
        level: 'beginner',
        title: 'Quality applications',
        minutes: 30,
        overview: 'Fewer, sharper applications beat spray-and-pray. Match spine story to role.',
        learn: ['Role fit score', 'Cover note lite', 'Referral paths'],
        steps: [
          {
            title: 'Score then send',
            body: '1–5 fit. Only apply at 3+. Customize top third of resume.',
            doThis: 'Send two high-fit apps this week. Log them.',
          },
        ],
        checklist: ['Fit score used', 'Two quality apps logged'],
      }),
      ch({
        id: 'jh-outreach',
        phase: 'A · Motion',
        level: 'intermediate',
        title: 'Human outreach',
        minutes: 25,
        overview: 'Short, specific, generous. Ask for a 15-minute reality check — not a job.',
        learn: ['Message structure', 'Follow-ups', 'No parasocial essays'],
        steps: [
          {
            title: 'Write the template',
            body: 'Who you are · why them · one sharp question · easy out.',
            doThis: 'Send three thoughtful notes. Track replies.',
          },
        ],
        checklist: ['Template saved', 'Three notes sent'],
      }),
      ch({
        id: 'jh-interview',
        phase: 'B · Interviews',
        level: 'intermediate',
        title: 'Interview loops',
        minutes: 35,
        overview: 'Stories (STAR-ish), system design lite for test strategy, live coding calm.',
        learn: ['Story bank', 'Strategy questions', 'Post-mortem notes'],
        steps: [
          {
            title: 'Bank five stories',
            body: 'Conflict, flake hunt, shipping under pressure, teaching, mistake+fix.',
            doThis: 'Write five stories at bullet fidelity. Practice one aloud.',
          },
        ],
        checklist: ['Five stories banked', 'One practiced aloud'],
        links: [{ name: 'Interview Craft (Pathwise)', url: '/Pathwise/manuals/interview-craft', kind: 'doc' }],
      }),
      ch({
        id: 'jh-cp',
        kind: 'checkpoint',
        phase: 'B · Interviews',
        level: 'advanced',
        title: 'Checkpoint: weekly review',
        minutes: 30,
        durationLabel: 'Gate',
        overview: 'Every week: metrics, learnings, next bets. The system should feel boringly steady.',
        learn: ['Review ritual'],
        steps: [
          {
            title: 'Run the review',
            body: 'Apps sent, replies, interviews, energy 1–5, one process change.',
            doThis: 'Write the weekly note. Schedule next review.',
          },
        ],
        checklist: ['Weekly note written', 'One process tweak chosen'],
        practice: { title: 'Four-week streak', brief: 'Complete four weekly reviews. Adjust WIP if energy tanks.' },
      }),
    ],
    resources: {
      docs: [],
      tools: ['Notion / Sheets tracker', 'Calendar blocks'],
      books: ['Designing Your Life — Burnett & Evans (selective)'],
      practice: [],
      videos: [],
    },
  },
]
