import { ch } from '../helpers.js'

/** Quality craft — a11y, security, mobile, containers. */
export const qualityManuals = [
  {
    id: 'accessibility',
    title: 'Accessibility Testing',
    tagline: 'Ship products everyone can use — keyboard, screen reader, contrast, and judgment.',
    category: 'quality',
    accent: '#0B3D2E',
    cover: 'covers/uiux-cover.png',
    duration: '3–5 weeks',
    levelSpan: 'Beginner → Pro',
    who: 'QA and builders who want a11y to be a skill, not a checklist afterthought.',
    outcomes: [
      'Audit a page with keyboard + one screen reader pass',
      'Write bugs that cite WCAG success criteria',
      'Partner with design/dev on remediations that stick',
    ],
    chapters: [
      ch({
        id: 'a11y-why',
        kind: 'guide',
        phase: 'Start',
        level: 'beginner',
        title: 'Why accessibility is quality',
        minutes: 25,
        overview:
          'Accessibility is not “extra.” It’s whether people can complete the job. Legal risk matters; dignity matters more. This chapter sets the mindset before tools.',
        learn: ['Who is affected', 'POUR principles', 'How a11y bugs differ'],
        steps: [
          {
            title: 'Meet real barriers',
            body: 'Name four barriers: vision, hearing, motor, cognitive. Map each to a product failure you’ve seen (or imagine).',
            doThis: 'Pick your product. List one barrier a user would hit today.',
          },
          {
            title: 'POUR as a compass',
            body: 'Perceivable, Operable, Understandable, Robust. Use it to sort findings instead of dumping “a11y issue.”',
            doThis: 'Rewrite one vague bug title using a POUR lens.',
          },
        ],
        checklist: ['I can explain POUR in one sentence each', 'One product barrier written down'],
        practice: { title: 'Barrier memo', brief: 'Half-page note: who is blocked, where, and what “done” looks like.' },
        links: [{ name: 'W3C WAI Introduction', url: 'https://www.w3.org/WAI/fundamentals/accessibility-intro/', kind: 'doc' }],
        citations: [{ name: 'WCAG 2 Overview', url: 'https://www.w3.org/WAI/standards-guidelines/wcag/' }],
      }),
      ch({
        id: 'a11y-keyboard',
        phase: 'A · Core audits',
        level: 'beginner',
        title: 'Keyboard & focus',
        minutes: 35,
        overview: 'If you can’t tab through it, assistive tech usually can’t either. Focus order and visible rings are non-negotiable.',
        learn: ['Tab order', 'Focus visibility', 'Skip links & traps'],
        steps: [
          {
            title: 'Unplug the mouse',
            body: 'Complete a primary flow with keyboard only. Note traps, missing focus, and weird order.',
            doThis: 'Record a 60-second Loom (or notes) of the keyboard path.',
            tip: 'Escape should close modals. Focus should return to the opener.',
          },
        ],
        checklist: ['Primary flow done keyboard-only', 'Focus ring visible on interactive controls'],
        practice: { title: 'Keyboard bug', brief: 'File one keyboard defect with steps, expected, and severity.' },
      }),
      ch({
        id: 'a11y-sr',
        phase: 'A · Core audits',
        level: 'intermediate',
        title: 'Screen reader pass',
        minutes: 40,
        overview: 'One structured pass beats endless tooling. Learn landmarks, names, and announcements.',
        learn: ['Landmarks & headings', 'Accessible names', 'Live regions'],
        steps: [
          {
            title: 'Headings as map',
            body: 'Navigate by heading. If the outline is chaos, content is chaos for SR users.',
            doThis: 'Dump the heading outline. Fix or file the worst gap.',
          },
        ],
        checklist: ['One SR pass on a key page', 'Accessible name verified on icon buttons'],
        links: [{ name: 'ARIA Authoring Practices', url: 'https://www.w3.org/WAI/ARIA/apg/', kind: 'doc' }],
      }),
      ch({
        id: 'a11y-tools',
        phase: 'B · Tools & criteria',
        level: 'intermediate',
        title: 'Automated + manual balance',
        minutes: 30,
        overview: 'axe finds ~30–50% of issues. Manual judgment finds the rest. Use both without worshipping either.',
        learn: ['What automation catches', 'False confidence', 'WCAG mapping'],
        steps: [
          {
            title: 'Run axe, then distrust it',
            body: 'Fix criticals. Then find one issue automation missed (focus, name quality, cognitive load).',
            doThis: 'Side-by-side: automation report vs your manual find.',
          },
        ],
        checklist: ['axe (or similar) run saved', 'One manual-only finding documented'],
      }),
      ch({
        id: 'a11y-cp',
        kind: 'checkpoint',
        phase: 'B · Tools & criteria',
        level: 'intermediate',
        title: 'Checkpoint: a11y audit',
        minutes: 45,
        durationLabel: 'Gate',
        overview: 'Deliver a short audit of one flow: keyboard, one SR pass, contrast notes, and WCAG-tagged bugs.',
        learn: ['Audit packaging', 'Severity with impact'],
        steps: [
          {
            title: 'Ship the audit',
            body: '2–4 pages max. Findings with criteria IDs. Top 3 remediations ranked by user impact.',
            doThis: 'Publish the audit in your notes or GitHub.',
          },
        ],
        checklist: ['Keyboard + SR covered', 'At least 3 findings with criteria', 'Remediation order clear'],
        practice: { title: 'Audit deliverable', brief: 'Complete the checkpoint package and share with a peer for feedback.' },
      }),
      ch({
        id: 'a11y-pro',
        phase: 'C · Pro habits',
        level: 'advanced',
        title: 'Shift-left with design & CI',
        minutes: 35,
        overview: 'Catch issues in Figma reviews and PR checks. Make a11y a team rhythm, not a release panic.',
        learn: ['Design crit prompts', 'CI linting limits', 'Regression habits'],
        steps: [
          {
            title: 'Add one gate',
            body: 'Pick: design checklist item, component story a11y addon, or CI axe on a key route.',
            doThis: 'Propose the gate in writing. Get one +1.',
          },
        ],
        checklist: ['One shift-left gate proposed', 'Regression note for future releases'],
        practice: { title: 'Team ritual', brief: 'Add a11y to your definition of done for the next sprint.' },
      }),
    ],
    resources: {
      docs: [
        { name: 'WCAG 2.2', url: 'https://www.w3.org/TR/WCAG22/' },
        { name: 'axe DevTools', url: 'https://www.deque.com/axe/devtools/' },
      ],
      tools: ['axe DevTools', 'VoiceOver / NVDA', 'Colour Contrast Analyser'],
      books: ['Inclusive Design Patterns — Heydon Pickering'],
      practice: ['https://www.w3.org/WAI/demos/bad/'],
      videos: [{ name: 'a11y project resources', url: 'https://www.a11yproject.com/' }],
    },
  },
  {
    id: 'security-testing',
    title: 'Security Testing Basics',
    tagline: 'Think like an attacker enough to catch the boring, devastating bugs.',
    category: 'quality',
    accent: '#1A4A3A',
    cover: 'covers/api-testing-cover.png',
    duration: '3–4 weeks',
    levelSpan: 'Beginner → Intermediate',
    who: 'QA engineers adding security awareness without becoming full-time pen testers.',
    outcomes: [
      'Spot OWASP Top 10 smells in features you test',
      'Test authz boundaries and sensitive data leaks',
      'Write clear security bugs without fear-mongering',
    ],
    chapters: [
      ch({
        id: 'sec-mindset',
        kind: 'guide',
        phase: 'Start',
        level: 'beginner',
        title: 'Security mindset for QA',
        minutes: 25,
        overview: 'You don’t need to hack banks. You need to ask “what if I’m not who I claim?” and “what if this input is hostile?”',
        learn: ['Trust boundaries', 'Threat vs vulnerability', 'Responsible reporting'],
        steps: [
          {
            title: 'Draw the trust line',
            body: 'Client, server, third parties. Mark what you trust and why.',
            doThis: 'Sketch a trust map for one feature.',
          },
        ],
        checklist: ['Trust map sketched', 'I know how to escalate findings'],
        links: [{ name: 'OWASP Top 10', url: 'https://owasp.org/www-project-top-ten/', kind: 'doc' }],
      }),
      ch({
        id: 'sec-auth',
        phase: 'A · Common flaws',
        level: 'beginner',
        title: 'Auth & session basics',
        minutes: 35,
        overview: 'Broken auth and session mishandling are still everyday bugs. Test logout, expiry, and privilege.',
        learn: ['Session fixation smells', 'Logout reality', 'Role checks'],
        steps: [
          {
            title: 'Horizontal privilege',
            body: 'Can user A see user B’s resource by changing an ID?',
            doThis: 'Attempt one IDOR-style check on a safe staging app.',
            tip: 'Never test production with destructive payloads.',
          },
        ],
        checklist: ['Logout verified', 'One IDOR attempt documented'],
      }),
      ch({
        id: 'sec-input',
        phase: 'A · Common flaws',
        level: 'intermediate',
        title: 'Injection & XSS awareness',
        minutes: 35,
        overview: 'Know enough XSS/SQLi patterns to recognize them and hand off safely.',
        learn: ['Reflected vs stored XSS', 'Input sinks', 'Safe proof-of-concept'],
        steps: [
          {
            title: 'Harmless probe',
            body: 'Use a benign marker string. If it renders raw, escalate. Don’t spray real exploits.',
            doThis: 'Test one form field with a safe marker; note encoding.',
          },
        ],
        checklist: ['Safe probe recorded', 'Encoding behavior noted'],
      }),
      ch({
        id: 'sec-cp',
        kind: 'checkpoint',
        phase: 'B · Practice',
        level: 'intermediate',
        title: 'Checkpoint: security smoke',
        minutes: 40,
        durationLabel: 'Gate',
        overview: 'Run a mini security smoke on staging: authz, session, sensitive fields, headers notes.',
        learn: ['Smoke packaging', 'Severity language'],
        steps: [
          {
            title: 'Ship the smoke report',
            body: 'One page: what you tried, what failed, what’s unknown.',
            doThis: 'Write the report. Include “out of scope.”',
          },
        ],
        checklist: ['Authz checks done', 'Session checks done', 'Report shared'],
        practice: { title: 'Smoke pack', brief: 'Complete checkpoint report on a practice app (e.g. OWASP Juice Shop).' },
        links: [{ name: 'OWASP Juice Shop', url: 'https://owasp.org/www-project-juice-shop/', kind: 'practice' }],
      }),
      ch({
        id: 'sec-pro',
        phase: 'B · Practice',
        level: 'advanced',
        title: 'Partnering with AppSec',
        minutes: 25,
        overview: 'Know when to stop and escalate. Build a lightweight security regression list for releases.',
        learn: ['Escalation paths', 'Regression checklist', 'Secrets hygiene in tests'],
        steps: [
          {
            title: 'Regression list',
            body: 'Five checks you will always run before major releases.',
            doThis: 'Add the list to your team wiki or README.',
          },
        ],
        checklist: ['Escalation contact known', '5-item regression list exists'],
      }),
    ],
    resources: {
      docs: [
        { name: 'OWASP Top 10', url: 'https://owasp.org/www-project-top-ten/' },
        { name: 'OWASP Testing Guide', url: 'https://owasp.org/www-project-web-security-testing-guide/' },
      ],
      tools: ['Burp Community (careful)', 'browser DevTools', 'OWASP ZAP'],
      books: ['The Web Application Hacker’s Handbook (select chapters)'],
      practice: ['https://owasp.org/www-project-juice-shop/'],
      videos: [],
    },
  },
  {
    id: 'mobile-testing',
    title: 'Mobile Testing',
    tagline: 'Phones aren’t small desktops — gestures, networks, and interrupts change everything.',
    category: 'quality',
    accent: '#0F5C4C',
    cover: 'covers/test-automation-cover.png',
    duration: '2–4 weeks',
    levelSpan: 'Beginner → Intermediate',
    who: 'QA covering iOS/Android apps or responsive web on real devices.',
    outcomes: [
      'Build a mobile test matrix that isn’t “every phone ever”',
      'Catch gesture, interrupt, and offline bugs',
      'Know when to automate vs explore on device',
    ],
    chapters: [
      ch({
        id: 'mob-matrix',
        kind: 'guide',
        phase: 'Start',
        level: 'beginner',
        title: 'Devices, OS, and risk',
        minutes: 25,
        overview: 'You can’t test every device. You can cover risk: top OS versions, screen sizes, and fragile flows.',
        learn: ['Risk-based matrix', 'Emulator vs real device', 'WebView traps'],
        steps: [
          {
            title: 'Draft a matrix',
            body: 'Rows: flows. Columns: OS/device class. Mark must / nice / skip.',
            doThis: 'Publish a one-page matrix for your product.',
          },
        ],
        checklist: ['Matrix drafted', 'Must-cover devices named'],
      }),
      ch({
        id: 'mob-gestures',
        phase: 'A · Real conditions',
        level: 'beginner',
        title: 'Gestures & layout',
        minutes: 30,
        overview: 'Touch targets, safe areas, rotation, and scroll physics. Desktop thinking fails here.',
        learn: ['Hit targets', 'Orientation', 'Safe areas'],
        steps: [
          {
            title: 'Fat finger pass',
            body: 'Use the app one-handed. Note cramped controls and accidental taps.',
            doThis: 'File one touch-target defect or confirm none on key screens.',
          },
        ],
        checklist: ['One-handed pass done', 'Rotation checked on key screens'],
      }),
      ch({
        id: 'mob-network',
        phase: 'A · Real conditions',
        level: 'intermediate',
        title: 'Network, battery, interrupts',
        minutes: 35,
        overview: 'Airplane mode, flaky LTE, incoming calls, backgrounding — reality for users.',
        learn: ['Offline UX', 'App switch resume', 'Permission prompts'],
        steps: [
          {
            title: 'Chaos lite',
            body: 'Kill network mid-flow. Background during upload. Deny a permission.',
            doThis: 'Log three outcomes with expected vs actual.',
          },
        ],
        checklist: ['Offline behavior noted', 'Background resume checked'],
      }),
      ch({
        id: 'mob-cp',
        kind: 'checkpoint',
        phase: 'B · Ship confidence',
        level: 'intermediate',
        title: 'Checkpoint: mobile smoke',
        minutes: 40,
        durationLabel: 'Gate',
        overview: 'Run a release smoke on one real device + one emulator: install, login, core flow, interrupt, offline.',
        learn: ['Smoke packaging'],
        steps: [
          {
            title: 'Execute & report',
            body: 'Pass/fail table. Screenshots for fails. Device details at top.',
            doThis: 'Ship the smoke report.',
          },
        ],
        checklist: ['Real device covered', 'Interrupt + offline covered', 'Report done'],
        practice: { title: 'Smoke day', brief: 'Complete the checkpoint on staging or a public demo app.' },
      }),
    ],
    resources: {
      docs: [
        { name: 'Android testing docs', url: 'https://developer.android.com/training/testing' },
        { name: 'XCTest', url: 'https://developer.apple.com/documentation/xctest' },
      ],
      tools: ['BrowserStack / Sauce (optional)', 'Android Emulator', 'Xcode Simulator'],
      books: [],
      practice: [],
      videos: [],
    },
  },
  {
    id: 'docker-qa',
    title: 'Docker for QA',
    tagline: 'Reproducible environments so “works on my machine” dies quietly.',
    category: 'quality',
    accent: '#145C4A',
    cover: 'covers/cicd-cover.png',
    duration: '2–3 weeks',
    levelSpan: 'Beginner → Intermediate',
    who: 'Testers who need local stacks, CI parity, and less env thrash.',
    outcomes: [
      'Run a service stack with Compose',
      'Understand images, volumes, and networking enough to debug',
      'Use containers in test pipelines thoughtfully',
    ],
    chapters: [
      ch({
        id: 'dk-why',
        kind: 'guide',
        phase: 'Start',
        level: 'beginner',
        title: 'Why containers help QA',
        minutes: 20,
        overview: 'Same bits everywhere. Isolate dependencies. Spin up DBs without polluting your laptop forever.',
        learn: ['Image vs container', 'When not to containerize'],
        steps: [
          {
            title: 'Mental model',
            body: 'Image = recipe. Container = running instance. Volume = durable data.',
            doThis: 'Explain the three terms to a rubber duck in writing.',
          },
        ],
        checklist: ['Terms clear', 'One use-case for your team named'],
        links: [{ name: 'Docker overview', url: 'https://docs.docker.com/get-started/overview/', kind: 'doc' }],
      }),
      ch({
        id: 'dk-compose',
        phase: 'A · Hands-on',
        level: 'beginner',
        title: 'Compose a test stack',
        minutes: 40,
        overview: 'docker compose up should be the onboarding sentence for your test env.',
        learn: ['compose.yml', 'Ports & healthchecks', 'Logs'],
        steps: [
          {
            title: 'Bring something up',
            body: 'Use a sample stack (web + db) or your team’s compose file.',
            doThis: 'compose up, hit a health endpoint, compose down.',
            tip: 'Read logs before restarting blindly.',
          },
        ],
        checklist: ['Stack started cleanly', 'I can find logs'],
      }),
      ch({
        id: 'dk-debug',
        phase: 'A · Hands-on',
        level: 'intermediate',
        title: 'Debug like a grown-up',
        minutes: 35,
        overview: 'exec into containers, check networks, reset volumes without panic.',
        learn: ['docker exec', 'Networks', 'Volume gotchas'],
        steps: [
          {
            title: 'Break and fix',
            body: 'Wrong env var or port clash. Diagnose with ps, logs, and inspect.',
            doThis: 'Document the failure mode and the fix in three bullets.',
          },
        ],
        checklist: ['Used exec or logs to diagnose', 'Wrote the three-bullet postmortem'],
      }),
      ch({
        id: 'dk-cp',
        kind: 'checkpoint',
        phase: 'B · CI mindset',
        level: 'intermediate',
        title: 'Checkpoint: reproducible demo',
        minutes: 45,
        durationLabel: 'Gate',
        overview: 'Hand someone a README: clone, compose up, run one test command, compose down.',
        learn: ['Onboarding clarity'],
        steps: [
          {
            title: 'README or it didn’t happen',
            body: 'Prereqs, commands, expected output, teardown.',
            doThis: 'Get a peer to follow it without Slack help.',
          },
        ],
        checklist: ['Peer succeeded from README', 'Teardown documented'],
        practice: { title: 'Peer dry-run', brief: 'Complete the checkpoint with a friend or future-you tomorrow.' },
      }),
    ],
    resources: {
      docs: [
        { name: 'Docker docs', url: 'https://docs.docker.com/' },
        { name: 'Compose specification', url: 'https://docs.docker.com/compose/compose-file/' },
      ],
      tools: ['Docker Desktop / Engine', 'Dive (optional)'],
      books: [],
      practice: ['https://docs.docker.com/get-started/'],
      videos: [],
    },
  },
]
