// ⚙️ AUTO-GENERATED by scripts/generate-chapter-index.mjs — do not edit by hand
import type { ChapterRecord } from "../../types";

import { chapter as part_0_chapter_1 } from "./part-0/chapter-1";
import { chapter as part_0_chapter_2 } from "./part-0/chapter-2";
import { chapter as part_0_chapter_3 } from "./part-0/chapter-3";
import { chapter as part_1_chapter_1 } from "./part-1/chapter-1";
import { chapter as part_1_chapter_2 } from "./part-1/chapter-2";
import { chapter as part_1_chapter_3 } from "./part-1/chapter-3";
import { chapter as part_1_chapter_4 } from "./part-1/chapter-4";
import { chapter as part_2_chapter_1 } from "./part-2/chapter-1";
import { chapter as part_2_chapter_2 } from "./part-2/chapter-2";
import { chapter as part_2_chapter_3 } from "./part-2/chapter-3";
import { chapter as part_3_chapter_1 } from "./part-3/chapter-1";
import { chapter as part_3_chapter_2 } from "./part-3/chapter-2";
import { chapter as part_3_chapter_3 } from "./part-3/chapter-3";
import { chapter as part_3_chapter_4 } from "./part-3/chapter-4";
import { chapter as part_3_chapter_5 } from "./part-3/chapter-5";
import { chapter as part_4_chapter_1 } from "./part-4/chapter-1";
import { chapter as part_4_chapter_2 } from "./part-4/chapter-2";
import { chapter as part_4_chapter_3 } from "./part-4/chapter-3";
import { chapter as part_5_chapter_1 } from "./part-5/chapter-1";
import { chapter as part_5_chapter_2 } from "./part-5/chapter-2";
import { chapter as part_5_chapter_3 } from "./part-5/chapter-3";
import { chapter as part_6_chapter_1 } from "./part-6/chapter-1";
import { chapter as part_6_chapter_2 } from "./part-6/chapter-2";
import { chapter as part_6_chapter_3 } from "./part-6/chapter-3";
import { chapter as part_7_chapter_1 } from "./part-7/chapter-1";
import { chapter as part_7_chapter_2 } from "./part-7/chapter-2";
import { chapter as part_7_chapter_3 } from "./part-7/chapter-3";
import { chapter as part_8_chapter_1 } from "./part-8/chapter-1";
import { chapter as part_8_chapter_2 } from "./part-8/chapter-2";
import { chapter as part_8_chapter_3 } from "./part-8/chapter-3";
import { chapter as part_9_chapter_1 } from "./part-9/chapter-1";
import { chapter as part_9_chapter_2 } from "./part-9/chapter-2";
import { chapter as part_9_chapter_3 } from "./part-9/chapter-3";
import { chapter as part_10_chapter_1 } from "./part-10/chapter-1";
import { chapter as part_10_chapter_2 } from "./part-10/chapter-2";
import { chapter as part_10_chapter_3 } from "./part-10/chapter-3";
import { chapter as part_11_chapter_1 } from "./part-11/chapter-1";
import { chapter as part_11_chapter_2 } from "./part-11/chapter-2";
import { chapter as part_11_chapter_3 } from "./part-11/chapter-3";
import { chapter as part_12_chapter_1 } from "./part-12/chapter-1";
import { chapter as part_12_chapter_2 } from "./part-12/chapter-2";
import { chapter as part_12_chapter_3 } from "./part-12/chapter-3";
import { chapter as part_12_chapter_4 } from "./part-12/chapter-4";

export const chapterPaths: Record<string, string> = {
  "jm-0-1-what-jmeter-is-and-when-to-use-it": "part-0/chapter-1.ts",
  "jm-0-2-installing-jmeter": "part-0/chapter-2.ts",
  "jm-0-3-jmeter-s-execution-model-thread-groups-samplers-": "part-0/chapter-3.ts",
  "jm-1-1-test-plan-structure-and-hierarchy": "part-1/chapter-1.ts",
  "jm-1-2-thread-groups-users-ramp-up-loop-count": "part-1/chapter-2.ts",
  "jm-1-3-samplers-http-request-being-the-main-one": "part-1/chapter-3.ts",
  "jm-1-4-listeners-view-results-tree-summary-report-aggre": "part-1/chapter-4.ts",
  "jm-2-1-recording-a-test-with-the-http-s-test-script-rec": "part-2/chapter-1.ts",
  "jm-2-2-manually-building-an-http-request": "part-2/chapter-2.ts",
  "jm-2-3-running-and-reading-basic-results": "part-2/chapter-3.ts",
  "jm-3-1-http-request-defaults": "part-3/chapter-1.ts",
  "jm-3-2-http-header-manager": "part-3/chapter-2.ts",
  "jm-3-3-http-cookie-manager": "part-3/chapter-3.ts",
  "jm-3-4-csv-data-set-config-parameterization": "part-3/chapter-4.ts",
  "jm-3-5-user-defined-variables": "part-3/chapter-5.ts",
  "jm-4-1-logic-controllers-loop-if-while-runtime-transact": "part-4/chapter-1.ts",
  "jm-4-2-timers-constant-uniform-random-gaussian": "part-4/chapter-2.ts",
  "jm-4-3-assertions-response-duration-size-json": "part-4/chapter-3.ts",
  "jm-5-1-extracting-values-regular-expression-json-and-xp": "part-5/chapter-1.ts",
  "jm-5-2-passing-extracted-values-between-requests": "part-5/chapter-2.ts",
  "jm-5-3-handling-tokens-and-session-ids-login-flows": "part-5/chapter-3.ts",
  "jm-6-1-beanshell-vs-jsr223-groovy-why-groovy-is-preferr": "part-6/chapter-1.ts",
  "jm-6-2-pre-processors-and-post-processors": "part-6/chapter-2.ts",
  "jm-6-3-custom-logic-with-jsr223-sampler": "part-6/chapter-3.ts",
  "jm-7-1-rest-api-testing-json-body-headers-auth": "part-7/chapter-1.ts",
  "jm-7-2-soap-xml-requests": "part-7/chapter-2.ts",
  "jm-7-3-testing-with-authentication-bearer-tokens-basic-": "part-7/chapter-3.ts",
  "jm-8-1-load-vs-stress-vs-spike-vs-soak-testing": "part-8/chapter-1.ts",
  "jm-8-2-designing-realistic-load-profiles-ramp-up-steady": "part-8/chapter-2.ts",
  "jm-8-3-think-time-and-pacing": "part-8/chapter-3.ts",
  "jm-9-1-master-slave-controller-agent-setup": "part-9/chapter-1.ts",
  "jm-9-2-running-tests-from-cli-non-gui-mode": "part-9/chapter-2.ts",
  "jm-9-3-why-gui-mode-is-bad-for-actual-load-generation": "part-9/chapter-3.ts",
  "jm-10-1-key-metrics-response-time-throughput-error-rate-": "part-10/chapter-1.ts",
  "jm-10-2-aggregate-report-vs-summary-report-interpretatio": "part-10/chapter-2.ts",
  "jm-10-3-generating-html-dashboard-reports-cli-e-o": "part-10/chapter-3.ts",
  "jm-11-1-running-jmeter-from-command-line-in-pipelines": "part-11/chapter-1.ts",
  "jm-11-2-integrating-with-jenkins-and-github-actions": "part-11/chapter-2.ts",
  "jm-11-3-failing-builds-on-performance-thresholds": "part-11/chapter-3.ts",
  "jm-12-1-common-errors-troubleshooting": "part-12/chapter-1.ts",
  "jm-12-2-jmeter-vs-other-tools-k6-gatling-locust": "part-12/chapter-2.ts",
  "jm-12-3-best-practices-common-mistakes": "part-12/chapter-3.ts",
  "jm-12-4-useful-plugins": "part-12/chapter-4.ts",
};

export const chapters: ChapterRecord[] = [
  part_0_chapter_1,
  part_0_chapter_2,
  part_0_chapter_3,
  part_1_chapter_1,
  part_1_chapter_2,
  part_1_chapter_3,
  part_1_chapter_4,
  part_2_chapter_1,
  part_2_chapter_2,
  part_2_chapter_3,
  part_3_chapter_1,
  part_3_chapter_2,
  part_3_chapter_3,
  part_3_chapter_4,
  part_3_chapter_5,
  part_4_chapter_1,
  part_4_chapter_2,
  part_4_chapter_3,
  part_5_chapter_1,
  part_5_chapter_2,
  part_5_chapter_3,
  part_6_chapter_1,
  part_6_chapter_2,
  part_6_chapter_3,
  part_7_chapter_1,
  part_7_chapter_2,
  part_7_chapter_3,
  part_8_chapter_1,
  part_8_chapter_2,
  part_8_chapter_3,
  part_9_chapter_1,
  part_9_chapter_2,
  part_9_chapter_3,
  part_10_chapter_1,
  part_10_chapter_2,
  part_10_chapter_3,
  part_11_chapter_1,
  part_11_chapter_2,
  part_11_chapter_3,
  part_12_chapter_1,
  part_12_chapter_2,
  part_12_chapter_3,
  part_12_chapter_4
];
