import type { ChapterRecord } from "../../../types";

/** 23. Page Object Model (POM) */
export const chapter = {
  id: "pw-23-pom",
  title: "23. Page Object Model (POM)",
  minutes: 40,
  level: "intermediate",
  phase: "Part 3 · Test Structure & Framework",
  partName: "Part 3 · Test Structure & Framework",
  overviewText: "Page Object Model pattern: page classes encapsulating locators and actions, BasePage shared utilities, composition over inheritance, and keeping tests readable as user-journey scripts.",
  why: "POM is the standard interview answer for 'how do you maintain a large test suite?' Locator changes touch one class, not 50 tests.",
  when: "Read when the same page interactions appear in 3+ tests or when onboarding teammates to the suite.",
  practical: { app: "HRMS login used by 30 tests", scenario: "Login button renamed from 'Sign In' to 'Log In' — 30 tests break.", pass: "LoginPage.login() method updated once; all tests pass.", fail: "Find-and-replace get_by_role('button', name='Sign In') across 30 files." },
  tools: [],
  contentMarkdown: "## 23. Page Object Model (POM)\n\nPOM centralizes each page's locators and actions into a dedicated class.\nWithout POM, locators get written directly inside test functions — meaning if the UI changes (a button's text, an ID), you have to hunt down and fix every test that touches that element. POM solves this by centralizing each page's locators and actions into one class, so a UI change means fixing one class, not dozens of tests.\nproject/\n├── pages/\n│   ├── base_page.py\n│   ├── login_page.py\n│   └── dashboard_page.py\n├── tests/\n│   ├── test_login.py\n│   └── test_dashboard.py\n└── conftest.py\n\nA BasePage class holds behavior common to every page.\n```python\n# pages/base_page.py\nclass BasePage:\n    def __init__(self, page):\n        self.page = page\n\n    def navigate(self, path):\n        self.page.goto(f\"https://app.example.com{path}\")\n\n    def wait_for_load(self):\n        self.page.wait_for_load_state(\"networkidle\")\n```\n\n\nBasePage.__init__(self, page) stores a reference to the Playwright page object so every method in the class (and its subclasses) can use it. page (Page object, required) is typically passed in from the page pytest fixture. Every page class should inherit from this and call super().__init__(page) to get this shared setup for free — navigation helpers, generic wait logic, anything that would otherwise be duplicated across every single page class.\nIndividual page classes hold their own locators and user-facing methods.\n```python\n# pages/login_page.py\nfrom pages.base_page import BasePage\n\nclass LoginPage(BasePage):\n    def __init__(self, page):\n```\n\n        super().__init__(page)\n```python\n        self.username_input = page.get_by_label(\"Username\")\n        self.password_input = page.get_by_label(\"Password\")\n        self.login_button = page.get_by_role(\"button\", name=\"Log in\")\n\n    def login(self, username, password):\n        self.navigate(\"/login\")\n        self.username_input.fill(username)\n        self.password_input.fill(password)\n        self.login_button.click()\n\n# tests/test_login.py\nfrom pages.login_page import LoginPage\n\ndef test_successful_login(page):\n```\n\n    login_page = LoginPage(page)\n```python\n    login_page.login(\"testuser\", \"testpass\")\n    expect(page.get_by_text(\"Welcome, testuser\")).to_be_visible()\n```\n\n\nLoginPage.login(self, username, password) encapsulates the full \"log in\" user flow as one method call, hiding the individual locator/action steps from the test itself. username and password (both strings, required) are the only things the test needs to supply. The test file itself should read almost like plain English (login_page.login(...)) — if a test file is full of raw locators and .fill()/.click() calls, that's a signal POM isn't being followed consistently, and locator maintenance will end up scattered across test files instead of contained in the page classes where it belongs.",
  customSummary: "## 23. Page Object Model (POM)\n\nPOM centralizes each page's locators/actions into a dedicated class — a UI change means fixing one class, not every test that touches it.\nBasePage holds shared behavior (navigation, generic waits); every page class inherits from it via super().__init__(page).\nPage classes hold locators as attributes and expose plain-English methods (e.g. login_page.login(username, password)).\nA test file full of raw locators/.fill()/.click() calls signals POM isn't being followed — the test should read like plain English instead.",
  exercises: [],
  resourceLinks: [],
  steps: [],
  learn: [],
} as ChapterRecord;
