import { ch } from '../helpers.js'

/** Compact skill manuals — extras pack. */

function miniManual({ id, title, tagline, category, accent, cover, who, outcomes, chapters }) {
  return {
    id,
    title,
    tagline,
    category,
    accent,
    cover,
    duration: '2–5 weeks',
    levelSpan: 'Beginner → Useful',
    who,
    outcomes,
    pace: {
      hoursPerDay: '45–90 min/day',
      recommended: '~3–5 weeks',
      accelerated: '~2 weeks',
      slow: '~6–8 weeks',
    },
    chapters,
  }
}

function stepsFor(topic, bullets, quizQ, quizOpts, answer) {
  return [
    {
      title: 'Key idea',
      body: bullets[0],
      learnMore: bullets[1] || null,
      resources: [{ label: 'Docs', url: bullets.docs || 'https://developer.mozilla.org/', kind: 'Docs' }],
      quiz: { question: quizQ, options: quizOpts, answer },
      doThis: `Write 3 notes on: ${topic}.`,
    },
    {
      title: 'Practice',
      body: bullets[2] || `Practice ${topic} with a tiny project today.`,
      tryIt: {
        prompt: 'Starter',
        code: bullets.code || `# ${topic}\n# try one small experiment`,
        result: 'You have a green or fixable failure — both count.',
      },
      doThis: `Commit one file practicing ${topic}.`,
    },
  ]
}

export const extrasPackManuals = [
  miniManual({
    id: 'react-basics',
    title: 'React Basics',
    tagline: 'Components, props, state, and effects — enough to read and ship simple UIs.',
    category: 'foundations',
    accent: '#0EA5E9',
    cover: 'covers/javascript-cover.png',
    who: 'JS learners who want to build interactive UIs without drowning in the ecosystem.',
    outcomes: ['Build components with props/state', 'Fetch data with effects', 'Lift state without panic'],
    chapters: [
      ch({
        id: 'react-why',
        phase: 'Start',
        level: 'beginner',
        title: 'Why React',
        minutes: 25,
        overview: 'UI as a function of state — the mental model that unlocks everything else.',
        learn: ['Components', 'Declarative UI', 'When not to use React'],
        steps: stepsFor(
          'Why React',
          {
            0: 'React lets you describe UI from state instead of manually mutating the DOM. Components compose like Lego.',
            1: 'You still need HTML/CSS/JS fundamentals. React is not a substitute for the platform.',
            2: 'Create a Vite React app and render a Hello component.',
            code: 'export default function Hello({ name }) {\n  return <h1>Hello {name}</h1>\n}',
            docs: 'https://react.dev/learn',
          },
          'React is primarily about…',
          ['Replacing CSS', 'UI as a function of state', 'Only class components forever', 'Skipping JavaScript'],
          1,
        ),
        checklist: ['Vite app runs', 'One component rendered'],
      }),
      ch({
        id: 'react-state',
        phase: 'Core',
        level: 'beginner',
        title: 'Props & state',
        minutes: 40,
        overview: 'Props in, state inside, events up.',
        learn: ['useState', 'Props', 'Controlled inputs'],
        steps: stepsFor(
          'Props & state',
          {
            0: 'Props are inputs from parents. State is data that changes over time inside a component.',
            1: 'Don’t mutate state — setState with a new value. Controlled inputs keep value in state.',
            2: 'Build a counter and a controlled text field.',
            code: 'const [n, setN] = useState(0)\nreturn <button onClick={() => setN(n + 1)}>{n}</button>',
            docs: 'https://react.dev/reference/react/useState',
          },
          'Updating state should…',
          ['Mutate the array in place', 'Replace with a new value', 'Use document.write', 'Skip renders forever'],
          1,
        ),
        checklist: ['Counter works', 'Input is controlled'],
      }),
      ch({
        id: 'react-effects',
        phase: 'Core',
        level: 'intermediate',
        title: 'Effects & fetching',
        minutes: 45,
        overview: 'useEffect for syncing with the outside world — carefully.',
        learn: ['useEffect', 'Dependency arrays', 'Cleanup'],
        steps: stepsFor(
          'Effects',
          {
            0: 'Effects run after paint to talk to APIs, subscriptions, or the DOM. Dependency arrays decide when they re-run.',
            1: 'Fetching in effects needs ignore flags or abort to avoid race conditions.',
            2: 'Fetch a public JSON API into state and render a list.',
            code: 'useEffect(() => {\n  let on = true\n  fetch(url).then(r => r.json()).then(d => { if (on) setData(d) })\n  return () => { on = false }\n}, [url])',
            docs: 'https://react.dev/reference/react/useEffect',
          },
          'Empty dependency array means…',
          ['Run every keystroke', 'Run once after mount (plus Strict Mode double in dev)', 'Never run', 'Delete the component'],
          1,
        ),
        checklist: ['List from API renders', 'You handled loading state'],
      }),
      ch({
        id: 'react-cp',
        kind: 'checkpoint',
        phase: 'Gate',
        level: 'checkpoint',
        title: 'Checkpoint — React mini app',
        minutes: 60,
        overview: 'Ship a tiny app: list + filter + detail from public API.',
        learn: ['Composition', 'State lift', 'README'],
        steps: [
          {
            title: 'Ship it',
            body: 'Deploy or record a demo of list/filter/detail. README with run steps.',
            quiz: {
              question: 'Checkpoint passes when…',
              options: ['You watched a tutorial', 'App runs and README explains it', 'You bookmarked React docs', 'You used 12 libraries'],
              answer: 1,
            },
            doThis: 'Push to GitHub and link it from your portfolio notes.',
          },
        ],
        checklist: ['Repo public', 'Demo recorded or GIF'],
      }),
    ],
  }),

  miniManual({
    id: 'css-layout',
    title: 'CSS Layout',
    tagline: 'Flexbox, Grid, and responsive layouts that don’t fight you.',
    category: 'design',
    accent: '#7C3AED',
    cover: 'covers/uiux-cover.png',
    who: 'Anyone shipping UI who still guesses at centering.',
    outcomes: ['Flex and Grid confidently', 'Responsive without panic', 'Debug layout with DevTools'],
    chapters: [
      ch({
        id: 'css-box',
        phase: 'Start',
        level: 'beginner',
        title: 'Box model & flow',
        minutes: 30,
        overview: 'Margin, border, padding, content — and normal flow.',
        learn: ['Box model', 'display', 'DevTools'],
        steps: stepsFor(
          'Box model',
          {
            0: 'Every element is a box. box-sizing: border-box makes sizes predictable.',
            1: 'Normal flow stacks block elements; inline sits in lines.',
            2: 'Inspect three elements and sketch their boxes on paper.',
            docs: 'https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model',
          },
          'border-box includes…',
          ['Only content', 'Padding and border in the width', 'Only margin', 'JavaScript'],
          1,
        ),
        checklist: ['You use border-box globally'],
      }),
      ch({
        id: 'css-flex',
        phase: 'Core',
        level: 'beginner',
        title: 'Flexbox',
        minutes: 40,
        overview: 'One-dimensional layouts: rows and columns that distribute space.',
        learn: ['justify/align', 'gap', 'flex'],
        steps: stepsFor(
          'Flexbox',
          {
            0: 'flex container controls direction and distribution; items can grow/shrink.',
            1: 'gap beats margin hacks for spacing between siblings.',
            2: 'Rebuild a nav and a card row with flex only.',
            code: '.row { display: flex; gap: 1rem; justify-content: space-between; }',
            docs: 'https://css-tricks.com/snippets/css/a-guide-to-flexbox/',
          },
          'Main axis is controlled by…',
          ['align-items', 'justify-content (with flex-direction)', 'z-index', 'float'],
          1,
        ),
        checklist: ['Nav + card row without floats'],
      }),
      ch({
        id: 'css-grid',
        phase: 'Core',
        level: 'intermediate',
        title: 'CSS Grid',
        minutes: 45,
        overview: 'Two-dimensional layouts for pages and dashboards.',
        learn: ['tracks', 'areas', 'minmax'],
        steps: stepsFor(
          'Grid',
          {
            0: 'Grid defines rows and columns. Place items by line or area names.',
            1: 'minmax(0, 1fr) prevents stubborn overflow in nested grids.',
            2: 'Build a header/main/sidebar layout with grid-template-areas.',
            code: 'grid-template-areas: "header header" "side main";',
            docs: 'https://css-tricks.com/snippets/css/complete-guide-grid/',
          },
          'fr units represent…',
          ['Fixed pixels only', 'Fractions of free space', 'Font size', 'Flex only'],
          1,
        ),
        checklist: ['Holy grail layout works'],
      }),
    ],
  }),

  miniManual({
    id: 'postman-api',
    title: 'Postman & API Exploration',
    tagline: 'Collections, environments, and assertions before you automate.',
    category: 'automation',
    accent: '#F97316',
    cover: 'covers/api-testing-cover.png',
    who: 'QA and devs who need to explore APIs fast and share requests.',
    outcomes: ['Organize collections', 'Use environments', 'Write basic tests'],
    chapters: [
      ch({
        id: 'pm-intro',
        phase: 'Start',
        level: 'beginner',
        title: 'Requests & collections',
        minutes: 30,
        overview: 'GET/POST in Postman, save into a collection, name things clearly.',
        learn: ['Methods', 'Collections', 'Examples'],
        steps: stepsFor(
          'Postman requests',
          {
            0: 'A collection is a folder of requests you can share and run together.',
            1: 'Save examples of successful responses for teammates.',
            2: 'Hit a public API (e.g. JSONPlaceholder) and save 3 requests.',
            docs: 'https://learning.postman.com/docs/getting-started/overview/',
          },
          'Collections are for…',
          ['Hiding errors', 'Grouping and sharing requests', 'Replacing git', 'Only GraphQL'],
          1,
        ),
        checklist: ['3 requests saved'],
      }),
      ch({
        id: 'pm-env',
        phase: 'Core',
        level: 'beginner',
        title: 'Environments & variables',
        minutes: 35,
        overview: 'baseUrl and tokens per env — never hardcode secrets in shared collections.',
        learn: ['env vars', 'Secrets', '{{baseUrl}}'],
        steps: stepsFor(
          'Environments',
          {
            0: 'Environments swap baseUrl and credentials between local/staging/prod.',
            1: 'Use secret type for tokens. Don’t commit real prod keys.',
            2: 'Create local + staging envs and parameterize URLs.',
            docs: 'https://learning.postman.com/docs/sending-requests/variables/',
          },
          'Best place for an API token…',
          ['In the collection name', 'Environment secret variable', 'A public gist', 'Screenshot'],
          1,
        ),
        checklist: ['Two envs work'],
      }),
      ch({
        id: 'pm-tests',
        phase: 'Core',
        level: 'intermediate',
        title: 'Tests & monitors',
        minutes: 40,
        overview: 'pm.test assertions and collection runner basics.',
        learn: ['pm.test', 'Runner', 'Newman intro'],
        steps: stepsFor(
          'Postman tests',
          {
            0: 'Assert status and JSON fields in the Tests tab so regressions show up in the runner.',
            1: 'Newman runs collections in CI — same idea as Playwright smoke.',
            2: 'Add status + schema-ish asserts to two requests.',
            code: 'pm.test("status 200", () => pm.response.to.have.status(200))',
            docs: 'https://learning.postman.com/docs/writing-scripts/test-scripts/',
          },
          'pm.test runs…',
          ['Only in production browsers', 'After the response returns', 'Instead of sending', 'On CSS only'],
          1,
        ),
        checklist: ['Runner green on happy path'],
      }),
    ],
  }),

  miniManual({
    id: 'excel-data',
    title: 'Spreadsheets for QA & Analysis',
    tagline: 'Filters, pivots, and clean tables — the underrated automation skill.',
    category: 'foundations',
    accent: '#16A34A',
    cover: 'covers/sql-cover.png',
    who: 'Manual QAs and PMs who live in sheets and want fewer mistakes.',
    outcomes: ['Clean tabular data', 'Pivot for insight', 'VLOOKUP/XLOOKUP basics'],
    chapters: [
      ch({
        id: 'sheet-tables',
        phase: 'Start',
        level: 'beginner',
        title: 'Clean tables',
        minutes: 25,
        overview: 'One header row, no merged cells, consistent types.',
        learn: ['Tables', 'Filters', 'Data validation'],
        steps: stepsFor(
          'Clean tables',
          {
            0: 'Merged cells and mixed types break filters and pivots. Use a proper Table object.',
            1: 'Validate dropdowns for status fields used in bug triage.',
            2: 'Convert a messy export into a filtered Table.',
            docs: 'https://support.microsoft.com/excel',
          },
          'Merged cells are…',
          ['Great for pivots', 'Usually harmful for analysis', 'Required for CSV', 'A SQL feature'],
          1,
        ),
        checklist: ['One clean Table'],
      }),
      ch({
        id: 'sheet-pivot',
        phase: 'Core',
        level: 'beginner',
        title: 'Pivot tables',
        minutes: 35,
        overview: 'Summarize defects by severity/component without writing code.',
        learn: ['Pivot', 'Counts', 'Charts'],
        steps: stepsFor(
          'Pivots',
          {
            0: 'Pivots group and aggregate. Perfect for weekly QA reports.',
            1: 'Refresh when source data changes — don’t screenshot stale pivots.',
            2: 'Build a severity × component pivot from sample bug data.',
            docs: 'https://support.microsoft.com/en-us/office/create-a-pivottable-to-analyze-worksheet-data',
          },
          'Pivots need…',
          ['Merged titles', 'Tabular source data', 'Only images', 'No headers'],
          1,
        ),
        checklist: ['Pivot answers one real question'],
      }),
      ch({
        id: 'sheet-lookup',
        phase: 'Core',
        level: 'intermediate',
        title: 'Lookups',
        minutes: 35,
        overview: 'XLOOKUP/VLOOKUP to join id → name without a database.',
        learn: ['XLOOKUP', 'Errors', 'When to use SQL instead'],
        steps: stepsFor(
          'Lookups',
          {
            0: 'Lookups join tables by key. Prefer XLOOKUP when available.',
            1: 'If sheets become a second database, graduate to SQL/real tools.',
            2: 'Join a case-id sheet to an owner sheet.',
            code: '=XLOOKUP(A2, Owners!A:A, Owners!B:B, "missing")',
            docs: 'https://support.microsoft.com/en-us/office/xlookup-function',
          },
          'When sheets hurt…',
          ['Always', 'When multiple writers need integrity + history', 'Never', 'Only on Fridays'],
          1,
        ),
        checklist: ['Working XLOOKUP'],
      }),
    ],
  }),

  miniManual({
    id: 'chatgpt-workflows',
    title: 'ChatGPT Workflows for Learners',
    tagline: 'Repeatable prompts for studying, debugging, and reviewing — without outsourcing your brain.',
    category: 'ai',
    accent: '#0D9488',
    cover: 'covers/prompt-engineering-cover.png',
    who: 'Students and QAs who want AI as a tutor, not a crutch.',
    outcomes: ['Study loops', 'Debug prompts', 'Review checklists'],
    chapters: [
      ch({
        id: 'cg-study',
        phase: 'Start',
        level: 'beginner',
        title: 'Study loop prompts',
        minutes: 25,
        overview: 'Explain → quiz me → correct me. Keep ownership of answers.',
        learn: ['Tutor mode', 'Active recall', 'Limits'],
        steps: stepsFor(
          'Study loops',
          {
            0: 'Ask for a quiz on a chapter, answer first, then reveal. AI is the tutor, you are the student.',
            1: 'Never paste secrets. Never submit AI text as your portfolio voice unedited.',
            2: 'Run a 5-question quiz on yesterday’s chapter.',
            docs: 'https://platform.openai.com/docs/guides/prompt-engineering',
          },
          'Best use of AI for learning…',
          ['Copy final answers blindly', 'Active recall + feedback', 'Skip practice', 'Generate fake experience'],
          1,
        ),
        checklist: ['One quiz session done'],
      }),
      ch({
        id: 'cg-debug',
        phase: 'Core',
        level: 'intermediate',
        title: 'Debug prompts',
        minutes: 30,
        overview: 'Paste error + minimal repro + what you tried.',
        learn: ['Minimal repro', 'Hypothesis', 'Verify'],
        steps: stepsFor(
          'Debug prompts',
          {
            0: 'Structure: expected vs actual, snippet, stack, what you already tried.',
            1: 'Ask for 2 hypotheses ranked, not 20 random fixes.',
            2: 'Debug one real error using that template.',
            docs: 'https://platform.openai.com/docs/guides/prompt-engineering',
          },
          'Include in a debug prompt…',
          ['Only “fix it”', 'Error + repro + attempts', 'Your password', 'Entire node_modules'],
          1,
        ),
        checklist: ['Template saved in notes'],
      }),
      ch({
        id: 'cg-review',
        phase: 'Core',
        level: 'intermediate',
        title: 'Review & critique',
        minutes: 30,
        overview: 'Have AI review your test plan or README against a checklist you own.',
        learn: ['Rubrics', 'Diff review', 'Voice'],
        steps: stepsFor(
          'Review prompts',
          {
            0: 'Give a rubric first (clarity, risks, missing cases). Ask for gaps only.',
            1: 'You decide what to accept — AI doesn’t own quality.',
            2: 'Review your latest README with a 5-point rubric.',
            docs: 'https://platform.openai.com/docs/guides/prompt-engineering',
          },
          'Rubrics help because…',
          ['They waste time', 'They focus critique on what you care about', 'They replace tests', 'They hide bugs'],
          1,
        ),
        checklist: ['Rubric reused twice'],
      }),
    ],
  }),

  miniManual({
    id: 'linux-shell-daily',
    title: 'Linux Shell Daily',
    tagline: 'cd, pipes, grep, and logs — the everyday CLI for QA and devs.',
    category: 'ops',
    accent: '#1D4ED8',
    cover: 'covers/git-cover.png',
    who: 'Anyone scared of the terminal who needs it for CI logs and servers.',
    outcomes: ['Navigate filesystem', 'Pipe and grep logs', 'Read exit codes'],
    chapters: [
      ch({
        id: 'sh-nav',
        phase: 'Start',
        level: 'beginner',
        title: 'Navigation & files',
        minutes: 25,
        overview: 'pwd, ls, cd, mkdir, touch, mv, cp, rm (carefully).',
        learn: ['Paths', 'Listing', 'Safety'],
        steps: stepsFor(
          'Shell navigation',
          {
            0: 'The shell is a text UI to the filesystem. Relative vs absolute paths matter.',
            1: 'rm -rf is powerful — prefer trash tools until you’re sure.',
            2: 'Create a practice folder, move files, list with ls -la.',
            code: 'pwd\nls -la\nmkdir practice && cd practice',
            docs: 'https://linuxcommand.org/',
          },
          'pwd shows…',
          ['Python version', 'Current directory', 'Git branch only', 'CPU temp'],
          1,
        ),
        checklist: ['Comfortable cd/ls'],
      }),
      ch({
        id: 'sh-pipes',
        phase: 'Core',
        level: 'beginner',
        title: 'Pipes & grep',
        minutes: 35,
        overview: 'Connect commands; find needles in logs.',
        learn: ['|', 'grep', 'head/tail'],
        steps: stepsFor(
          'Pipes',
          {
            0: 'Pipes send stdout of one command to stdin of the next.',
            1: 'grep -i error app.log | tail -n 20 is a QA superpower.',
            2: 'Download a sample log and extract ERROR lines.',
            code: 'cat app.log | grep -i error | tail -n 20',
            docs: 'https://www.gnu.org/software/grep/manual/',
          },
          'grep is for…',
          ['Editing images', 'Searching text patterns', 'Compiling C', 'Deploying k8s only'],
          1,
        ),
        checklist: ['Found errors in a log'],
      }),
      ch({
        id: 'sh-exit',
        phase: 'Core',
        level: 'intermediate',
        title: 'Exit codes & scripts',
        minutes: 35,
        overview: '$? and simple bash scripts for repetitive checks.',
        learn: ['Exit codes', 'set -e', 'Tiny scripts'],
        steps: stepsFor(
          'Exit codes',
          {
            0: '0 means success; non-zero means failure — CI depends on this.',
            1: 'set -euo pipefail makes scripts fail loudly.',
            2: 'Write a 10-line script that greps a log and exits 1 if errors exist.',
            code: '#!/usr/bin/env bash\nset -euo pipefail\ngrep -q ERROR "$1" && exit 1 || exit 0',
            docs: 'https://tldp.org/LDP/abs/html/',
          },
          'Exit code 0 usually means…',
          ['Crash', 'Success', 'Permission denied', 'Network down'],
          1,
        ),
        checklist: ['Script executable and tested'],
      }),
    ],
  }),
]
