import { ch, r } from '../helpers.js'

const md = (...lines) => lines.join('\n')

/** PART 1 — Testing by Level. Full how-tos for unit, integration, system, and UAT. */
export const testingLevelsManual = {
  id: 'testing-by-level',
  title: 'Testing by Level',
  tagline:
    'The four levels that carry an application from a single function to a signed-off release — each with the free tools teams actually use.',
  category: 'quality',
  accent: '#0F766E',
  cover: 'covers/test-automation-cover.png',
  duration: '2–3 weeks',
  levelSpan: 'Beginner → Intermediate',
  who: 'QA and builders who need a clear map of unit, integration, system, and acceptance testing — and which tools belong on each rung.',
  outcomes: [
    'Name the four testing levels and what each one is allowed to miss',
    'Write and run unit, integration, and system tests with free tools',
    'Run a UAT cycle with business scenarios, TestRail, Jira, and sign-off',
  ],
  chapters: [
    ch({
      id: 'tbl-guide',
      kind: 'guide',
      phase: 'Part 1 · Testing by Level',
      level: 'beginner',
      title: 'The four rungs',
      minutes: 15,
      durationLabel: 'Day 0',
      overview:
        'Part 1 of the Software Testing Reference. Tests are not a pile of cases — they are levels. A unit test cannot sign off a release. A UAT session cannot prove a function is correct in isolation. This path walks unit, integration, system, and acceptance testing, with the free tools teams actually use and how those tools stack up.',
      learn: ['Unit vs integration vs system vs UAT', 'What each level is allowed to miss', 'Free-tool posture'],
      steps: [
        {
          title: 'Read the stack bottom-up',
          body: 'Unit tests the smallest piece of code in isolation. Integration verifies that combined modules keep their contracts. System tests the fully wired product the way a user would. Acceptance (UAT) is the business gate: does this fit how the work actually happens?',
          items: [
            'Unit — a function, method, or class; dependencies mocked',
            'Integration — interfaces, data flow, and contracts between modules',
            'System — black-box, end to end, real user path',
            'Acceptance — stakeholders confirm fitness for the business, not just the spec',
          ],
          doThis: 'Write one sentence for each level using a product you know. If two sentences sound the same, you do not have the distinction yet.',
        },
        {
          title: 'Tools are not levels',
          body: 'PyTest can run unit, API, and UI tests. Selenium can sit at integration or system. The level is the question you are asking, not the logo on the runner.',
          tip: 'If a tool can do three levels, still pick one question per test. Mixed-purpose suites rot fast.',
        },
      ],
      checklist: ['I can name the four levels in order', 'I can say what a unit test is not allowed to prove'],
    }),

    ch({
      id: 'tbl-unit',
      phase: 'Part 1 · Testing by Level',
      level: 'beginner',
      title: 'Unit Testing',
      minutes: 50,
      overview:
        'Unit testing is the practice of testing the smallest individual pieces of a software application in complete isolation from the rest of the system. A "unit" is typically a single function, method, or class. The goal is to verify that each unit of code does exactly what it is supposed to do — given a specific input, it produces the expected output. Unit tests are written and run by developers, usually at the same time they write the code itself. Because each unit is tested in isolation, any external dependencies like databases, APIs, or file systems are replaced with fake versions called mocks or stubs. This means the test is only checking the logic of that one piece of code, nothing else. Unit testing sits at the very bottom of the testing pyramid — it is the foundation on which all other testing types are built. In modern software development, unit tests are run automatically every time a developer pushes code, catching bugs within seconds of them being introduced.',
      learn: ['Isolation and mocks', 'JUnit', 'PyTest', 'Jest', 'When unit tests belong in the PR'],
      steps: [
        {
          title: 'Why it Matters',
          body: 'If unit testing is skipped, bugs that could have been caught in seconds during development instead travel all the way to integration testing, system testing, or worse — production. Finding a bug at the unit level takes minutes to fix. Finding the same bug in production takes hours of debugging across multiple systems, and may have already caused data corruption or customer-facing failures. Unit tests also serve as living documentation — they show exactly how each function is expected to behave, which is invaluable when a new developer joins the team or when code is refactored months later.',
        },
        {
          title: 'Free tools',
          body: '1. JUnit (Java) — 2. PyTest (Python) — 3. Jest (JavaScript).',
        },
        {
          title: 'JUnit',
          body: md(
            'JUnit is the most widely used unit testing framework for Java applications. It was originally created by Kent Beck and Erich Gamma — two of the most influential figures in software engineering — and is now maintained as JUnit 5, also called JUnit Jupiter. JUnit provides annotations that tell the framework exactly which methods are tests, how to set up before each test, and how to clean up after. The `@Test` annotation marks a method as a test case. `@BeforeEach` runs setup code before every test. `@AfterEach` runs cleanup after every test. `@BeforeAll` and `@AfterAll` run once for the entire test class. JUnit integrates directly into build tools like Maven and Gradle, meaning your entire test suite runs automatically as part of the build process. It also integrates into IDEs like IntelliJ IDEA and Eclipse, giving developers a green and red pass/fail indicator right inside their editor without switching to a terminal. JUnit 5 introduced a modular architecture — JUnit Platform (the launcher), JUnit Jupiter (the new API), and JUnit Vintage (backwards compatibility with JUnit 4) — making it flexible enough for both legacy and modern Java projects.',
            '',
            '#### Step 1 — Add JUnit to your Maven project',
            '',
            'In `pom.xml`:',
            '',
            '```',
            '<dependency>',
            '    <groupId>org.junit.jupiter</groupId>',
            '    <artifactId>junit-jupiter</artifactId>',
            '    <version>5.10.0</version>',
            '    <scope>test</scope>',
            '</dependency>',
            '```',
            '',
            '#### Step 2 — Write the class you want to test',
            '',
            'Create `Calculator.java`:',
            '',
            '```',
            'public class Calculator {',
            '    public int add(int a, int b) {',
            '        return a + b;',
            '    }',
            '',
            '    public int subtract(int a, int b) {',
            '        return a - b;',
            '    }',
            '',
            '    public double divide(int a, int b) {',
            '        if (b == 0) throw new ArithmeticException("Cannot divide by zero");',
            '        return (double) a / b;',
            '    }',
            '}',
            '```',
            '',
            '#### Step 3 — Create the test class',
            '',
            'Create `CalculatorTest.java` in `src/test/java`:',
            '',
            '```',
            'import org.junit.jupiter.api.*;',
            'import static org.junit.jupiter.api.Assertions.*;',
            '',
            'class CalculatorTest {',
            '',
            '    Calculator calculator;',
            '',
            '    @BeforeEach',
            '    void setUp() {',
            '        calculator = new Calculator();  // fresh instance before each test',
            '    }',
            '',
            '    @Test',
            '    void testAddTwoPositiveNumbers() {',
            '        int result = calculator.add(3, 5);',
            '        assertEquals(8, result);',
            '    }',
            '',
            '    @Test',
            '    void testSubtract() {',
            '        int result = calculator.subtract(10, 4);',
            '        assertEquals(6, result);',
            '    }',
            '',
            '    @Test',
            '    void testDivideNormal() {',
            '        double result = calculator.divide(10, 2);',
            '        assertEquals(5.0, result);',
            '    }',
            '',
            '    @Test',
            '    void testDivideByZeroThrowsException() {',
            '        ArithmeticException exception = assertThrows(',
            '            ArithmeticException.class,',
            '            () -> calculator.divide(10, 0)',
            '        );',
            '        assertEquals("Cannot divide by zero", exception.getMessage());',
            '    }',
            '',
            '    @Test',
            '    @DisplayName("Adding negative numbers should return correct negative sum")',
            '    void testAddNegativeNumbers() {',
            '        assertEquals(-8, calculator.add(-3, -5));',
            '    }',
            '}',
            '```',
            '',
            '#### Step 4 — Run tests via Maven',
            '',
            '```',
            'mvn test',
            '```',
            '',
            'Output:',
            '',
            '```',
            '[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0',
            '[INFO] BUILD SUCCESS',
            '```',
            '',
            '#### Step 5 — Run with parameterized inputs',
            '',
            '```',
            '@ParameterizedTest',
            '@CsvSource({',
            '    "2, 3, 5",',
            '    "0, 0, 0",',
            '    "-1, 1, 0",',
            '    "100, 200, 300"',
            '})',
            'void testAddMultipleCases(int a, int b, int expected) {',
            '    assertEquals(expected, calculator.add(a, b));',
            '}',
            '```',
            '',
            '#### Step 6 — Group tests with @Nested',
            '',
            '```',
            '@Nested',
            '@DisplayName("Division tests")',
            'class DivisionTests {',
            '',
            '    @Test',
            '    void dividePositiveNumbers() {',
            '        assertEquals(2.5, calculator.divide(5, 2));',
            '    }',
            '',
            '    @Test',
            '    void divideByZero() {',
            '        assertThrows(ArithmeticException.class, () -> calculator.divide(5, 0));',
            '    }',
            '}',
            '```',
            '',
            '#### Step 7 — View results in IntelliJ',
            '',
            'Right-click the test class → Run. The left panel shows a green tick for each passing test and a red cross for each failure, with the exact assertion that failed and the actual vs expected values.',
          ),
          items: [
            'Advantage: Deep IDE integration — pass/fail shows inline in IntelliJ and Eclipse',
            'Advantage: Runs automatically as part of the Maven/Gradle build, no extra wiring',
            'Advantage: Modular Platform/Jupiter/Vintage design supports legacy and modern code side by side',
            'Advantage: Rich annotation model (@Nested, @ParameterizedTest) keeps large suites organized',
            'Limitation: Java-only — no use outside the JVM ecosystem',
            'Limitation: More boilerplate than PyTest or Jest for the same test',
            'Limitation: No built-in mocking — Mockito or similar has to be added separately',
            'Limitation: Parameterized data sources need extra annotations most teams have to look up each time',
          ],
          resources: [{ label: 'junit.org', url: 'https://junit.org', kind: 'Docs' }],
        },
        {
          title: 'PyTest',
          body: md(
            "PyTest is the most popular testing framework for Python. Unlike Python's built-in `unittest` module, PyTest requires almost no boilerplate — you write a plain function starting with `test_` and PyTest finds and runs it automatically without any class inheritance or special imports. PyTest's real power comes from its fixture system — reusable setup and teardown blocks that can be shared across hundreds of tests with a single line. Its parameterization feature lets you run the same test with dozens of different inputs without duplicating code. PyTest also has one of the richest plugin ecosystems in any testing framework — `pytest-cov` for coverage, `pytest-xdist` for parallel execution, `pytest-html` for HTML reports, `pytest-mock` for mocking, and `pytest-playwright` for browser automation. When a test fails, PyTest produces some of the clearest, most readable failure messages in any testing framework — showing the exact values on both sides of a failed assertion, the full call stack, and the local variables at the point of failure. It is used not just for unit testing but for integration, API, and UI testing as well, making it the single framework that can cover an entire Python testing strategy.",
            '',
            '#### Step 1 — Install PyTest',
            '',
            '```',
            'pip install pytest pytest-cov',
            'pytest --version',
            '```',
            '',
            '#### Step 2 — Write the function to test',
            '',
            'Create `salary.py`:',
            '',
            '```',
            'def calculate_gross_salary(basic, allowances, overtime_hours, overtime_rate):',
            '    if basic < 0:',
            '        raise ValueError("Basic salary cannot be negative")',
            '    overtime_pay = overtime_hours * overtime_rate',
            '    return basic + allowances + overtime_pay',
            '',
            'def calculate_tax(gross_salary):',
            '    if gross_salary <= 500000:',
            '        return gross_salary * 0.01',
            '    elif gross_salary <= 700000:',
            '        return gross_salary * 0.10',
            '    else:',
            '        return gross_salary * 0.20',
            '```',
            '',
            '#### Step 3 — Write the test file',
            '',
            'Create `test_salary.py`:',
            '',
            '```',
            'import pytest',
            'from salary import calculate_gross_salary, calculate_tax',
            '',
            'def test_gross_salary_with_overtime():',
            '    result = calculate_gross_salary(50000, 10000, 5, 500)',
            '    assert result == 62500',
            '',
            'def test_gross_salary_no_overtime():',
            '    result = calculate_gross_salary(50000, 10000, 0, 500)',
            '    assert result == 60000',
            '',
            'def test_negative_basic_raises_error():',
            '    with pytest.raises(ValueError, match="Basic salary cannot be negative"):',
            '        calculate_gross_salary(-1000, 5000, 0, 0)',
            '',
            'def test_tax_lowest_slab():',
            '    assert calculate_tax(400000) == 4000.0',
            '',
            'def test_tax_middle_slab():',
            '    assert calculate_tax(600000) == 60000.0',
            '',
            'def test_tax_highest_slab():',
            '    assert calculate_tax(800000) == 160000.0',
            '```',
            '',
            '#### Step 4 — Run the tests',
            '',
            '```',
            'pytest test_salary.py -v',
            '```',
            '',
            '#### Step 5 — Use fixtures for reusable setup',
            '',
            '```',
            '@pytest.fixture',
            'def employee_data():',
            '    return {',
            '        "basic": 50000,',
            '        "allowances": 10000,',
            '        "overtime_hours": 5,',
            '        "overtime_rate": 500',
            '    }',
            '',
            'def test_gross_with_fixture(employee_data):',
            '    result = calculate_gross_salary(**employee_data)',
            '    assert result == 62500',
            '```',
            '',
            '#### Step 6 — Parameterize for multiple scenarios',
            '',
            '```',
            '@pytest.mark.parametrize("gross, expected_tax", [',
            '    (400000, 4000.0),',
            '    (600000, 60000.0),',
            '    (800000, 160000.0),',
            '    (500000, 5000.0),',
            '])',
            'def test_tax_slabs(gross, expected_tax):',
            '    assert calculate_tax(gross) == expected_tax',
            '```',
            '',
            '#### Step 7 — Run with coverage report',
            '',
            '```',
            'pytest test_salary.py --cov=salary --cov-report=term-missing -v',
            '```',
          ),
          items: [
            'Advantage: Almost zero boilerplate — a plain function is a valid test',
            'Advantage: One of the richest plugin ecosystems (coverage, parallel runs, HTML reports, mocking, Playwright)',
            'Advantage: Same framework can cover unit, API/integration, and UI tests',
            'Advantage: Failure output shows both sides of a failed assertion clearly',
            'Limitation: Python-only',
            'Limitation: Heavy plugin use can make a suite fragile if plugin versions drift',
            'Limitation: Fixture scoping (function/class/module/session) has a learning curve',
            'Limitation: Loose structure means teams need their own conventions to stay consistent',
          ],
          resources: [{ label: 'pytest.org', url: 'https://pytest.org', kind: 'Docs' }],
        },
        {
          title: 'Jest',
          body: md(
            "Jest is the standard unit testing framework for JavaScript and TypeScript, created and maintained by Meta (Facebook). It was built with one guiding principle — zero configuration. You install it, point it at your files, and it works. Jest includes everything a JavaScript developer needs in a single package — a test runner, an assertion library, a mocking system, code coverage reporting, and snapshot testing — without needing to install and configure multiple separate libraries the way older JavaScript testing setups required. Jest runs tests in parallel by default using worker threads, making large test suites significantly faster. Its watch mode is a developer favourite — it monitors your files for changes and automatically re-runs only the affected tests, giving you instant feedback as you write code. Jest's mocking system is particularly powerful — you can mock entire modules, individual functions, timers, and even HTTP calls with a single line of code. Snapshot testing, one of Jest's most distinctive features, lets you capture the rendered output of a UI component and automatically compare it on every future run, catching unintended visual changes without writing explicit assertions. Jest works out of the box with React (create-react-app includes it by default), Node.js, TypeScript (with `ts-jest`), and most modern JavaScript frameworks.",
            '',
            '#### Step 1 — Initialize a Node project and install Jest',
            '',
            '```',
            'npm init -y',
            'npm install --save-dev jest',
            '```',
            '',
            'Add to `package.json`:',
            '',
            '```',
            '{',
            '  "scripts": {',
            '    "test": "jest",',
            '    "test:coverage": "jest --coverage",',
            '    "test:watch": "jest --watch"',
            '  }',
            '}',
            '```',
            '',
            '#### Step 2 — Write the function to test',
            '',
            'Create `leaveCalculator.js`:',
            '',
            '```',
            'function calculateRemainingLeave(totalDays, usedDays) {',
            '    if (usedDays > totalDays) {',
            '        throw new Error("Used days cannot exceed total allocated days");',
            '    }',
            '    return totalDays - usedDays;',
            '}',
            '',
            'function isLeaveEligible(joiningDate, requestDate) {',
            '    const joining = new Date(joiningDate);',
            '    const request = new Date(requestDate);',
            '    const diffMonths = (request - joining) / (1000 * 60 * 60 * 24 * 30);',
            '    return diffMonths >= 3;  // must have worked 3 months to be eligible',
            '}',
            '',
            'module.exports = { calculateRemainingLeave, isLeaveEligible };',
            '```',
            '',
            '#### Step 3 — Write the test file',
            '',
            'Create `leaveCalculator.test.js`:',
            '',
            '```',
            "const { calculateRemainingLeave, isLeaveEligible } = require('./leaveCalculator');",
            '',
            "describe('calculateRemainingLeave', () => {",
            '',
            "    test('returns correct remaining days', () => {",
            '        expect(calculateRemainingLeave(20, 5)).toBe(15);',
            '    });',
            '',
            "    test('returns zero when all leave is used', () => {",
            '        expect(calculateRemainingLeave(20, 20)).toBe(0);',
            '    });',
            '',
            "    test('throws error when used days exceed total', () => {",
            '        expect(() => {',
            '            calculateRemainingLeave(10, 15);',
            '        }).toThrow("Used days cannot exceed total allocated days");',
            '    });',
            '});',
            '',
            "describe('isLeaveEligible', () => {",
            '',
            "    test('returns true after 3 months of joining', () => {",
            "        expect(isLeaveEligible('2025-01-01', '2025-04-15')).toBe(true);",
            '    });',
            '',
            "    test('returns false before 3 months of joining', () => {",
            "        expect(isLeaveEligible('2025-01-01', '2025-02-01')).toBe(false);",
            '    });',
            '});',
            '```',
            '',
            '#### Step 4 — Run the tests',
            '',
            '```',
            'npm test',
            '```',
            '',
            '#### Step 5 — Mock a dependency',
            '',
            '```',
            "// Mock an external API call inside a function",
            "jest.mock('./api', () => ({",
            '    getEmployeeById: jest.fn().mockResolvedValue({',
            '        id: 1,',
            '        name: "Simran",',
            '        leaveBalance: 12',
            '    })',
            '}));',
            '',
            "test('fetches employee leave balance', async () => {",
            "    const { getEmployeeById } = require('./api');",
            '    const employee = await getEmployeeById(1);',
            '    expect(employee.leaveBalance).toBe(12);',
            '    expect(getEmployeeById).toHaveBeenCalledWith(1);',
            '});',
            '```',
            '',
            '#### Step 6 — Run with coverage',
            '',
            '```',
            'npm run test:coverage',
            '```',
            '',
            '#### Step 7 — Run in watch mode during development',
            '',
            '```',
            'npm run test:watch',
            '```',
            '',
            'Jest watches your files. Every time you save a change, only the affected tests re-run instantly — no manual re-run needed.',
          ),
          items: [
            'Advantage: Zero-config — install and run, no separate assertion or mocking library needed',
            'Advantage: Parallel test execution by default via worker threads',
            'Advantage: Watch mode re-runs only affected tests for instant feedback',
            'Advantage: Snapshot testing catches unintended UI changes without writing new assertions',
            'Limitation: Snapshot tests get rubber-stamped if diffs are not actually reviewed',
            'Limitation: Config gets complex fast for ESM or monorepo setups',
            'Limitation: Slower cold-start on very large suites than newer runners like Vitest',
            'Limitation: Full TypeScript support needs the ts-jest wrapper, not native',
          ],
          resources: [{ label: 'jestjs.io', url: 'https://jestjs.io', kind: 'Docs' }],
          tip: 'Review every snapshot diff. Unreviewed snapshots are not tests.',
        },
        {
          title: 'Practical Example',
          body: md(
            'Application: HRMS — Tax deduction logic.',
            '',
            'Scenario: The finance team reports that employee net salaries look wrong after a recent code change. The unit tests for the tax calculation function immediately pinpoint the broken slab logic — the developer accidentally used `<` instead of `<=` in the boundary condition for the 10% slab, causing employees earning exactly Rs 500,000 to be taxed at 20% instead of 10%.',
            '',
            'Pass: `calculate_tax(500000)` returns `5000.0` (1% slab applied correctly).',
            '',
            'Fail: `calculate_tax(500000)` returns `100000.0` — boundary condition bug caught instantly by unit test before it reaches payroll.',
          ),
        },
        {
          title: 'Advantages',
          items: [
            'Catches bugs within seconds of code being written — the fastest feedback loop in all of testing',
            'Tests run in milliseconds — hundreds of tests complete in under a second',
            'Forces developers to write modular, clean, single-responsibility functions',
            'Acts as living documentation — tests show exactly how every function is expected to behave',
            'Makes refactoring safe — change internal implementation confidently as long as tests pass',
            'All three tools integrate with CI/CD — tests run automatically on every code push',
          ],
        },
        {
          title: 'Limitations',
          items: [
            'Only tests individual units — does not catch bugs that emerge when components interact',
            'Mocks give false confidence — the real database or API may behave very differently from the mock',
            'Poor unit tests (testing implementation instead of behaviour) break on every refactor',
            'High coverage percentage does not mean all bugs are caught — it only measures lines executed',
            'Cannot test UI, user flows, network calls, or any real-world integration',
          ],
        },
        {
          title: 'When to Use it in a Project',
          body: 'Unit tests should be written at the same time as the code — not after. Every function or method added in a sprint should have corresponding unit tests in the same pull request. They run on every commit in the CI/CD pipeline and must pass before code is merged. They are the cheapest, fastest safety net in software development and should never be skipped regardless of deadline pressure.',
        },
      ],
      checklist: [
        'I can explain isolation vs a running system',
        'I ran or read one JUnit, PyTest, or Jest example',
        'I listed one limitation of that runner I will have to live with',
      ],
      practice: {
        title: 'One unit test',
        brief: 'Write one isolated test for a pure function. No network, no database, no UI.',
      },
      links: [
        { name: 'JUnit', url: 'https://junit.org', kind: 'doc' },
        { name: 'PyTest', url: 'https://pytest.org', kind: 'doc' },
        { name: 'Jest', url: 'https://jestjs.io', kind: 'doc' },
      ],
    }),

    ch({
      id: 'tbl-integration',
      phase: 'Part 1 · Testing by Level',
      level: 'beginner',
      title: 'Integration Testing',
      minutes: 50,
      overview:
        'Integration testing verifies that multiple individual units or components work correctly when they are combined together. While unit testing checks each piece in isolation, integration testing checks the connections between pieces — does the login module correctly communicate with the user database? Does the leave request service correctly update the leave balance and trigger a manager notification? Does the API return the right data structure when the frontend calls it? Integration tests are run after unit tests pass and before full system testing begins. They expose a category of bugs that unit tests are structurally incapable of finding — bugs that live in the interfaces, contracts, and data flows between components. In a real HRMS system, a unit test confirms that the leave balance calculation function works correctly in isolation. Only an integration test confirms that when an employee submits a leave request through the actual API, the correct balance is deducted in the actual database and the manager actually receives the notification through the actual notification service.',
      learn: ['Contracts and data flow', 'Postman', 'PyTest for APIs', 'Selenium at this level'],
      steps: [
        {
          title: 'Why it Matters',
          body: 'The most damaging bugs in real applications almost always live at integration points — API response shapes that do not match what the frontend expects, database queries that return unexpected null values, authentication tokens that expire mid-session, event listeners that drop messages under load. These bugs are completely invisible to unit tests because unit tests mock all external dependencies. Skipping integration testing means these interface bugs survive all the way to system testing or production, where finding and fixing them is dramatically more expensive and disruptive.',
        },
        {
          title: 'Free tools',
          body: '1. Postman — 2. PyTest (for API integration) — 3. Selenium.',
        },
        {
          title: 'Postman',
          body: md(
            "Postman is the world's most widely used API platform, originally created in 2012 by Abhinav Asthana as a Chrome extension and now a standalone desktop and web application used by over 25 million developers and testers. At its core, Postman is an HTTP client — it lets you construct and send any kind of HTTP request (GET, POST, PUT, PATCH, DELETE) to any API endpoint and inspect every detail of the response including status code, headers, body, cookies, and response time. For integration testing specifically, Postman's real power comes from its Collections feature — you group related API requests into a collection and run them in sequence, passing data between them using variables. For example, a login request extracts the authentication token from the response and stores it as a variable, and every subsequent request automatically uses that token in its Authorization header. Each request has a Tests tab where you write JavaScript assertions that automatically validate the response — checking status codes, response structure, data types, and business logic values. The Newman CLI tool lets you run entire Postman collections from the command line or CI/CD pipeline without opening the GUI, producing JUnit-compatible XML reports that integrate with Jenkins, GitHub Actions, or any other build system. Postman also supports environment files — you define base URLs and credentials for dev, staging, and production separately, and switch between them with one click without changing any request.",
            '',
            '#### Step 1 — Download and install Postman',
            '',
            'Go to `postman.com/downloads`, download the desktop app for your OS, and create a free account. The free tier supports unlimited collections and requests.',
            '',
            '#### Step 2 — Create a new Collection',
            '',
            'Click "New" → "Collection". Name it `HRMS Integration Tests`. Collections are the main organizational unit — think of them as a test suite.',
            '',
            '#### Step 3 — Set up a Collection Variable for the base URL',
            '',
            'Click the collection name → Variables tab. Add variable `base_url` with initial value `https://staging.hrms-app.com/api`. Now every request uses `{{base_url}}` instead of the full URL — change it once to switch environments.',
            '',
            '#### Step 4 — Add a login request',
            '',
            'Inside the collection, click "Add request": Name `01 - Login`, Method `POST`, URL `{{base_url}}/auth/login`. Body → raw → JSON:',
            '',
            '```',
            '{',
            '    "email": "hr@company.com",',
            '    "password": "Admin@1234"',
            '}',
            '```',
            '',
            'In the Tests tab:',
            '',
            '```',
            'pm.test("Login returns 200", function () {',
            '    pm.response.to.have.status(200);',
            '});',
            '',
            'pm.test("Response contains auth token", function () {',
            '    const body = pm.response.json();',
            '    pm.expect(body).to.have.property("token");',
            '    pm.expect(body.token).to.be.a("string").and.not.empty;',
            '});',
            '',
            'pm.test("Response contains user info", function () {',
            '    const body = pm.response.json();',
            '    pm.expect(body.user).to.have.property("id");',
            '    pm.expect(body.user.role).to.equal("HR_ADMIN");',
            '});',
            '',
            '// Pass token to all subsequent requests',
            'pm.collectionVariables.set("auth_token", pm.response.json().token);',
            'pm.collectionVariables.set("user_id", pm.response.json().user.id);',
            '```',
            '',
            '#### Step 5 — Add a chained request using the token',
            '',
            'Add request `02 - Get Employee List`, Method `GET`, URL `{{base_url}}/employees`, Header `Authorization: Bearer {{auth_token}}`.',
            '',
            '```',
            'pm.test("Returns 200", () => pm.response.to.have.status(200));',
            '',
            'pm.test("Returns array of employees", function () {',
            '    const body = pm.response.json();',
            '    pm.expect(body.data).to.be.an("array");',
            '    pm.expect(body.data.length).to.be.above(0);',
            '});',
            '',
            'pm.test("Each employee has required fields", function () {',
            '    const employees = pm.response.json().data;',
            '    employees.forEach(emp => {',
            '        pm.expect(emp).to.have.property("id");',
            '        pm.expect(emp).to.have.property("name");',
            '        pm.expect(emp).to.have.property("department");',
            '    });',
            '});',
            '',
            'pm.collectionVariables.set("employee_id", pm.response.json().data[0].id);',
            '```',
            '',
            '#### Step 6 — Run the full collection',
            '',
            'Click the collection name → "Run collection". The Collection Runner executes all requests in order, shows pass/fail for every assertion, and displays a summary at the end.',
            '',
            '#### Step 7 — Run from terminal using Newman',
            '',
            '```',
            'npm install -g newman newman-reporter-htmlextra',
            'newman run HRMS_Integration_Tests.json \\',
            '    -e staging_environment.json \\',
            '    --reporters cli,htmlextra \\',
            '    --reporter-htmlextra-export reports/integration_report.html',
            '```',
          ),
          items: [
            'Advantage: GUI-based, so non-developers can build and run requests without code',
            'Advantage: Collections + variables make chaining requests (e.g. login → use token) simple',
            'Advantage: Newman CLI runs full collections in CI/CD with JUnit-style reports',
            'Advantage: One-click environment switching between dev, staging, and production',
            'Limitation: Test scripts are JavaScript-only inside the Tests tab — awkward for complex logic',
            'Limitation: Large collections get hard to navigate and maintain over time',
            'Limitation: Free tier has workspace and monthly request limits at scale',
            'Limitation: Not built for direct database checks — HTTP only',
          ],
          resources: [{ label: 'postman.com', url: 'https://postman.com', kind: 'Docs' }],
        },
        {
          title: 'PyTest for API Integration',
          body: md(
            "PyTest is not just a unit testing framework — used with the `requests` library it becomes a powerful API integration testing tool. The advantage over Postman is that Python test code can include complex logic, data manipulation, database queries, and external validations that Postman's JavaScript test scripts cannot easily handle. PyTest fixtures handle authentication once and share the token across all tests in a session. Parameterization runs the same API test against multiple data sets. The `pytest-html` plugin generates professional HTML reports. For teams already using Python for their Playwright UI tests, using PyTest for API integration tests means one language, one framework, one CI/CD configuration for all testing layers.",
            '',
            '#### Step 1 — Install dependencies',
            '',
            '```',
            'pip install pytest requests pytest-html',
            '```',
            '',
            '#### Step 2 — Create conftest.py with auth fixture',
            '',
            '```',
            'import pytest',
            'import requests',
            '',
            'BASE_URL = "https://staging.hrms-app.com/api"',
            '',
            '@pytest.fixture(scope="session")',
            'def auth_token():',
            '    response = requests.post(f"{BASE_URL}/auth/login", json={',
            '        "email": "hr@company.com",',
            '        "password": "Admin@1234"',
            '    })',
            '    assert response.status_code == 200',
            '    return response.json()["token"]',
            '',
            '@pytest.fixture(scope="session")',
            'def api_headers(auth_token):',
            '    return {',
            '        "Authorization": f"Bearer {auth_token}",',
            '        "Content-Type": "application/json"',
            '    }',
            '```',
            '',
            '#### Step 3 — Write integration tests',
            '',
            '```',
            'import requests',
            'import pytest',
            '',
            'BASE_URL = "https://staging.hrms-app.com/api"',
            '',
            'def test_get_employees_returns_list(api_headers):',
            '    response = requests.get(f"{BASE_URL}/employees", headers=api_headers)',
            '    assert response.status_code == 200',
            '    data = response.json()',
            '    assert isinstance(data["data"], list)',
            '    assert len(data["data"]) > 0',
            '',
            'def test_employee_has_required_fields(api_headers):',
            '    response = requests.get(f"{BASE_URL}/employees", headers=api_headers)',
            '    employee = response.json()["data"][0]',
            '    assert "id" in employee',
            '    assert "name" in employee',
            '    assert "department" in employee',
            '    assert "email" in employee',
            '',
            'def test_create_leave_request_updates_balance(api_headers):',
            '    balance_before = requests.get(',
            '        f"{BASE_URL}/leave/balance/1", headers=api_headers',
            '    ).json()["annual_leave"]',
            '',
            '    response = requests.post(f"{BASE_URL}/leave/request", headers=api_headers, json={',
            '        "employee_id": 1,',
            '        "type": "annual",',
            '        "days": 2,',
            '        "reason": "Personal work"',
            '    })',
            '    assert response.status_code == 201',
            '    assert "request_id" in response.json()',
            '',
            '    balance_after = requests.get(',
            '        f"{BASE_URL}/leave/balance/1", headers=api_headers',
            '    ).json()["annual_leave"]',
            '',
            '    assert balance_after == balance_before - 2',
            '```',
            '',
            '#### Step 4 — Run with HTML report',
            '',
            '```',
            'pytest tests/integration/ -v --html=reports/integration.html',
            '```',
            '',
            '#### Step 5 — Parameterize for multiple employees',
            '',
            '```',
            '@pytest.mark.parametrize("employee_id", [1, 2, 3, 5, 10])',
            'def test_payslip_exists_for_active_employees(api_headers, employee_id):',
            '    response = requests.get(',
            '        f"{BASE_URL}/payslip/{employee_id}/latest",',
            '        headers=api_headers',
            '    )',
            '    assert response.status_code == 200',
            '    assert response.json()["net_salary"] > 0',
            '```',
          ),
          items: [
            'Advantage: Full Python logic available in tests — DB queries, complex assertions',
            'Advantage: Same framework and CI config as unit and UI tests, if already used elsewhere',
            'Advantage: Session-scoped fixtures share an auth token across an entire suite',
            'Advantage: pytest-html produces shareable, professional reports',
            'Limitation: Requires Python fluency — not approachable for manual/business testers',
            'Limitation: No GUI for quickly exploring an endpoint ad hoc, unlike Postman',
            'Limitation: Test data cleanup has to be handled manually in code',
            'Limitation: Less visual — harder to demo results to non-technical stakeholders',
          ],
          resources: [{ label: 'pytest.org', url: 'https://pytest.org', kind: 'Docs' }],
          tip: 'Use Postman to explore; use PyTest to lock the contract in CI.',
        },
        {
          title: 'Selenium for frontend-backend integration',
          body: md(
            'Selenium, for integration testing, is used to test the integration between the browser-rendered frontend and the backend services — it clicks real UI elements and verifies that the correct data flows through to the backend and back. While Selenium has largely been replaced by Playwright for new projects, it remains widely deployed in existing enterprise frameworks and is still a valid tool for integration-level UI testing. Its WebDriver protocol controls real browsers, and its `WebDriverWait` with `expected_conditions` handles dynamic page elements. Selenium Grid extends it to run integration tests in parallel across multiple browsers simultaneously.',
            '',
            '#### Step 1 — Install Selenium',
            '',
            '```',
            'pip install selenium webdriver-manager',
            '```',
            '',
            '#### Step 2 — Set up the driver',
            '',
            '```',
            'from selenium import webdriver',
            'from selenium.webdriver.chrome.service import Service',
            'from webdriver_manager.chrome import ChromeDriverManager',
            'from selenium.webdriver.common.by import By',
            'from selenium.webdriver.support.ui import WebDriverWait',
            'from selenium.webdriver.support import expected_conditions as EC',
            '',
            'driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))',
            'wait = WebDriverWait(driver, 10)',
            '```',
            '',
            '#### Step 3 — Login and verify dashboard loads',
            '',
            '```',
            'def test_login_integrates_with_session(driver):',
            '    driver.get("https://staging.hrms-app.com/login")',
            '',
            '    driver.find_element(By.ID, "email").send_keys("hr@company.com")',
            '    driver.find_element(By.ID, "password").send_keys("Admin@1234")',
            '    driver.find_element(By.CSS_SELECTOR, "button[type=\'submit\']").click()',
            '',
            '    dashboard = wait.until(',
            '        EC.visibility_of_element_located((By.CSS_SELECTOR, ".dashboard-header"))',
            '    )',
            '    assert dashboard.is_displayed()',
            '    assert "dashboard" in driver.current_url',
            '```',
            '',
            '#### Step 4 — Form submission integrates with database',
            '',
            '```',
            'def test_leave_form_submission_shows_confirmation(driver, auth_session):',
            '    driver.get("https://staging.hrms-app.com/leave/apply")',
            '',
            '    wait.until(EC.element_to_be_clickable((By.ID, "leave-type"))).click()',
            '    driver.find_element(By.CSS_SELECTOR, "option[value=\'annual\']").click()',
            '    driver.find_element(By.ID, "from-date").send_keys("2025-09-15")',
            '    driver.find_element(By.ID, "to-date").send_keys("2025-09-17")',
            '    driver.find_element(By.ID, "reason").send_keys("Family event")',
            '    driver.find_element(By.CSS_SELECTOR, "button.submit-leave").click()',
            '',
            '    success = wait.until(',
            '        EC.visibility_of_element_located((By.CSS_SELECTOR, ".success-toast"))',
            '    )',
            '    assert "Leave request submitted" in success.text',
            '```',
            '',
            '#### Step 5 — Always close the driver after tests',
            '',
            '```',
            'driver.quit()',
            '```',
          ),
          items: [
            'Advantage: Mature, 20+ years in production — huge documentation and community',
            'Advantage: WebDriver protocol works natively with every major browser',
            'Advantage: Selenium Grid distributes tests across machines and browsers in parallel',
            'Advantage: Validates the real frontend-to-backend path, not just the API contract',
            'Limitation: No built-in auto-waiting — flakier than Playwright without careful WebDriverWait usage',
            'Limitation: Slower to author tests than a pure API approach',
            'Limitation: Heavier setup and maintenance overhead than Postman or PyTest',
            'Limitation: Overkill when the integration in question does not touch the UI at all',
          ],
          resources: [{ label: 'selenium.dev', url: 'https://selenium.dev', kind: 'Docs' }],
        },
        {
          title: 'Practical Example',
          body: md(
            'Application: HRMS — Leave request to balance integration.',
            '',
            'Full integration test flow:',
            '',
            '1. POST `/auth/login` → get token, assert status 200',
            '2. GET `/leave/balance/5` → store annual leave balance (12 days)',
            '3. POST `/leave/request` with employee 5, annual leave, 3 days → assert 201, request ID returned',
            '4. GET `/leave/balance/5` again → assert balance is now 9 days',
            '5. GET `/notifications?recipient=manager_id` → assert new notification exists for pending leave',
            '6. PATCH `/leave/request/{id}/approve` → manager approves',
            '7. GET `/leave/balance/5` → balance remains 9 (already deducted at request time)',
            '',
            'Pass: All 7 steps succeed, data flows correctly across all integrated services.',
            '',
            'Fail: Step 4 shows balance still 12 — the leave request service is not integrated with the balance service. A bug unit tests would never find.',
          ),
        },
        {
          title: 'Advantages',
          items: [
            'Catches interface bugs that unit tests are structurally unable to find',
            'Tests real data flow across modules — authentication, database reads/writes, notifications',
            'Postman collections are reusable across dev, staging, and production environments',
            'Faster than system testing — direct API calls without full browser rendering',
            'Automated with Newman or PyTest in CI/CD — runs on every pull request',
          ],
        },
        {
          title: 'Limitations',
          items: [
            'All integrated components must be running — more infrastructure than unit tests',
            'Harder to isolate failure root cause — bug could be in any connected component',
            'Test data management is complex — requests create real records that need cleanup',
            'Slower than unit tests — network calls and service responses add time',
            'Undocumented APIs make integration tests hard to write without trial and error',
          ],
        },
        {
          title: 'When to Use it in a Project',
          body: 'Integration testing begins as soon as two or more components are ready to connect — typically mid-sprint when a feature\'s API and frontend are both available. It runs in CI/CD on every pull request targeting the main branch. A full integration suite must pass before any build is promoted to system testing or staging.',
        },
      ],
      checklist: [
        'I named one seam unit tests cannot see',
        'I know when Postman is enough vs when I need code',
        'I will not use a browser for an HTTP-only contract',
      ],
      practice: {
        title: 'One seam check',
        brief: 'Hit one API with Postman or requests. Assert status + one field. No UI unless the seam is the UI.',
      },
      links: [
        { name: 'Postman', url: 'https://postman.com', kind: 'doc' },
        { name: 'PyTest', url: 'https://pytest.org', kind: 'doc' },
        { name: 'Selenium', url: 'https://selenium.dev', kind: 'doc' },
      ],
    }),

    ch({
      id: 'tbl-system',
      phase: 'Part 1 · Testing by Level',
      level: 'intermediate',
      title: 'System Testing',
      minutes: 45,
      overview:
        'System testing is the testing of a complete, fully integrated application as a whole from the outside. At this level the entire system is tested end-to-end — the UI, the backend APIs, the database, the integrations, the business logic, the security, and the performance — everything together as it will run in production. System testing verifies that the complete assembled system meets every requirement defined in the specification. Unlike unit or integration testing which examine individual pieces and their connections, system testing treats the application as a black box and tests it exactly the way a real user would experience it — navigating through screens, performing operations, and checking results. This is where complete business workflows are tested: a new employee is onboarded, assigned to a department, begins logging attendance, applies for leave, and receives their monthly payslip — all as one connected flow. System testing is performed by a dedicated QA team, not the developers who wrote the code, in an environment that mirrors production as closely as possible.',
      learn: ['Black-box E2E', 'Playwright', 'Selenium'],
      steps: [
        {
          title: 'Why it Matters',
          body: 'System testing is the last major technical quality gate before software reaches users. It validates that the application works not just in component-level pieces but as the unified product a real user will interact with. Bugs found here are more expensive to fix than in earlier levels but far less expensive than bugs found after go-live. System testing also provides the most business-relevant evidence of quality — it proves that the complete user journeys work correctly, which is what stakeholders actually care about. Without system testing, a team releases software that may work perfectly in all its individual parts but fail completely as an integrated whole.',
        },
        {
          title: 'Free tools',
          body: '1. Playwright — 2. Selenium.',
        },
        {
          title: 'Playwright',
          body: md(
            "Playwright is Microsoft's modern browser automation library and currently the best-in-class tool for system testing web applications. Released in 2020, it was built by engineers who previously created Puppeteer at Google, and it fixes the fundamental reliability problems that made Selenium-based system tests notoriously flaky. Playwright's defining feature is its auto-waiting system — every action automatically waits for the target element to be attached, visible, stable, enabled, and receiving events before proceeding, eliminating the vast majority of timing-related test failures. Its locator system searches the DOM fresh on every action rather than storing stale element references. Playwright supports Chromium, Firefox, and WebKit from a single API, meaning your system tests can run on all three major browser engines without changing a line of test code. Its network interception feature lets you mock API responses during system tests to test specific states without needing that state in the database. The Trace Viewer is its most powerful debugging tool — when a system test fails in CI, you download the trace file, open it with `playwright show-trace`, and see a step-by-step replay of exactly what happened including screenshots at every action, network calls made, and console errors. For Python, the `pytest-playwright` plugin integrates seamlessly with pytest, providing browser, context, and page fixtures automatically.",
            '',
            '#### Step 1 — Install Playwright',
            '',
            '```',
            'pip install playwright pytest-playwright',
            'playwright install',
            '```',
            '',
            '#### Step 2 — Set up the project structure',
            '',
            '```',
            'system_tests/',
            '├── tests/',
            '│   ├── test_employee_management.py',
            '│   ├── test_leave_workflow.py',
            '│   └── test_payroll.py',
            '├── pages/',
            '│   ├── login_page.py',
            '│   └── employee_page.py',
            '├── conftest.py',
            '└── pytest.ini',
            '```',
            '',
            '#### Step 3 — Configure conftest.py',
            '',
            '```',
            'import pytest',
            '',
            '@pytest.fixture(scope="session")',
            'def browser_type_launch_args():',
            '    return {"headless": True, "slow_mo": 0}',
            '',
            '@pytest.fixture(scope="session")',
            'def base_url():',
            '    return "https://staging.hrms-app.com"',
            '',
            '@pytest.fixture(scope="function", autouse=True)',
            'def configure_timeouts(page):',
            '    page.set_default_timeout(30000)',
            '    page.set_default_navigation_timeout(60000)',
            '```',
            '',
            '#### Step 4 — Write a complete system test',
            '',
            '```',
            'from playwright.sync_api import Page, expect',
            '',
            'def test_employee_onboarding_complete_flow(page: Page):',
            '    page.goto("https://staging.hrms-app.com/login")',
            '    page.get_by_label("Email").fill("hr@company.com")',
            '    page.get_by_label("Password").fill("Admin@1234")',
            '    page.get_by_role("button", name="Login").click()',
            '    expect(page.get_by_role("heading", name="Dashboard")).to_be_visible()',
            '',
            '    page.get_by_role("link", name="Employees").click()',
            '    page.get_by_role("button", name="Add Employee").click()',
            '',
            '    page.get_by_label("First Name").fill("Anita")',
            '    page.get_by_label("Last Name").fill("Sharma")',
            '    page.get_by_label("Email").fill("anita.sharma@company.com")',
            '    page.get_by_label("Department").select_option("Engineering")',
            '    page.get_by_label("Joining Date").fill("2025-09-01")',
            '    page.get_by_role("button", name="Save").click()',
            '',
            '    expect(page.get_by_text("Employee created successfully")).to_be_visible()',
            '',
            '    page.get_by_role("link", name="Employee List").click()',
            '    expect(page.get_by_role("row", has_text="Anita Sharma")).to_be_visible()',
            '```',
            '',
            '#### Step 5 — Enable tracing for failure debugging',
            '',
            '```',
            '@pytest.fixture(scope="function")',
            'def context(browser):',
            '    context = browser.new_context()',
            '    context.tracing.start(screenshots=True, snapshots=True, sources=True)',
            '    yield context',
            '    context.tracing.stop(path=f"traces/trace_{pytest.current_test}.zip")',
            '```',
            '',
            '#### Step 6 — Run the tests',
            '',
            '```',
            'pytest tests/ -v --html=reports/system_test_report.html',
            '```',
            '',
            '#### Step 7 — View trace on failure',
            '',
            '```',
            'playwright show-trace traces/trace_failed_test.zip',
            '```',
          ),
          items: [
            'Advantage: Auto-waiting removes most timing-related flaky failures automatically',
            'Advantage: One API drives Chromium, Firefox, and WebKit — no per-browser rewrites',
            'Advantage: Trace Viewer replays a failed run step-by-step with screenshots and network calls',
            'Advantage: Network interception mocks specific states without touching the real database',
            'Limitation: Newer tool — smaller long-tail community and fewer legacy integrations than Selenium',
            'Limitation: Teams migrating from Selenium have a real API and mental-model switch to make',
            'Limitation: Best support is in modern language bindings; older stacks may not be first-class',
            'Limitation: Trace files can get large on long test runs, adding storage overhead',
          ],
          resources: [{ label: 'playwright.dev', url: 'https://playwright.dev', kind: 'Docs' }],
        },
        {
          title: 'Selenium',
          body: md(
            "Selenium is the veteran of browser-based system testing with over 20 years of production use. For teams with existing Selenium frameworks or Java/C# backends, Selenium remains a practical choice for system testing. Its WebDriver protocol is supported by every major browser natively. Selenium Grid lets you distribute system tests across many machines and browser combinations simultaneously — essential for large enterprise test suites that need to finish quickly. While newer frameworks like Playwright have surpassed it in developer experience, Selenium's maturity means extensive documentation, a massive community, and integration support in virtually every CI/CD and test management tool in existence.",
            '',
            '#### Step 1 — Install dependencies',
            '',
            '```',
            'pip install selenium webdriver-manager pytest',
            '```',
            '',
            '#### Step 2 — Create a base test fixture',
            '',
            '```',
            'import pytest',
            'from selenium import webdriver',
            'from selenium.webdriver.chrome.service import Service',
            'from webdriver_manager.chrome import ChromeDriverManager',
            '',
            '@pytest.fixture(scope="function")',
            'def driver():',
            '    service = Service(ChromeDriverManager().install())',
            '    options = webdriver.ChromeOptions()',
            '    options.add_argument("--headless")',
            '    options.add_argument("--window-size=1280,720")',
            '    driver = webdriver.Chrome(service=service, options=options)',
            '    driver.implicitly_wait(10)',
            '    yield driver',
            '    driver.quit()',
            '```',
            '',
            '#### Step 3 — Write a system test',
            '',
            '```',
            'from selenium.webdriver.common.by import By',
            'from selenium.webdriver.support.ui import WebDriverWait',
            'from selenium.webdriver.support import expected_conditions as EC',
            '',
            'def test_leave_application_workflow(driver):',
            '    driver.get("https://staging.hrms-app.com/login")',
            '    driver.find_element(By.ID, "email").send_keys("emp@company.com")',
            '    driver.find_element(By.ID, "password").send_keys("Emp@1234")',
            '    driver.find_element(By.CSS_SELECTOR, "button[type=\'submit\']").click()',
            '',
            '    wait = WebDriverWait(driver, 10)',
            '    leave_link = wait.until(',
            '        EC.element_to_be_clickable((By.LINK_TEXT, "Apply Leave"))',
            '    )',
            '    leave_link.click()',
            '',
            '    driver.find_element(By.ID, "leave-type").send_keys("Annual Leave")',
            '    driver.find_element(By.ID, "from-date").send_keys("2025-09-15")',
            '    driver.find_element(By.ID, "to-date").send_keys("2025-09-17")',
            '    driver.find_element(By.ID, "reason").send_keys("Family function")',
            '    driver.find_element(By.CSS_SELECTOR, ".submit-btn").click()',
            '',
            '    success = wait.until(',
            '        EC.visibility_of_element_located((By.CSS_SELECTOR, ".success-message"))',
            '    )',
            '    assert "Leave request submitted" in success.text',
            '    assert "Pending" in driver.find_element(By.CSS_SELECTOR, ".leave-status").text',
            '```',
            '',
            '#### Step 4 — Take screenshot on failure',
            '',
            '```',
            '@pytest.fixture(autouse=True)',
            'def screenshot_on_failure(driver, request):',
            '    yield',
            '    if request.node.rep_call.failed:',
            '        driver.save_screenshot(f"screenshots/{request.node.name}.png")',
            '```',
            '',
            '#### Step 5 — Run tests in parallel with pytest-xdist',
            '',
            '```',
            'pip install pytest-xdist',
            'pytest tests/ -n 4  # run on 4 parallel workers',
            '```',
          ),
          items: [
            'Advantage: 20+ years of maturity — the largest documentation base and community in the space',
            'Advantage: Integrates with virtually every CI/CD and test management tool that exists',
            'Advantage: Selenium Grid scales to large cross-browser, cross-machine test suites',
            'Advantage: Strong fit for teams with existing Java or C# Selenium frameworks',
            'Limitation: No auto-waiting — tests are more flaky by default without careful explicit waits',
            'Limitation: Test authoring is more verbose and slower than Playwright',
            'Limitation: Falling behind on developer experience — weaker debugging tools out of the box',
            'Limitation: Higher long-term maintenance cost as the UI under test evolves',
          ],
          resources: [{ label: 'selenium.dev', url: 'https://selenium.dev', kind: 'Docs' }],
          tip: 'Greenfield UI automation: start Playwright. Existing Java/C# Grid estate: stay on Selenium until you have a migration reason.',
        },
        {
          title: 'Practical Example',
          body: md(
            'Application: HRMS Payroll System.',
            '',
            'Complete system test scenario — full payroll cycle:',
            '',
            '1. Login as Payroll Admin → assert Dashboard visible',
            '2. Navigate to Payroll → Select August 2025 pay period',
            '3. Assert all 47 active employees appear in the payroll run list',
            '4. Click "Process Payroll" → assert confirmation dialog appears',
            '5. Confirm processing → assert status changes to "Processing"',
            '6. Wait for status to change to "Processed" (async job)',
            '7. Click on Employee #5 → assert gross salary, tax, deductions, and net salary are correct',
            '8. Click "Generate Payslips" → assert all payslips marked as generated',
            '9. Logout → login as Employee #5',
            '10. Navigate to Payslips → assert August 2025 payslip is visible with correct net amount',
            '',
            'Pass: All 10 steps succeed, payroll flows end-to-end correctly.',
            '',
            'Fail: Employee cannot see payslip after generation — cross-module visibility bug only detectable at system level.',
          ),
        },
        {
          title: 'Advantages',
          items: [
            'Tests the complete application exactly as users experience it — most realistic test level',
            'Validates end-to-end workflows that cross every module and service',
            'Catches bugs that only appear when the full system runs together',
            'Provides the most business-relevant pass/fail evidence for stakeholders and sign-off',
            "Playwright's trace viewer makes debugging system test failures significantly faster than traditional tools",
          ],
        },
        {
          title: 'Limitations',
          items: [
            'Slowest test level — full browser automation takes seconds to minutes per scenario',
            'Most expensive to maintain — UI changes require corresponding test updates',
            'Difficult to isolate root cause when a system test fails across multiple layers',
            'Requires a complete, stable environment with realistic test data',
            'Cannot cover every possible user path — combinatorial explosion makes full coverage impossible',
          ],
        },
        {
          title: 'When to Use it in a Project',
          body: 'System testing begins after integration testing passes and the full application is deployed to a stable staging environment. Critical path system tests run on every release candidate. A full regression suite runs before every major release, after significant feature additions, and after any architectural change. System tests should never be the only testing layer — they work best as the top of a pyramid with solid unit and integration tests beneath them.',
        },
      ],
      checklist: [
        'I can state a system test as a user goal',
        'I know Playwright auto-wait vs Selenium explicit waits',
        'I will not duplicate unit logic inside an E2E',
      ],
      practice: {
        title: 'One user path',
        brief: 'Automate or manually walk one complete user job on staging. Note where waits or environment data broke the path.',
      },
      links: [
        { name: 'Playwright', url: 'https://playwright.dev', kind: 'doc' },
        { name: 'Selenium', url: 'https://selenium.dev', kind: 'doc' },
      ],
    }),

    ch({
      id: 'tbl-uat',
      phase: 'Part 1 · Testing by Level',
      level: 'intermediate',
      title: 'Acceptance Testing (UAT)',
      minutes: 45,
      overview:
        'User Acceptance Testing, universally called UAT, is the final testing level before software is released to real users or goes live in production. Unlike every preceding test level which is performed by technical teams, UAT is performed by the actual business stakeholders — the end users, the client representatives, the department heads, or the product owners. The fundamental purpose of UAT is not to find technical bugs but to confirm business fitness — that the software genuinely delivers the value it was commissioned to deliver, works the way the business actually operates, and solves the real problems users face in their daily work. UAT is built on real business scenarios, not technical test cases. A payroll manager testing whether the system handles Nepal\'s fiscal year 2081/82 tax slabs correctly is UAT. A department head verifying that the leave approval chain matches the company\'s four-level hierarchy is UAT. An HR director confirming that the appraisal cycle timelines match the performance review calendar is UAT. The software may have passed every unit, integration, and system test in the automation suite and still fail UAT — because the system was technically correct but did not match the reality of how the business operates.',
      learn: ['Business fitness', 'Manual UAT', 'TestRail', 'Jira'],
      steps: [
        {
          title: 'Why it Matters',
          body: 'Requirements are written by humans, interpreted by developers, and reviewed by project managers — three levels of communication where meaning can drift significantly from the original business intent. UAT is where that drift is discovered and corrected before it becomes a production problem. Technical teams sometimes build exactly what the specification said but not what the business actually needed — because the specification itself was incomplete, ambiguous, or misunderstood. UAT catches these gaps when they are still fixable with configuration or code changes rather than costly post-production hotfixes. In regulated industries like banking, healthcare, or government, UAT sign-off is a legal and compliance requirement, not optional.',
        },
        {
          title: 'Free tools',
          body: '1. Manual Testing (Primary) — 2. TestRail (Free Tier) — 3. Jira (Free Tier).',
        },
        {
          title: 'Manual Testing — Primary UAT Method',
          body: md(
            'Manual testing in the context of UAT means real business users sitting with the application and testing it against their actual job responsibilities. There is no tool that replaces human business judgment in UAT — a payroll accountant knows immediately whether a tax calculation looks right in the context of their company, in a way no automated test can assess. The process is structured but not scripted line-by-line: UAT testers are given business scenarios, background context, and test data, and they work through the system the way they would on a normal working day. A UAT tester does not follow a step-by-step script saying "click this button" — they are told "process the August payroll for department Engineering and confirm the output matches the pre-approved salary sheet." How they get there is their business expertise.',
            '',
            '#### Step 1 — Define UAT entry criteria',
            '',
            'Before any user touches the system, confirm:',
            '',
            '- All system tests have passed in the testing environment',
            '- A UAT environment is deployed and stable — separate from dev and testing',
            "- Realistic test data is loaded that represents the business's actual scenarios",
            '- UAT testers (business users) have accounts and access set up',
            '- A UAT schedule is agreed — specific dates, specific testers, specific modules',
            '',
            '#### Step 2 — Write UAT scenarios in business language',
            '',
            'UAT scenarios are not technical test cases. Write them as business tasks:',
            '',
            '```',
            'UAT Scenario: Process Monthly Payroll — August 2025',
            '',
            'Business context:',
            'Our company has 47 employees across 5 departments.',
            'Salary sheet for August was approved by Finance Director on Aug 25.',
            '',
            'What to test:',
            '1. Log in as Payroll Manager',
            '2. Navigate to Payroll Processing',
            '3. Select August 2025 pay period',
            '4. Confirm all 47 active employees appear — note any missing',
            '5. Verify gross salaries match the approved salary sheet (compare 5 random employees)',
            '6. Process payroll and confirm the system accepts it',
            '7. Generate payslips and confirm they look correct and professional',
            '8. Mark as disbursed',
            '',
            'Expected outcome:',
            'All employees processed correctly, payslips generated with correct tax breakdown,',
            'disbursement status updated, employees can view their payslips.',
            '',
            'Pass / Fail: [UAT tester marks here]',
            'Comments: [Any observations, even if passed]',
            '```',
            '',
            '#### Step 3 — Brief UAT testers',
            '',
            'Run a 30-minute briefing: what UAT is for, how to mark pass/fail, how to report a bug, what level of detail to capture in comments. Keep it simple — these are not QA professionals.',
            '',
            '#### Step 4 — Execute UAT sessions',
            '',
            'Have testers work through scenarios. A QA engineer should be present — not to guide, but to take notes, help with environment issues, and ensure bugs are logged properly. Do not correct the tester when they do something unexpected — that unexpected path is real user behaviour and may reveal a gap.',
            '',
            '#### Step 5 — Log all findings',
            '',
            '- Blocker — system cannot go live (wrong calculation, data loss, crash)',
            '- Major — significant business impact but workaround exists',
            '- Minor — cosmetic or inconvenience, acceptable for go-live',
            '',
            '#### Step 6 — Fix, retest, and obtain formal sign-off',
            '',
            'Development team addresses blockers and agreed majors. UAT testers retest specifically those scenarios. When satisfied, the authorised business stakeholder signs the UAT sign-off document — this is the formal acceptance.',
            '',
            '#### Step 7 — Document UAT results',
            '',
            'Produce a UAT completion report: scenarios tested, pass/fail counts, bugs found, bugs fixed, outstanding known issues with accepted risk, and the sign-off signatures. This document is the official evidence that UAT was completed.',
          ),
          items: [
            'Advantage: Applies real business judgment automation structurally cannot replicate',
            'Advantage: Scenarios are business-driven, surfacing exceptions a spec never anticipated',
            'Advantage: Catches requirement drift and specification gaps before go-live',
            'Advantage: Produces the formal, signed acceptance record required for sign-off',
            'Limitation: Business users are not trained testers — coverage can be inconsistent',
            'Limitation: Scheduling time with busy stakeholders is a recurring bottleneck',
            'Limitation: Feedback is often vague and needs a QA engineer to turn into an actionable bug',
            'Limitation: Does not scale to frequent releases the way automated levels do',
          ],
        },
        {
          title: 'TestRail',
          body: md(
            'TestRail is a web-based test case management tool made by Gurock (now part of Idera). For UAT specifically, TestRail lets you create test plans containing business scenarios, assign them to specific UAT testers, and collect structured pass/fail results with comments and attachments. Testers access TestRail through a browser, click each step, and mark it pass or fail — no technical knowledge required. Managers see real-time UAT progress dashboards showing how many scenarios are complete, how many passed, and how many have defects. TestRail\'s free plan supports small teams and is sufficient for most UAT projects. It integrates with Jira so bugs logged in TestRail automatically create Jira tickets.',
            '',
            '#### Step 1 — Create a free TestRail account',
            '',
            'Go to `testrail.com` and sign up for a free account or use their hosted trial.',
            '',
            '#### Step 2 — Create a Project',
            '',
            'Click "Add Project" → Name it "HRMS UAT — August 2025 Release".',
            '',
            '#### Step 3 — Create a Test Suite with UAT scenarios',
            '',
            'Under the project, create a Test Suite called "Payroll Module UAT". Add test cases written as business scenarios (not technical steps). Each case has a title, description, and expected result written in plain English.',
            '',
            '#### Step 4 — Create a Test Plan and assign to UAT testers',
            '',
            'Create a "Test Plan" for the UAT cycle. Assign each test case to the appropriate business user — payroll scenarios to the Payroll Manager, leave scenarios to the HR Director.',
            '',
            '#### Step 5 — Testers execute and record results',
            '',
            'UAT testers log in, see their assigned test cases, work through them, and mark each Pass, Fail, or Blocked with comments.',
            '',
            '#### Step 6 — Track progress and export report',
            '',
            'The manager sees a live dashboard. At UAT completion, export the full results as a PDF for the sign-off record.',
          ),
          items: [
            'Advantage: Structured scenario tracking that non-technical testers can execute unaided',
            'Advantage: Real-time dashboards show UAT progress without chasing anyone for status',
            'Advantage: Direct Jira integration turns a failed case into a bug ticket automatically',
            'Advantage: Free tier is workable for a typical small UAT cycle',
            'Limitation: Free tier caps users and projects — a constraint on larger UAT rounds',
            'Limitation: Someone still has to author good business-language scenarios up front',
            'Limitation: One more tool for already-busy stakeholders to get oriented in',
            'Limitation: Limited value on its own without a bug tracker connected to it',
          ],
          resources: [{ label: 'testrail.com', url: 'https://testrail.com', kind: 'Docs' }],
        },
        {
          title: 'Jira',
          body: md(
            'Jira is the most widely used issue tracking platform, made by Atlassian. During UAT, it serves as the bug and feedback repository — when a UAT tester finds a problem, a Jira ticket is created. The ticket captures: what was being tested, what was expected, what happened, and the severity. Developers pick up these tickets, fix the issues, and transition the ticket to "Ready for Retest". The UAT tester retests and closes the ticket or reopens it. Jira\'s free tier supports up to 10 users, making it accessible for small UAT teams. Its Kanban board gives a visual overview of all UAT findings and their current fix status.',
            '',
            '#### Step 1 — Create a free Jira account',
            '',
            'Go to `atlassian.com/software/jira` and create a free account. Create a project named "HRMS UAT Bugs".',
            '',
            '#### Step 2 — Configure issue types',
            '',
            'Ensure your project has issue types: Bug (for defects found in UAT), Task (for retest activities), and Feedback (for non-bug observations).',
            '',
            '#### Step 3 — UAT testers log bugs',
            '',
            '- Summary: Short description — "Payslip shows wrong tax amount for employees above NPR 700,000"',
            '- Description: Steps taken, expected result, actual result',
            '- Priority: Blocker / Major / Minor',
            '- Attachments: Screenshot of the wrong value',
            '',
            '#### Step 4 — Development team works the queue',
            '',
            'Developers filter Jira for open UAT bugs, fix them, and transition to "Fixed — Ready for UAT Retest".',
            '',
            '#### Step 5 — UAT tester retests and closes',
            '',
            'Tester retests the specific scenario, confirms the fix, and closes the ticket or reopens with comments.',
            '',
            '#### Step 6 — UAT sign-off',
            '',
            'When all Blocker and agreed Major tickets are closed, generate a Jira report showing zero open blockers — attach this to the formal UAT sign-off document.',
          ),
          items: [
            'Advantage: Industry-standard issue tracking most teams already know',
            'Advantage: Kanban board gives a visual read on every open UAT finding at a glance',
            'Advantage: Free tier covers up to 10 users, enough for most UAT teams',
            'Advantage: Clear fix loop: open → fixed → ready for retest → closed',
            'Limitation: Not a test case manager by itself — needs TestRail or similar alongside it',
            'Limitation: 10-user free cap can be limiting once stakeholders are added in',
            'Limitation: Can get cluttered and noisy without disciplined ticket hygiene',
            'Limitation: UAT-specific workflows and fields need to be configured, not default',
          ],
          resources: [{ label: 'Jira', url: 'https://atlassian.com/software/jira', kind: 'Docs' }],
          tip: 'TestRail holds the scenarios. Jira holds the findings. Mixing both into one ticket pile hides coverage.',
        },
        {
          title: 'Practical Example',
          body: md(
            'Application: HRMS — Leave policy compliance UAT.',
            '',
            'UAT Tester: HR Director with 15 years of company HR experience.',
            '',
            'Scenario tested: Over-limit leave request. The HR Director tests applying 3 days of casual leave for an employee who has only 2 days remaining. She expects the system to reject this with a clear message showing the available balance. In UAT, the system approves the request without warning. All unit tests, integration tests, and system tests passed because test data always had sufficient leave balances — nobody tested the boundary condition with real business knowledge.',
            '',
            'UAT Fail result: The system violates the company\'s HR policy by allowing negative leave balances. The HR Director marks this as a Blocker — the system cannot go live with this behaviour because it would cause payroll complications and policy non-compliance.',
            '',
            'Development fix: Add balance validation before leave approval.',
            '',
            'UAT Retest result: Pass — system now shows "Insufficient casual leave balance. Available: 2 days, Requested: 3 days. Request rejected."',
            '',
            'Sign-off: HR Director signs UAT acceptance after all blockers resolved.',
          ),
        },
        {
          title: 'Advantages',
          items: [
            'Validates business requirements in real-world terms — not just technical specifications',
            'Performed by people who understand the actual business workflows and exceptions',
            'Catches requirement mismatches and specification gaps that technical testing misses entirely',
            'Builds genuine user confidence and buy-in before go-live',
            'Produces formal signed documentation for compliance, audit, and contractual purposes',
          ],
        },
        {
          title: 'Limitations',
          items: [
            'Business users are not trained testers — they may miss edge cases or test inconsistently',
            'Time and schedule coordination with busy stakeholders is consistently challenging',
            'UAT environments need realistic data — hard to prepare without touching sensitive production data',
            'Feedback can be subjective or vague — requires a QA engineer to translate into actionable bug reports',
            'Running UAT on an unstable system wastes stakeholder time and damages confidence in the project',
          ],
        },
        {
          title: 'When to Use it in a Project',
          body: 'UAT is mandatory before every production release without exception. In agile projects, a lightweight UAT review happens at the Sprint Review with product owners. Full formal UAT with sign-off happens before every major release to production. It is never skipped — if a go-live proceeds without UAT sign-off, the business must document that decision and accept the risk formally in writing.',
        },
      ],
      checklist: [
        'I wrote one scenario with no UI jargon',
        'I know why UAT stays mostly manual',
        'I can split scenarios (TestRail) from bugs (Jira)',
      ],
      practice: {
        title: 'UAT packet',
        brief: 'Three business scenarios + a one-line pass/fail log. Ask a non-engineer if they could run them without you.',
      },
      links: [
        { name: 'TestRail', url: 'https://testrail.com', kind: 'doc' },
        { name: 'Jira', url: 'https://atlassian.com/software/jira', kind: 'doc' },
      ],
    }),

    ch({
      id: 'tbl-checkpoint',
      kind: 'checkpoint',
      phase: 'Part 1 · Gate',
      level: 'intermediate',
      title: 'Checkpoint: pick the right level',
      minutes: 25,
      durationLabel: 'Gate',
      overview:
        'Prove you can assign a test to a level and a tool without inflating the pyramid. Four levels, ten tools, free tier — use them on purpose.',
      learn: ['Level selection', 'Tool tradeoffs', 'Pyramid hygiene'],
      steps: [
        {
          title: 'Assign four tests',
          body: 'Take one feature. Write four tests — one per level — and name the tool you would use, plus one limitation you accept.',
          doThis: 'Publish a one-pager: feature, four tests, four tools, four limitations.',
          items: [
            'Unit — JUnit, PyTest, or Jest',
            'Integration — Postman, PyTest, or Selenium',
            'System — Playwright or Selenium',
            'UAT — manual + TestRail + Jira',
          ],
        },
        {
          title: 'Kill one redundant E2E',
          body: 'If you already have a unit test for the calculation and an API test for the contract, the browser path should only prove the user can finish the job. Cut anything else.',
          quiz: {
            question: 'A discount formula is wrong. Which level should catch it first?',
            options: ['Unit', 'Integration', 'System', 'UAT'],
            answer: 0,
            explain: 'A formula is a unit. System and UAT may still fail, but they are the expensive place to learn that math is wrong.',
          },
        },
      ],
      checklist: [
        'Four tests mapped to four levels',
        'Each tool has a named limitation',
        'No E2E that only re-proves a unit',
      ],
      practice: {
        title: 'Level one-pager',
        brief: 'Share the four-test map with a peer. If they cannot tell the levels apart from your wording, rewrite.',
      },
    }),
  ],
  resources: {
    docs: [
      { name: 'JUnit', url: 'https://junit.org' },
      { name: 'PyTest', url: 'https://pytest.org' },
      { name: 'Jest', url: 'https://jestjs.io' },
      { name: 'Postman', url: 'https://postman.com' },
      { name: 'Playwright', url: 'https://playwright.dev' },
      { name: 'Selenium', url: 'https://selenium.dev' },
      { name: 'TestRail', url: 'https://testrail.com' },
      { name: 'Jira', url: 'https://atlassian.com/software/jira' },
    ],
    tools: ['JUnit', 'PyTest', 'Jest', 'Postman', 'Playwright', 'Selenium', 'TestRail', 'Jira'],
    practice: ['Map one feature to all four levels before adding more E2E.'],
  },
}
