import type { ChapterRecord } from "../../../types";

/** 49. Interview Prep */
export const chapter = {
  id: "pw-49-interview",
  title: "49. Interview Prep",
  minutes: 40,
  level: "intermediate",
  phase: "Part 7 · Real-World Project & Job Readiness",
  partName: "Part 7 · Real-World Project & Job Readiness",
  overviewText: "Common Playwright interview topics: auto-waiting vs Selenium, POM rationale, flake diagnosis, CI integration, API+UI hybrid, and scenario-based comparison answers.",
  why: "Interviewers test judgment with scenarios, not command recitation. Prepared framing turns experience into credible narrative.",
  when: "Read two weeks before Playwright/SDET interviews; practice answers aloud.",
  practical: { app: "SDET technical interview", scenario: "'Why Playwright over Selenium?' and 'How do you handle flaky tests?'", pass: "Architecture comparison + concrete flake workflow (trace, quarantine, root-cause fix).", fail: "List API methods without explaining auto-waiting or CI artifact strategy." },
  advantages: ["Scenario-based answers demonstrate hands-on judgment","Playwright vs Cypress comparison shows architectural awareness","Flake diagnosis story uses trace viewer concretely","POM explanation ties to maintenance cost not pattern worship","CI integration answer shows production mindset","API+UI hybrid demonstrates full-stack test thinking"],
  limitations: ["Memorized answers sound robotic without real project backing","Interview focus varies — some teams test algorithms not automation","Tool comparisons outdated if interviewer uses proprietary framework","Live coding nerves override prepared talking points","Take-home assignments may test different skills than verbal prep","Over-preparing comparisons neglects domain-specific app knowledge"],
  tools: [],
  contentMarkdown: "## Interview Prep\n\nInterviews for QA automation roles tend to test three distinct things — technical depth, judgment, and communication — not just \"do you know the API.\" Live-coding a locator or a small test is common, but so is being asked to explain a decision (\"why would you choose get_by_role over a CSS selector here\") or to critique a piece of existing test code — preparation should cover all three, not just memorizing API syntax.\n\nCommon technical questions worth being genuinely fluent in, not just able to look up. Playwright vs. Selenium vs. Cypress (Chapter 1's comparison table, including the \"why\" behind each row, not just the row contents). Auto-waiting mechanics — what actionability checks actually run before an action (Chapter 16). Locator strategy and the specific reasoning for preferring role/test-id over CSS/XPath (Chapter 13). Page Object Model — not just \"what is POM\" but why it helps and what a test file without it looks like in practice (Chapter 23). Flaky test diagnosis — being able to walk through a systematic root-causing process (Chapter 38) rather than a vague \"just rerun it\" answer signals real experience.\n\nBehavioral/scenario questions probe judgment under realistic constraints, not textbook knowledge. Examples worth having a real, specific answer for (not a generic one): \"A test has been flaky for two weeks and no one's fixed it — what do you do?\" (tests the quarantine + root-cause discipline from Chapter 38, and the courage to flag it rather than just re-running it). \"You're asked to automate a feature that's still being actively redesigned — how do you respond?\" (tests the automation-ROI judgment from Part 0, Chapter 6). \"The suite takes 45 minutes and blocks every PR — what levers would you pull?\" (tests Chapter 44/46's suite-scaling and performance material together). Preparing a specific, concrete story for questions like these — ideally drawn from actual capstone-project or Bizlevate experience — is far stronger than a rehearsed general answer.\n\nA locator-strategy or test-design live exercise is one of the most common practical formats — practice it directly. Being handed a snippet of HTML or a live webpage and asked \"how would you locate this element, and why\" is extremely common; practicing this out loud, articulating the reasoning (not just producing a working locator), is worth deliberate rehearsal, since interviews reward visible reasoning as much as a correct final answer.\n\nSystem-design-style questions appear more often at senior levels — \"design a test framework for X.\" Being asked to sketch a framework for a hypothetical app (folder structure, fixture strategy, CI approach, how you'd handle auth/data) is effectively asking you to reproduce the reasoning from Part 6 out loud — this is a strong argument for genuinely internalizing why each Part 6 decision was made, not just being able to describe what a framework looks like.",
  customSummary: "## Interview Prep\n\nInterviews test technical depth, judgment, and communication together — prep for live-coding, decision explanations, and code critique, not just API recall.\nBe genuinely fluent (not just able to look up) in: Playwright vs. Selenium vs. Cypress reasoning, auto-waiting mechanics, locator strategy reasoning, why POM helps, and systematic flaky-test root-causing.\nPrepare specific, real stories (ideally from capstone/Bizlevate work) for judgment scenarios: a long-standing flaky test, an unstable feature someone wants automated, a suite that's grown too slow.\nPractice live locator/test-design exercises out loud — reasoning is evaluated as much as the final answer.\nAt senior levels, expect \"design a framework for X\" — effectively asking you to reproduce Part 6's reasoning live.",
  exercises: [],
  resourceLinks: [],
  steps: [],
  learn: [],
} as ChapterRecord;
