// ⚙️ AUTO-GENERATED by scripts/generate-chapter-index.mjs — do not edit by hand
import type { ChapterRecord } from "../../types";

import { chapter as part_0_chapter_1 } from "./part-0/chapter-1";

export const chapterPaths: Record<string, string> = {

};

export const chapters: ChapterRecord[] = [
  part_0_chapter_1
];
