import type { ChapterRecord } from "../../../types";

/** 16. Waits & Auto-waiting */
export const chapter = {
  id: "pw-16-waits",
  title: "16. Waits & Auto-waiting",
  minutes: 35,
  level: "intermediate",
  phase: "Part 2 · Core Interactions",
  partName: "Part 2 · Core Interactions",
  overviewText: "Playwright's five actionability checks, built-in auto-waiting on actions and expect(), page.wait_for_load_state(), page.wait_for_selector(), page.wait_for_url(), and why time.sleep() is an anti-pattern.",
  why: "Understanding auto-waiting internals explains 80% of Playwright-vs-Selenium flake differences. Explicit waits are escape hatches, not defaults.",
  when: "Read when tempted to add time.sleep(). Revisit for SPA navigation timing and networkidle pitfalls.",
  practical: { app: "React SPA with client-side routing", scenario: "Test passes locally, flakes in CI after clicking nav link.", pass: "expect(page).to_have_url(re.compile(r'/dashboard')) — auto-waits for route.", fail: "time.sleep(5) after every navigation click." },
  advantages: ["Five actionability checks before every click/fill","expect() and actions share same retry engine","wait_for_url() handles SPA client-side routing","wait_for_selector(state='hidden') for spinners","Default timeout configurable globally in playwright.config","Zero sleep needed for 90% of real-world flows"],
  limitations: ["networkidle dangerous on SPAs with persistent websockets","wait_for_load_state('networkidle') often never resolves","Explicit waits can mask missing assertions","time.sleep() still tempting for beginners — always wrong","Custom loading indicators need locator-based waits not load_state","Race conditions still possible across multiple tabs"],
  tools: [],
  contentMarkdown: "## 16. Waits & Auto-waiting\n\nPlaywright runs an actionability checklist before most actions.\nBefore performing most actions, Playwright checks that the target element is: Attached (present in the DOM at all), Visible (non-zero size, not display: none/visibility: hidden), Stable (stopped moving/animating, checked across at least two animation frames), Enabled (not disabled), and able to receive events (not covered by another element, like a loading spinner overlay). Playwright re-checks this list repeatedly until all conditions pass or the timeout is hit — this is exactly why you rarely need manual waits.\nwait_for_selector() waits for an element to reach a specific state.\n```python\npage.wait_for_selector(\".spinner\", state=\"hidden\")   # wait for loading spinner to disappear\npage.wait_for_selector(\".results\", state=\"visible\")\n```\n\n\nselector (string, required) is a CSS/XPath selector for the target element. state (string, optional, default \"visible\") can be \"attached\" (present in DOM regardless of visibility), \"detached\" (removed from DOM), \"visible\" (present and visibly rendered), or \"hidden\" (present but not visible, or removed entirely). Use this for state-based waits that plain auto-waiting doesn't cover directly — e.g., waiting for a spinner to hit \"hidden\" before checking the results underneath it.\nwait_for_load_state() waits for a page-level loading milestone.\n```python\npage.wait_for_load_state(\"networkidle\")   # no network activity for 500ms\npage.wait_for_load_state(\"domcontentloaded\")\npage.wait_for_load_state(\"load\")\n```\n\n\nstate (string, optional, default \"load\") can be \"load\" (the full page load event has fired), \"domcontentloaded\" (HTML parsed, DOM ready, before images/styles finish), or \"networkidle\" (no network connections for at least 500ms). \"networkidle\" is handy after actions that trigger background calls with no specific element to target as a wait signal — but avoid it on pages with continuous polling (common in dashboards), since the network will never go fully idle and the wait will simply time out.\n### Manual sleep() should essentially never be used.\n\n```python\n# Avoid this:\n```\n\ntime.sleep(3)\n```python\npage.click(\".submit-button\")\n\n# Prefer this:\npage.get_by_role(\"button\", name=\"Submit\").click()   # auto-waits already\n```\n\n\nA hard sleep() is a lose-lose: too short and the test is flaky; too long and every run wastes time even when the app responded instantly. Auto-waiting solves both problems simultaneously. The only legitimate reasons to add explicit waits are the state-based cases above (wait_for_selector, wait_for_load_state) — never as a blanket \"just in case\" habit.",
  customSummary: "## 16. Waits & Auto-waiting\n\nBefore most actions, Playwright checks: attached, visible, stable, enabled, receives events — retried until timeout.\nwait_for_selector(selector, state=...) — waits for attached/detached/visible/hidden state.\nwait_for_load_state(state) — \"load\", \"domcontentloaded\", \"networkidle\" (avoid on pages with continuous polling).\nNever use time.sleep() — always too short (flaky) or too long (wastes time); rely on auto-waiting or the state-based waits above.",
  exercises: [],
  resourceLinks: [],
  steps: [],
  learn: [],
} as ChapterRecord;
